### ISSUE TITLE
Auto delete comments older than X time to reduce ram usage.

### ISSUE THREAD

**Issue by leem32** [umputun/remark42#1055]
Looking at my server resource usage which has 12GB Ram, I notice Remark42 server is now using 8.8% of total Ram.

I don't remember Remark42 using such a high amount of Ram before (I would definitely have noticed), so I'm assuming this has increased over time based on the number of comments posted on my site. Is this correct? will Remark42 Ram usage increase based on number of comments Remark42 is holding?

Is there any way to decrease the amount of Ram Remark42 is using?
One way could be to automatically delete comments older than X time.
There isn't much value for my site in comments older than 12 months, so I would like Remark42 to delete them.

Its not really practical me deleting them manually because they're spread over hundreds of pages. 

Note: Also Remark42 server on my dev server only uses 0.6% Ram of  4GB total Ram, so total comments is obviously causing this huge increase in production server.

**Comment by umputun** [comment]
pls, use discussions for questions like this. 

moved
