### ISSUE TITLE
Deploying in Heroku

### ISSUE THREAD

**Issue by bevsxyz** [umputun/remark42#1066]
Hi,
I had tried to deploy remark42 with docker to Heroku, but I couldn't get it working. Are there any resources on how to do it? Has anyone got it working successfully?

I'll get back with more details on my attempt.

**Comment by umputun** [comment]
pls use discussions for questions like this. Issues are for the actual issues and remark42 has nothing special that makes it non-deployable to a particular platform.

_Moved to dicussion_
