### ISSUE TITLE
White text on white background color in Chrome in MacOS

### ISSUE THREAD

**Issue by obask** [umputun/remark42#1069]
<img width="1234" alt="Screen Shot 2021-07-28 at 3 37 13 PM" src="https://user-images.githubusercontent.com/13053173/127405258-f79c1a69-7de4-4fe6-8fb5-53f2b0052e8e.png">
Google Chrome is up to date
Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by akellbl4** [comment]
I see a problem with the frontend build. I'll check why it happens.

**Comment by akellbl4** [comment]
Should be fixed ;)
