### ISSUE TITLE
fix error screen on comments request in profile popup

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#1084]
- create a better layout
- add retry button

<img width="397" alt="CleanShot 2021-08-09 at 00 05 10@2x" src="https://user-images.githubusercontent.com/2330682/128645669-09404182-8110-4f37-a6e6-3ff0902223d4.png">

**Comment by esvyridov** [comment]
@akellbl4 can this issue be closed after https://github.com/umputun/remark42/pull/1110 was merged?

**Comment by akellbl4** [comment]
Resolved. @esvyridov thank you!
