### ISSUE TITLE
show total number of comments in profile

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#1085]
this endpoint `/api/v1/comments` returns the total number of user's comments
we can show it on the profile screen

_If you'd like to work on this ping me and I'll bring design for it._

**Comment by esvyridov** [comment]
@akellbl4 Hi, I would take this issue

**Comment by akellbl4** [comment]
@esvyridov hey! I checked the UI and found out that we have the title "My recent comments" or "Recent comments".
In my opinion, the best place is right next to the title. It led me to change that title to "My comments" / "Comments".
But in this case, it could be awesome to add the ability to check all user's comments. 

As I can see method `/api/v1/comments?site={site}&user={user_id}` has only limiter with `limit={number}` but doesn't have pagination with `skip={number}`. It means we need to have that ability on the server-side and then add "show more comments" for looking at older comments of a user.

@paskal @umputun could we add `skip` parameter to `/api/v1/comments?site={site}&user={user_id}`

**Comment by akellbl4** [comment]
Design proposal is [here](https://www.figma.com/file/UKUj98QJOGMnqH8Huuv3P8/Remark42-Profile-comments-counter?node-id=0%3A1)

**Comment by esvyridov** [comment]
@akellbl4 looks good. I'll start to work after we get some information about `skip` param.
It looks like `count` param counts deleted comments. I think it can be confusing for a user if I put that number into UI.

![image](https://user-images.githubusercontent.com/46542370/131260172-56278b17-53e0-43af-ad6f-8278fe6aa12a.png)

**Comment by umputun** [comment]
I have added support of `skip` query param to `/api/v1/comments?site=siteID&user=id&limit=123&skip=10` endpoint

**Comment by umputun** [comment]
> It looks like count param counts deleted comments. I think it can be confusing for a user if I put that number into UI.

It is confusing, however, I don't have an effective solution for this problem yet. This should not affect your UI work and as soon as figure how to filter deleted, the same API will return an altered count.

**Comment by esvyridov** [comment]
@umputun sounds good, thank you
@akellbl4 I'll start to work on comments counter and "load more" button very soon

**Comment by akellbl4** [comment]
@esvyridov sounds great!

**Comment by esvyridov** [comment]
@akellbl4 PR is ready https://github.com/umputun/remark42/pull/1176
@umputun can I try to resolve the issue with `count` property in `/comments` response which we discussed above?

**Comment by umputun** [comment]
> @umputun can I try to resolve the issue with `count` property in `/comments` response which we discussed above?

sure

**Comment by paskal** [comment]
It works, resolving.
<img width="376" alt="image" src="https://github.com/umputun/remark42/assets/712534/50d661a7-3955-4c09-8c39-b91a82c50552">
