### ISSUE TITLE
TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by vahidtakro** [umputun/remark42#1109]
I get this error while running on react nextjs
![Clkapture](https://user-images.githubusercontent.com/40500566/129987899-c3d25705-9806-4a98-9fc3-1e5d8db6a2a3.JPG)

**Comment by akellbl4** [comment]
@vahidtakro It's not a remark42's issue. Pls, use [this discussion](https://github.com/umputun/remark42/discussions/1106) to post any problems and I'll try to help.
