### ISSUE TITLE
this is not enough info to help you. I would suspect misconfigured auth, but can't tell for sure without additional details, like your configuration settings.

### ISSUE THREAD

**Issue by drkamine** [umputun/remark42#1120]
this is not enough info to help you. I would suspect misconfigured auth, but can't tell for sure without additional details, like your configuration settings.

_this is not a bug report, but rather some configuration issue; moved to discussions_

_Originally posted by @umputun in https://github.com/umputun/remark42/issues/1118#issuecomment-910044225_

HELLO HERE IS MY CONFIGURATION  i can login with GITHUB WITHOUT ANY ISSUE BUT SAME ISSUE 

 version: '2'

services:
    remark:
        build: .
        image: umputun/remark42:latest
        container_name: "remark42"
        hostname: "remark42"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        # uncomment to expose directly (no proxy)
        ports:
          - "8080:8080"    #VERY IMPORTANT : DO NOT CHANGE THIS.

        environment:
            - REMARK_URL=http://remark.XXXX WEBSITE
            - SECRET=HERE MY ROOT PASSWORD 
            - SITE=remark. 
            - STORE_BOLT_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - DEBUG=true
            - AUTH_GITHUB_CID=cdb733f776c60710d324
            - AUTH_GITHUB_CSEC=f7d52637377035f540aefcadd40f9c767322a66f
            - ADMIN_SHARED_ID=github_48792324
            # - ADMIN_PASSWD=password
        volumes:
            - ./var:/srv/var
~

**Comment by umputun** [comment]
pls, don't make new issues for this. I have moved your issue to discussion, so use it to provide all the details 

https://github.com/umputun/remark42/discussions/1119
