### ISSUE TITLE
[doc] Expand menu

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#1168]
Menu items like [the one below](https://remark42.com/docs/contributing/development/) should be expanded by default, now they are invisible before you click the parent category.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/712534/140644680-0650f071-8268-4a26-a894-e5b3fd8900f5.png">
->
<img width="232" alt="image" src="https://user-images.githubusercontent.com/712534/140644688-e556a7ab-f3ee-4998-8f77-e691bc1af853.png">

**Comment by esvyridov** [comment]
@paskal should the "Development" menu item be expandable after the task will be implemented? What do you think about adding an arrow icon on the right side of menu item which opens a submenu?

**Comment by paskal** [comment]
I think, keeping everything expanded all the time would be better: we don't have that many items in the menu to have necessity to hide anything.
