### ISSUE TITLE
Put prebuild html in package as doc

### ISSUE THREAD

**Issue by adfslslddkds** [umputun/remark42#1178]
Remark42 source code comes with remark42 website source code, which contains documentation. Isn't it a good idea to put pre-build html as well? Some github action can build html from source if it changes and put in some folder inside repository for example "doc". So user can just start webserver and  read doc without any worry if node.js dependencies work well.  

Actually now there some problem with docker in "site" folder. It does not build static files to build folder.  It looks like Dockerfile used for some production with reproxy webserver.

**Comment by umputun** [comment]
I'm not sure what the problem is. The current site/Docker file does exactly what it is supposed to do, i.e. build site container. This container serves the site as designed.

> So user can just start webserver and read doc without any worry if node.js dependencies work well.

User can do it now, this is why we build the site image

**Comment by adfslslddkds** [comment]
In current docker-compose file two commads "build" that actually hasn't god any command and "server" that should run "yarn dev" (development webserver) and they both connected to "./build" folder on host. But both of this command useless because they connected to Dockerfile that serves prebuilt static that already stored inside container with reproxy webserver and even has no node.js.  It rums correct production image because 'build' in docker-compose file has no command section. But straight production compose can be just with one option run existing container and open some ports.  

In readme.md it said that compose can be used for development. So I think it will be good to fix development option or completely remove it. 

And static section of issue is because someday build process can be broken. It is the point.

**Comment by umputun** [comment]
to me, this site/docker-compose.yml looks like some artifact from an early development phase

cc @paskal @akellbl4

**Comment by paskal** [comment]
@akellbl4 must know, it was added deliberately with the new site and should be useful, or fixed if it's not.

**Comment by umputun** [comment]
i think, all we need here is this:

```
version: '2'
services:
  site:
    image: remark42-site
    build: .
    ports:
      - '8080:8080'
```

**Comment by adfslslddkds** [comment]
Good for production usage. Also serving static from container with overleyfs it is not a good practice for highload usage because reading from overlayfs in 10 times slower then from a host filesystem. But for this project it should be enough..
