### ISSUE TITLE
Cursor pointer for editing bar and sort bar 

### ISSUE THREAD

**Issue by meefox** [umputun/remark42#1182]
Small things but UX important.
To get feedback that those are active buttons.

<img width="956" alt="links" src="https://user-images.githubusercontent.com/2067027/142781631-c5a74b09-9268-48ef-b0a5-5d6e36263f38.png">

Solution:
adding `cursor: pointer` for formating toolbar:
frontend/app/components/comment-form/__markdown-toolbar/comment-form__markdown-toolbar.css
`.comment-form__toolbar-item`
and the same property for sort dropdown:
frontend/app/components/select/select.module.css
`.select {}`

**Comment by esvyridov** [comment]
From first sight I would agree that toolbar buttons should have different cursor pointer, but after research it seems that these buttons come from here https://github.com/github/markdown-toolbar-element and they were done as advised here https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html. 

At the same time it seems that bigger part of all active elements in the app have cursor pointer and probably that behaviour should be considered as correct

**Comment by meefox** [comment]
@esvyridov 
Thank you for the explanations, and for showing tracks. 
It is interesting to see how w3 practice is going against a common practice.

But it is not that simple. 
W3 just decided to use whatever is the default provided by the browser, and for the button, it is `cursor: default`. 
Back in the day's button were considered as OS elements with OS behavior. 
Indeed there is no cursor pointer for buttons in OS context by default.
Only nowadays we are running in a web context where is everything clickable has a `cursor: pointer`.
It makes sense to have it.

Sample from https://github.github.com/markdown-toolbar-element/examples/ 
has `cursor: pointer` on the buttons.
W3 toolbar is a very questionable example, I would say it is very generic (should have a tooltip, visible hover, accessible from keyboard).
at the same time non-semantic font increase/decrease buttons (using <span> instead of a <button>), 
and no clear definition for cursor.

wdyt?

**Comment by Mavrin** [comment]
I think we can make cursor `pointer`, because other button use `pointer`. At least we will have consistent behavior for all button. Pull request are welcome.
