### ISSUE TITLE
Cannot get Notifications working

### ISSUE THREAD

**Issue by cooperaj** [umputun/remark42#1189]
Hi, been running this a long time now and wanted to update to a newer version. I'm currently using master (as of this issue) and have followed the documentation. Namely I have configured:

```
NOTIFY_ADMINS:            telegram,email
NOTIFY_EMAIL_FROM:        no-reply@address.org
NOTIFY_TELEGRAM_CHAN:     CHANNEL_NO (e.g. -1001234567890)
NOTIFY_USERS:             email
SMTP_HOST:                smtp.eu.mailgun.org
SMTP_PASSWORD:            PASSWORD
SMTP_PORT:                465
SMTP_TLS:                 true
SMTP_USERNAME:            mailgun@username
TELEGRAM_TOKEN:           BIGTOKEN
```

Outbound Email I know is working as I can 'subscribe' or login and get the emails needed to do that. Telegram looks to be working fine (though I took a while to find the private channel id) as I get notified there 👍 

I don't get any notifications by email though. They just don't show up. Looking in the debug logs I can see that Telegram component does something but no similar log line appears for the email sending. I do see lines for the subscription request (and as I said I get those emails fine).

**Comment by JonnieCache** [comment]
also seeing this behavior

**Comment by paskal** [comment]
Will investigate it this week.

**Comment by BenRoe** [comment]
Hello,
do i have to set the channel id for `NOTIFY_TELEGRAM_CHAN` or a name?
I asked, because i don't get notification too. 
Should also mentioned in the [docs](https://github.com/umputun/remark42/blob/master/site/src/docs/configuration/notifications/index.md#telegram-notifications-for-administrators), what to set for `NOTIFY_TELEGRAM_CHAN`.

**Comment by umputun** [comment]
as far as I recall it should be the channel name, not the id. @paskal - correct if wrong

**Comment by cooperaj** [comment]
> as far as I recall it should be the channel name, not the id. @paskal - correct if wrong

If using a private channel you will need the channel ID. This begins with a `-100` I think.

**Comment by BenRoe** [comment]
> > as far as I recall it should be the channel name, not the id. @paskal - correct if wrong
> 
> If using a private channel you will need the channel ID. This begins with a `-100` I think.

Ok for privat channels the channel id, but i use a public channel. It has also a id with `-100`. Should i use the channel id or channel name (username) for `NOTIFY_TELEGRAM_CHAN`?

![Bildschirmfoto_2021-12-15_um_11_47_02](https://user-images.githubusercontent.com/643834/146172936-20c45630-c69f-4e15-b190-a8e57e56bf00.png)

**Comment by BenRoe** [comment]
This could be added to the docs.

How to get the Telegram channel ID:
1. Post a message in the channel you wan't to the ID.
2. Forward this message to `@JsonDumpBot`.
3. The bot answer with a JSON dump. Look for `id` in `forward_from_chat`element.

**Comment by paskal** [comment]
Thanks, @BenRoe, I've updated the documentation and CLI param description in #1197: feel free to leave your review on it.

**Comment by paskal** [comment]
@cooperaj, sorry for taking so long to look into it. Based on the information you provided, I assume that email notifications for administrators are not working due to the lack of the `ADMIN_SHARED_EMAIL` variable, [here](https://remark42.com/docs/configuration/email/#admin-notifications) is the doc on that. Could you please verify if it's the case or not?

**Comment by paskal** [comment]
@cooperaj have you had a chance to look into it?

**Comment by paskal** [comment]
Hey @cooperaj, any updates?

**Comment by cooperaj** [comment]
I'm very sorry, this one has slipped through the cracks. Will take a look tomorrow.

**Comment by cooperaj** [comment]
Ok, so embarrassingly I have missed that config variable.  I've added it now.
