### ISSUE TITLE
[site] Documentation doesn't have anchor links to headers, anchor scrolls too low

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#1198]
1. I've tried to find an anchor like https://remark42.com/docs/configuration/email/#admin-notifications on the page itself and didn't find it, would be nice to have a link to it next to the header.
2. After going by the anchor, the header itself is covered by the navigation of the site which is unexpected, I would expect the header I'm linking to be completely visible.
    Here is the state right now after opening https://remark42.com/docs/configuration/email/#admin-notifications in Safari:
    <img width="907" alt="image" src="https://user-images.githubusercontent.com/712534/146673854-1c9ebc11-43e3-4956-9335-62e605372503.png">
    What I expect to see after going by the link:
    <img width="917" alt="image" src="https://user-images.githubusercontent.com/712534/146673898-5ce330c5-92db-4d05-8323-94e3dbb85d13.png">

**Comment by vanyauhalin** [comment]
Hi, I have added implementation of anchor links in this [pr](https://github.com/umputun/remark42/pull/1255). This solved the first point, but not the second.

**Comment by markmonroy** [comment]
I [created a pull request](https://github.com/umputun/remark42/pull/1555) updating the .tsx that defines the placeholder variable. Total amateur here...no idea how to get this change into my docker image, so fingers crossed that this modification works as I hope.

**Comment by paskal** [comment]
I'm okay with the lack of mentions of the anchor links. At least they work properly now, thanks to @Jaskon. Resolving this issue.
