### ISSUE TITLE
The auth providers names are unreadable in dark mode

### ISSUE THREAD

**Issue by rikdewit** [umputun/remark42#1215]
<img width="330" alt="Screen Shot 2022-01-04 at 22 10 30" src="https://user-images.githubusercontent.com/18494371/148124420-932fd690-f120-4dfe-9268-8d559f278641.png">

**Comment by maxcold** [comment]
Couldn't reproduce the issue (Chrome), has it already been fixed or the issue can only be reproduced in some specific environment?
<img width="322" alt="Screenshot 2022-04-05 at 11 22 48" src="https://user-images.githubusercontent.com/478762/161723123-39b8c049-bb18-42af-bec6-bd84dd9e6fe3.png">
