### ISSUE TITLE
Telegram features not working

### ISSUE THREAD

**Issue by elmaester** [umputun/remark42#1221]
Nothing related to Telegram works for me, starting with Auth. Nothing related to Telegram appears in the Sign In dropdown UI.

I've double checked that my token is correct and bot operational. Docker environment fragment pasted below (data altered for privacy bla).

Google and GitHub auth works for me. Please let me know what I'm doing wrong for Telegram.

```
      - AUTH_TELEGRAM=true                                                                                                           
      - TELEGRAM_TOKEN=501bla8040:AAHjZblaMtblaGh-yrhblagLolPbTRblawU                                                                
      - NOTIFY_ADMINS=telegram                                                                                                       
      - NOTIFY_TELEGRAM_CHAN=-10bla51bla226                                                                                          
      - NOTIFY_USERS=telegram
```

**Comment by paskal** [comment]
Auth doesn't work unless https://github.com/umputun/remark42/issues/707 is resolved, and user notifications unless https://github.com/umputun/remark42/issues/830 is resolved. However, admin notifications should work: please check the log at the moment you post a new comment, there should be an error if a telegram notification can't be sent.
Also, please verify that you are using `master` image and not `latest` as `1.8.1` doesn't have all the features enabled yet, and we are waiting for Telegram auth and user notifications to be implemented to release `1.9.0`.

**Comment by elmaester** [comment]
@paskal I see, thank you for explaining. I will be eagerly awaiting the release then, and maybe I'll switch the image and check notifications. I am indeed using :latest at the moment.

**Comment by elmaester** [comment]
@paskal I'm trying on master and facing a problem:

`remark42  | 	* problem sending admin telegram notification about comment ID c5026c69-965b-48f5-b9b6-4e37d224e9ae to -100bla1708bla: unexpected telegram API status code 400, error: "Bad Request: chat not found"`

I got my channel's ID with the Json Dump Bot method, pretty sure I got it right. Is it a matter of format? I've already tried many options. With " ", without -, without -100, and others. Can't seem to get it to work. What could be the problem?

**Comment by umputun** [comment]
@elmaester is this `-100bla1708bla` a private chat?  If so, did you invite the bot in?

**Comment by elmaester** [comment]
@umputun Ha, I didn't know I needed to 😄 I don't believe it's in the docs. But I did it after your suggestion and it works. Thank you!

**Comment by umputun** [comment]
It is not something related to remark42 implementation but rather how bots work in telegram. But yeah, it is worthing to be mentioned in our docs
