### ISSUE TITLE
Twitter login problems

### ISSUE THREAD

**Issue by pippocarmona** [umputun/remark42#1249]
I've successfully implemented Remark42 on my site. I followed all that was written in the [documentation for authorization](https://remark42.com/docs/configuration/authorization/). Gmail and Facebook work flawlessly. However, while Twitter allows me to login, I am given the wrong profile and am unable to comment. The pic below shows what happens when I try to login via Twitter.

![remark42screenshot](https://user-images.githubusercontent.com/94895665/151927043-99e3c6e5-065f-4157-a78b-240c8f9cec88.png)

I tried to login via Twitter in the official Remark42 demo page and it seems to work fine as it properly shows my actual account and it allows me to comment, so it seems that my profile isn't really the problem.

**Additional details:**

On the Twitter app side, I've implemented both OAuth1 and OAuth2. I tinkered for some time, activating just one of either to see if it works, but nothing worked.

For "Type of App" I chose "Web App".

Callback URL and website URL both work fine. I followed what was said in the official documentation.

I also tried implementing a privacy policy declaration to see if that'll make things work, but it didn't. 

For  `AUTH_TWITTER_CID` and `AUTH_TWITTER_CSEC`, I used the consumer API key and consumer secret API key respectively as written in the documentation.

**Comment by paskal** [comment]
I don't have Twitter to reproduce that. Would someone be so kind as to verify if `v1.9.0` and `master` work with Twitter credentials created before? If yes, the second step (ideally) would be following [the guide](https://remark42.com/docs/configuration/authorization/#twitter) to create new credentials and check if it works and adjust the document if something is off.

I think you should check the logs for all messages after Twitter login as the error might pop up there, and also, it might be possible that adblocker is messing up with authorization.

**Comment by umputun** [comment]
it works on [demo](https://remark42.com/demo/) site just fine. Credentials were created at least a year ago

**Comment by paskal** [comment]
@pippocarmona, in the log please also include the version which is printed somewhere near the start of the application.

**Comment by akellbl4** [comment]
As I can see if a user doesn't have any comments then the server returns error 400 with data:
```
{
    "code": 1,
    "details": "can't get comment by user id",
    "error": "no comments for user twitter_500c776ee5c34f78a7e410277bf9f8f1ecd34145 in store"
}
```

Could we change this error to status 200 and empty array?

**Comment by pippocarmona** [comment]
So I managed to resolve the issue. The problem was, I think, Twitter's latest API version offering.

The way to make Twitter sign-in work is to upgrade the API level from the basic `Essential` to `Elevated` (pic below for reference). 

![Screenshot_20220208-150707](https://user-images.githubusercontent.com/94895665/152936489-fa21117f-a6ff-4152-9881-984ca5c6fc48.png)

**Comment by paskal** [comment]
This was documented in https://github.com/umputun/remark42/pull/1290.
