### ISSUE TITLE
Create backend-only docker image for development

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#1264]
Recently I've helped a developer set up a development environment for the frontend and saw that multiple times she had to wait for five-ten minutes on the `make rundev` frontend build and test part in case any of the frontend files were changed, despite the fact she didn't need to include frontend build in docker at all.

It would be handy to prepare backend-only Dockerfile which wouldn't rely on frontend at all, and update [frontend development](https://remark42.com/docs/contributing/development/frontend/) guide to rely on it.

**Comment by umputun** [comment]
`make rundev` is sort of "unspecified behavior" as this one runs with `compose-private.yml ` which is not even committed (ignored in fact) and developer can put anything in, including backend-only

the two current `compose-dev-*` files (`compose-dev-backend.yml` and `compose-dev-frontend.yml`) seem to provide the separation you meant, unless I missed the point.

**Comment by 0xmohit** [comment]
`make rundev` works pretty well as documented [here](https://remark42.com/docs/contributing/development/backend/).  However, it'd be nice if the README included a link to [contributing](https://remark42.com/docs/contributing/development/) in the docs.

**Comment by paskal** [comment]
@umputun, my point is not about different docker-compose.yaml file but about different Dockerfile, which would build only backend and not touch frontend at all, as frontend developers run it using `npm` anyway, and don't need static version provided in `umputun/remark42` docker image.

**Comment by umputun** [comment]
got it. probably another pair of ENV values, like SKIP_BACKEND and SKIP_FRONTEND will allow to keep a single dockerfile as all it needs is a couple of ifs
