### ISSUE TITLE
Remove PT Sans as main font OR include it

### ISSUE THREAD

**Issue by isnifer** [umputun/remark42#1268]
Screenshot from someone called Bobuk inside Radio-T chat:
![IMAGE 2022-02-10 11:17:17](https://user-images.githubusercontent.com/1788245/153365723-932d779d-05dd-48ca-ba3d-f47e9389cd98.jpg)

This issue exists due to PT Sans is not being installed on the machine. And this font is not a default one.

**Comment by isnifer** [comment]
@akellbl4 please, watch this ^^

**Comment by akellbl4** [comment]
By default browsers fallback to secondary font in styles. As I understand the user has PT Sans installed in the system and it's corrupted or invalid.

But I agree to change it in favor of default system font like it does by many sites nowadays.
