### ISSUE TITLE
Uncaught Error: window.remark_config is undefined

### ISSUE THREAD

**Issue by gianmarcogg03** [umputun/remark42#1278]
I'm running Remark42 on my Apache webserver with the following config:
```
<script>
  const remark_config = {
    host: 'http://comments.gianmarco.ga',
    site_id: 'comments.gianmarco.ga',
  }
</script>
```
The server seems to work alright:
![image](https://user-images.githubusercontent.com/28053717/154636074-cbd9d930-65da-4a49-bb73-bef5dd062372.png)
![image](https://user-images.githubusercontent.com/28053717/154636095-71b18cbe-5781-4db1-94e0-97ea3008be13.png)
I've put on the webpage the widget but it won't render and in the console I get this error:
![image](https://user-images.githubusercontent.com/28053717/154635677-1c196fd8-4742-49f2-acbb-2c2326c41d3d.png)

**Comment by gianmarcogg03** [comment]
The one that was reported to be working actually works, thank you.

**Comment by paskal** [comment]
@gianmarcogg03 can you please specify, how to change the documentation to fix that issue? Or send a fix yourself, here is the edit page for the Installation documentation: https://github.com/umputun/remark42/edit/master/site/src/docs/getting-started/installation/index.md

**Comment by paskal** [comment]
As far as I can tell, the difference in config definition is `var` in working documentation vs `const` in non-working one, is it the difference that fixed the situation for you?

**Comment by paskal** [comment]
That [seems](https://stackoverflow.com/a/37555378/961092) to be the case, I'll fix it.
