### ISSUE TITLE
Telegram login problems

### ISSUE THREAD

**Issue by ingria** [umputun/remark42#1291]
Telegram auth doesn't work on my website for some reason. UI doesn't show anything besides the `username` field. Submitting the field doesn't seem to do anything (nothing in the logs, no errors, no network requests).

I'm using the latest binary (`remark42 v1.9.0-0521c702`), my config is:

```
SECRET=... REMARK_URL=http://192.168.88.100:8080 SITE=mysite.dev AUTH_TELEGRAM=true AUTH_ANON=true TELEGRAM_TOKEN=TOKEN ./remark42 server --dbg
```
Log doesn't show any errors (but if I change the token to invalid, I can see the error: `failed to make telegram notify service`).

### Screencast

https://user-images.githubusercontent.com/2178368/157490738-f2203b87-d275-41c9-91d8-24a84426bcaa.mp4

**Comment by paskal** [comment]
Unfortunately, telegram auth only works in `master` docker image, could you please switch to it instead of `latest` and verify that it works?

**Comment by ingria** [comment]
Works fine on `master`, thanks!
