### ISSUE TITLE
Code between < and > in code blocks disappears when opened for editing

### ISSUE THREAD

**Issue by ilyapopov** [umputun/remark42#1292]
When creating a comment, I can type code containing `<...>` within a backtick code clock. However, when I open this comment for editing, code between `<` and `>` disappears.

**Comment by paskal** [comment]
Couldn't reproduce it on the current version.
<img width="348" alt="image" src="https://user-images.githubusercontent.com/712534/160303852-078279c6-80db-4c4d-a84e-5a9b92ee4ed5.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/712534/160303860-c0156af1-4207-4844-8324-b8a95b3eae64.png">
Could you please try to reproduce it on the https://remark42.com/demo/, and if you can, try different browsers just to rule out if it's front-end of back-end issue?

**Comment by ilyapopov** [comment]
I have just reproduced it on demo site. I entered 

    `foo<bar>`

and after I clicked "edit" I see 

    `foo`

My browser is Firefox 98.0.2 on Linux. I have also reproduced it on Chromium 99.0.4844.84

**Comment by paskal** [comment]
I can reproduce it on https://remark42.com/demo/ and I don't see any requests sent to the backend before the text appears on screen, I assume that might be a frontend bug. @akellbl4 can you please look into it?

**Comment by akellbl4** [comment]
@paskal it's backend related. Probably backend sanitizing HTML tags.
We send comment text as it is to the backend.

<img width="766" alt="Screen Shot 2022-07-10 at 12 56 28 PM" src="https://user-images.githubusercontent.com/2330682/178160256-190d213f-c1aa-481a-bfc1-da5f939dfca9.png">

**Comment by akellbl4** [comment]
@paskal okay, I figured out the problem that is described.
It's still the BE related in this case.
I have `text` with the whole content and `orig` without part of the content.
![IMAGE 2022-07-10 13:11:14](https://user-images.githubusercontent.com/2330682/178160560-3739cec5-895d-4897-a92f-9c0439ebf7d2.jpg)

**Comment by paskal** [comment]
The issue's root cause is the [following](https://github.com/umputun/remark42/blob/598d7677/backend/app/store/comment.go#L128) line:

```go
c.Orig = p.Sanitize(c.Orig)
```

We need to figure out if we want to sanitize the "orig" field or if it's okay to leave it as-is as the "text" is already sanitised.
