### ISSUE TITLE
Ability to change or remove the "Powered by Remark42" line

### ISSUE THREAD

**Issue by damienalexandre** [umputun/remark42#1305]
Hi :wave: 

This software is great and I'm using it in place of Disqus - a proprietary software in which no one has trust anymore.

And trust is of great importance when we ask for comments on a website. Chances of having user interaction is already small, but having Disqus for example is destroying those chances even further: nobody want to deal with this comment system anymore (it's widely known they sell your data / monitor your activity closely).

So I'm really glad to be able to host a similar system on my servers without any tracking.

But I feel the small text displayed at the end of the form is not adding trust for the end-user.

![image](https://user-images.githubusercontent.com/225704/161737150-ee129afd-39e2-4e42-9d17-14d6dc0fc18b.png)

It feel like we are going to send a form to an external service called Remark42. There is no sign of all the privacy-first and self-hosting this software is about. This does give confidence in the comment system.

Reading something like that **would do better** IMO:

> Powered by privacy first comment system Remark42 and hosted on our servers

To achieve this, being able to use our own translation files is an option?

Also, being able to **remove the sentence completely should be an option**. 

Also, security by obscurity is a thing. The HTTP headers leaking the exact version of the installed software are good for debug, but we have to remove them via a proxy (see OWASP: https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework)

```
app-name: remark42
app-version: master-39c141c-20220325T15:57:58
author: umputun
```

**Comment by umputun** [comment]
agree regarding the second point, #1305  adds `--disable-signature` ($DISABLE_SIGNATURE) parameter for this


However, I'm not sure how removing the link from the footer will give users more confidence. The page it opens literally says all you suggested about privacy-first as well as self-hosted nature. 

Either way, I have no problem if someone wants to add some sort of "no-footer" param and add a translation for this (both on UI/JS side)

**Comment by damienalexandre** [comment]
Thanks a lot for [65e3a82](https://github.com/umputun/remark42/commit/65e3a82d8be93777101df9aef0e1900a0527f267) that's a great addition :+1: 

> Either way, I have no problem if someone wants to add some sort of "no-footer" param and add a translation for this (both on UI/JS side)

Duly noted :+1: I'd love to push some contribution to this project (other than issues :yum:) some day :pray:

**Comment by aanishacharyaa** [comment]
@damienalexandre  Is it implemented ? adding no-footer param? Can you guide me how to remove "powered by remark42"?

**Comment by akellbl4** [comment]
Close this as it was implemented. Thanks @zloylos
