### ISSUE TITLE
Admin "Copy" button doesn't work in Safari

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#1312]
![telegram-cloud-photo-size-2-5368320889772423807-x](https://user-images.githubusercontent.com/712534/162333104-e86126e8-140c-47c2-9aa6-a7876748403f.jpg)
Click on this button in current Safari on Desktop doesn't copy anything into clipboard.

**Comment by akellbl4** [comment]
I've tried to reproduce but for me it works just fine.
I use have Version 15.3 (17612.4.9.1.5) installed.

**Comment by paskal** [comment]
Works in Chrome 100.0.4896.75, Firefox 99.0.
Doesn't work in Safari 15.4, iOS Safari 15.4, iOS Chrome 100.
