### ISSUE TITLE
Incorrect markup when images load not really fast

### ISSUE THREAD

**Issue by vblz** [umputun/remark42#1340]
Environment:
Firefox 99.0 (64-bit) / Linux

WTR:
1. Open new tab
2. In developer tools set up throttling to Regular 3g (easy way to reproduce, but I met the bug originally using regular internet)
3. Open https://remark42.com/demo/
4. Start pressing End button immediately until reaching the first comment

Result:
Several posts are below footer, one of the posts is cropped
![image](https://user-images.githubusercontent.com/2076171/165545626-420d30fa-7b88-407b-a124-4edb2010e6ab.png)

Excepted result:
Images doesn't brake markup after loading

**Comment by vitonsky** [comment]
+1 this bug looks bad
