### ISSUE TITLE
how to tell remark42 about the public url that proxies it?

### ISSUE THREAD

**Issue by Mathias-Fuchs** [umputun/remark42#1360]
Hello,
apologies if this is answered elsewhere, but even though there are very similar issues tracked here, I can't seem to find the solution.
I'm running nginx and proxying remark42 from 127.0.0.1:8080 to https://remark42.mathiasfuchs.com and starting the pre-compiled remark42 with the following command:
``` shell 
 ./remark42.linux-amd64  server  --url=http://127.0.0.1:8080  --site=remark  --secret=12345 --auth.github.cid=fea94ae2d797728f44c8     --auth.github.csec=mysecretid
``` 
but I get the redirect_uri mismatch error from github because remark42 sends the redirect_uri http://127.0.0.1:8080 to github, instead of the correct https://remark42.mathiasfuchs.com .... how can I tell remark42 about the public url of the server?? I don't find any command line option on https://remark42.com/docs/configuration/parameters/ to tell it about it but clearly it should know about it.
Thx, Mathias

**Comment by Mathias-Fuchs** [comment]
oh, seems I just solved it ... one has to say --url=https://remark42.mathiasfuchs.com, and remark42 will automatically guess it should start its server on port 8080 ... ok, interesting. This is not evident from the docs, at least for me.

**Comment by paskal** [comment]
Port 8080 is the default one and can be altered with --port directive. --url used in various places in the backend, including in place you found: for giving the URL to authentication providers so they could redirect the user back after logging in.
