### ISSUE TITLE
Relative URL breaks link on comment timestamp

### ISSUE THREAD

**Issue by irgendwr** [umputun/remark42#1368]
Hi,

in the frontend-config I set the `url` to `window.location.pathname`, so the URL is relative and does not contain the domain.
In the embedded comments widget the timestamps have an `href` that is set to `url` + `#remark42__comment-<ID>`, which leads to the link pointing to `https://remark42.<domain>/<path>#remark42__comment-<ID>` (with the remark subdomain => invalid URL) instead of `https://<domain>/<path>#remark42__comment-<ID>` (correct URL). The last-comments widget on the other hand supports relative URLs, as it does not use an iframe.

**Version:** `v1.9.0-0521c702-20220124T12:35:27`

**Steps to Reproduce:**
1. In the frontend-config, set URL to `window.location.pathname`
2. Post a comment.
3. Click on the comment timestamp
4. => Invalid URL (404)

An example can be found here: https://iwr.sh/posts/example/#remark42

**Workaround:**

The only workaround I can see is not using relative URLs, but I would prefer using them since I only want to associate comments with the path and **not** the domain.

I tried changing the href of the timestamp to only the fragment identifier (`#remark42__comment-<ID>`), but this would also not fix the issue since the link would be relative to the iframe URL, which is also wrong.

I'm not sure if there is a simple solution to this, maybe there should be two separate parameters for the URL used for links and the URL associated with the comment.

**Comment by paskal** [comment]
Hi @irgendwr, can you please verify if `v1.10.1` and `master` are still affected? I don't think it is, but we added an absolute URL to a few places if I'm not mistaken.

**Comment by irgendwr** [comment]
Hi @paskal, I can still reproduce this issue with the current version.

**Comment by akellbl4** [comment]
@irgendwr it works by design. you have to include `domain` or just do not provide a URL and it'll be caught by default.
Maybe it's not the best implementation, but it's nothing we can do with it without breaking things that already work.

**Comment by irgendwr** [comment]
Thanks for your response @akellbl4, your assessment is fair. I'll close this issue for now.
