### ISSUE TITLE
last-comments widget erroneously escapes HTML characters in title

### ISSUE THREAD

**Issue by irgendwr** [umputun/remark42#1369]
The latest-comments widget erroneously escapes HTML characters in the page title.

E.g. instead of `lorem "ipsum"`, it shows `lorem &#34;ipsum&#34;`

**Version:** `v1.9.0-0521c702-20220124T12:35:27`

**Comment by umputun** [comment]
i think, this is a dup, see #1341 and #415 and #1293

this change on master, not tagged yet

**Comment by irgendwr** [comment]
Thanks, both for the quick response and this great comment engine! I will close if for now and re-test once the next version is released.

By the way: Is there an ETA for new releases? It would be nice to get the latest changes from the master branch.

**Comment by umputun** [comment]
> By the way: Is there an ETA for new releases? It would be nice to get the latest changes from the master branch.

yep, planned to do it today/tomorrow

**Comment by paskal** [comment]
@irgendwr can you please verify that error you mentioned is not happening in v1.10.1?

**Comment by irgendwr** [comment]
Yes, this issue is fixed, thanks :)
