### ISSUE TITLE
Broken links to icons of authentication services

### ISSUE THREAD

**Issue by Ivan-Chupin** [umputun/remark42#1370]
When using Remark42 version 1.10.0 in a configuration without a subdomain, links to icons of authentication services are broken. Rollback to version 1.9.0 fixes the bug.
![remark42-broken-urls](https://user-images.githubusercontent.com/83099323/170953211-62b379ce-f8b0-4442-a79a-e141eec54c50.png)

**Comment by umputun** [comment]
@paskal @akellbl4 - any clue?

**Comment by saosangmo** [comment]
I have just installed RM42. I think @Ivan-Chupin has not configured nginx rewrite for path /web/. He may installed with an old document.

I have checked on his own site: _https://smarthdd.com/. Everything seem works well.

**Comment by Ivan-Chupin** [comment]
Nginx is configured correctly. The [problem with /web/](https://github.com/umputun/remark42/issues/995) when installing Remark42 without a subdomain is known, but unfortunately not resolved. The site works well because I rolled back Remark42 to version 1.9.0

**Comment by akellbl4** [comment]
I see possible problem. I'll try to fix it.

**Comment by akellbl4** [comment]
@Ivan-Chupin could you please test it on your instance and confirm that this issue was fixed for you?

**Comment by Ivan-Chupin** [comment]
Where can I download the corrected executable file?

**Comment by umputun** [comment]
master builds don't produce binary, but docker images, i.e. ghcr.io/umputun/remark42:master

_if you really need a binary version let me know what architecture, and I'll build and attach it to this ticker_

**Comment by Ivan-Chupin** [comment]
linux-amd64

**Comment by umputun** [comment]
[remark42.linux-amd64.tar.gz](https://github.com/umputun/remark42/files/8841921/remark42.linux-amd64.tar.gz)

fyi: you can always build it by running "make release"

**Comment by Ivan-Chupin** [comment]
Checked out the new version. The error has been fixed. Thank you.
