### ISSUE TITLE
Need more help for installation with Binary

### ISSUE THREAD

**Issue by saosangmo** [umputun/remark42#1371]
hello,

Because I do not want to use Docker, could you please write more details for installing with Binary on Ubuntu 20.x?

Thanks for your software!

-Dzung Do

**Comment by Ivan-Chupin** [comment]
https://blog.lasall.dev/post/hugo-and-comments-with-remark42/

**Comment by saosangmo** [comment]
Thank @Ivan-Chupin so much.
