### ISSUE TITLE
Broken links in remark.css when using Remark42 without subdomain.

### ISSUE THREAD

**Issue by Ivan-Chupin** [umputun/remark42#1380]
![remark42-broken-urls-2](https://user-images.githubusercontent.com/83099323/172132459-ff6315bd-e028-417b-b181-108f79eb5dbe.png)

**Comment by Ivan-Chupin** [comment]
I rolled back from version 1.10.0 to 1.9.0

**Comment by akellbl4** [comment]
@Ivan-Chupin thanks for reporting the issue.
I'll check other resources as well
