### ISSUE TITLE
Provide frontend API SDK

### ISSUE THREAD

**Issue by vitonsky** [umputun/remark42#1382]
Hi, your comments system looks great, i like how fast it may be configure and deploy.

However, the frontend side are looks really bad. I suggest to introduce a SDK which allow to clients make own implementations of comments component.

I know about https://remark42.com/docs/contributing/api/ page and it's really good, but i'm not ready to support wrappers over API of comments engine. Your product is really good, you give us a way to fast deploy self hosted comments, as user i expect a tools to as fast implement my own component which can use all powerful of remark42 as i can deploy the backend.

**Comment by umputun** [comment]
pls use discussions for this type of requests/ideas
