### ISSUE TITLE
Customize placeholder string from config

### ISSUE THREAD

**Issue by mythsman** [umputun/remark42#1471]
I think it is a good idea to customize the placeholder in the comment box , like changing 'You comment here' to something different which i can easily configure ?

**Comment by paskal** [comment]
I think the easiest way for you is to create a custom [translation file](https://github.com/umputun/remark42/blob/d9764c2/frontend/apps/remark42/app/locales/en.json) and use it instead of the one you have originally: `commentForm.input-placeholder` line is responsible for that prompt.
