### ISSUE TITLE
Office365 SMTP

### ISSUE THREAD

**Issue by Threnklyn** [umputun/remark42#1472]
Hi there,

I want to use Office365 to send mails
https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

but sadly I get the following error:
```
[WARN]  {notify/notify.go:168 notify.(*Service).do.func1} failed to send to email: with username 'no-reply@example.com' at server smtp.office365.com:587 with StartTLS, 1 error occurred:
Aug 26 07:40:29  remark[37761]:         * problem sending admin email notification to "t.klyn@example.com": failed to auth to smtp smtp.office365.com:587, 504 5.7.4 Unrecognized authentication type [FR0P281CA0125.DEUP281.PROD.OUTLOOK.COM]
```

my environment variables:
```
"NOTIFY_EMAIL_FROM=no-reply@example.com"
"SMTP_HOST=smtp.office365.com"
"SMTP_PORT=587"
"SMTP_USERNAME=no-reply@example.com"
"SMTP_PASSWORD=************"
"SMTP_STARTTLS=true"
"SMTP_TLS=false"
```

**Comment by Threnklyn** [comment]
looks like Microsoft does not allow [Plain Auth anymore](https://support.microsoft.com/en-us/office/outlook-com-no-longer-supports-auth-plain-authentication-07f7d5e9-1697-465f-84d2-4513d4ff0145), which is used in [go-pkgz/email/email.go](https://github.com/go-pkgz/email/blob/master/email.go#L123).
The go `net/smtp` package does not support the login mechanism `LOGIN`.
Here is an example I found for login auth using `net/smtp` https://gist.github.com/homme/22b457eb054a07e7b2fb

Shall I post an issue in https://github.com/go-pkgz/email/issues too?

**Comment by paskal** [comment]
Please post it there, and feel free to send the PR if you're interested in preparing one. Thank you!
