### ISSUE TITLE
Cannot delete/edit comment with replies even if they're removed

### ISSUE THREAD

**Issue by daniloarcidiacono** [umputun/remark42#1481]
Steps to reproduce:

1. Login as a non-administrator;
2. Post one comment "a";
3. Reply to that comment with another comment "b";
4. Delete the "b" comment;
5. Delete the "a" comment;

An error occurs on the last step: "parent comment with reply can't be edited"... but this shouldn't be thrown because the child comment "b" is no longer visible. Furthermore, the "Edit" action is not restored on the parent comment once the child comment has been deleted.

No errors are thrown if the user is an administrator instead, and also the "Edit" is restored after refreshing the page. 
I noticed that the "Delete" button calls two different APIs depending if the user is an administrator or not:

- **Administrator**:  DELETE /admin/comment/{id}
- **Non administrator**: PUT /comment/{id}

The problem seems related to the `repliesCache` used by `HasReplies()` method that is not updated when the child comment is removed.

**Comment by paskal** [comment]
Thanks for the good bug reports!
