### ISSUE TITLE
User is always blocked permanently

### ISSUE THREAD

**Issue by daniloarcidiacono** [umputun/remark42#1493]
When blocking a user the TTL information is not passed to the backend.

In `api.ts` only the "permanently" option is handled, however passing `undefined` also results in a permanent block.

```ts
export const blockUser = (
  id: User['id'],
  ttl: BlockTTL
): Promise<{
  block: boolean;
  site_id: string;
  user_id: string;
}> => adminFetcher.put(`/user/${id}`, { block: 1, ttl: ttl === 'permanently' ? ttl : undefined });
```

**Comment by akellbl4** [comment]
It was fixed and will be delivered in the next release.
