### ISSUE TITLE
Key() method invoked with wrong siteID

### ISSUE THREAD

**Issue by daniloarcidiacono** [umputun/remark42#1499]
Hello,
I noticed that in some places the `Key()` method of admin `Store` is called with an incorrect site id, precisely:

https://github.com/umputun/remark42/blob/master/backend/app/store/service/service.go#L986

```go
func (s *DataStore) getSecret(siteID string) (secret string, err error) {
	if secret, err = s.AdminStore.Key("any"); err != nil {
```

https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L1110

```go
SecretReader: token.SecretFunc(func(aud string) (string, error) { // get secret per site
	return admns.Key("")
}),
```

This is not a problem for the "shared" implementation since it supports only one set of data for all sites, however that's not the case for my custom RPC backend... moreover, the fix seems trivial in both cases:

https://github.com/umputun/remark42/blob/master/backend/app/store/service/service.go#L986

```go
func (s *DataStore) getSecret(siteID string) (secret string, err error) {
	if secret, err = s.AdminStore.Key(siteID); err != nil {
```

https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L1110

```go
SecretReader: token.SecretFunc(func(aud string) (string, error) { // get secret per site
        // go-pkgz/auth.go says:
        //       "SecretReader   token.Secret        // reader returns secret for given site id (aud), required"
	return admns.Key(aud)
}),
```

Thanks

**Comment by umputun** [comment]
This is not a bug but rather a documented limitation with a comment describing this behavior.

```
// get secret for given siteID
// Note: secret shared across sites, but some sites can be disabled.
func (s *DataStore) getSecret(siteID string) (secret string, err error) {
```

I do agree with the proposal. Looks like it won't break StaticStore.Key as it ignores aud anyway

This should be made clear somehow in comments what passed key won't affect the default store
