### ISSUE TITLE
Wrong siteId "ignore" used when logging in

### ISSUE THREAD

**Issue by daniloarcidiacono** [umputun/remark42#1519]
Hello,
as a follow-up of https://github.com/umputun/remark42/issues/1499, now the login process fails because in go-pkgz/auth library the audience `ignore` is passed (which in turn is used to lookup the site key):

![image](https://user-images.githubusercontent.com/17272323/197341095-a2cdc604-b9dc-4bb6-a91f-16715efaee0f.png)

It seems that enabling `AudSecrets` (in `backend/app/cmd/server.go`, method `getAuthenticator`) solves the problem, but I'm not sure it's a good fix since there's a warning in `go-pkgz/auth/token/jwt.go`:

![image](https://user-images.githubusercontent.com/17272323/197341187-2a9083e8-2828-4c1d-b6d1-401d5397dcf6.png)

Thanks

**Comment by umputun** [comment]
The warning means that this step avoids token validation and should be used carefully. It doesn't mean "shouldn't be ever used." This is precisely the use case for which this aud method exists in the first place - in order to get a secret for a given aud the token has to be parsed, but without a secret, we can't verify parsing.

The bottom line - it is fine to do, this is how it supposed to work

**Comment by daniloarcidiacono** [comment]
Sorry, but how this problem has been fixed? Enabling `AudSecrets` requires to change the source code.

Thanks

**Comment by paskal** [comment]
Apologies, I misunderstood your message and Umputun's answer. I'll add that option to Remark42 CLI options.

**Comment by paskal** [comment]
@daniloarcidiacono, we'll fix it shortly, likely not in the next minor release but in the next bugfix version (`v1.12.0`). Can you please verify that that's the only issue you know of in the current code base?

**Comment by daniloarcidiacono** [comment]
Hi @paskal, that's the only issue I know of at the moment.

I also noticed some issues with cropped iframe height but that was already been notified on https://github.com/umputun/remark42/issues/1521.
