### ISSUE TITLE
pnpm start:app does not work (on windows?)

### ISSUE THREAD

**Issue by realB12** [umputun/remark42#1530]
On my local **Windows10** developer-workstation, executing the command

       ` pnpm start:app` 
        
for launching the FrontenServer (as documented in the Remark42.com Frontend Online Manual on https://remark42.com/docs/contributing/frontend/) from the `apps/remark42/` project folder currently comes back with an **error, that the "`app`" folder is not found.** 

Manually switching into the `/app` folder and running `pnpm start` from there however runs fine.   
  
This is not really an issue (for me) - just curious whether I might have a local (configuration) issue or whether this is normal behavior on a Windows10 machine.

**Comment by akellbl4** [comment]
@realB12 as it turns out we needed to update docs ;)
