### ISSUE TITLE
how i can fix this? maybe about css?

### ISSUE THREAD

**Issue by Nabioka** [umputun/remark42#1535]
![image](https://user-images.githubusercontent.com/118914715/203579576-8808d505-5813-45dd-825e-9a62d08fa128.png)

**Comment by paskal** [comment]
Can you please share an URL of the page in question?

**Comment by Nabioka** [comment]
> Can you please share an URL of the page in question?

https://comment.kaichan.co/web/

**Comment by Nabioka** [comment]
now i can fix this. i switch to install master and it's work thx

**Comment by akellbl4** [comment]
Close as solved.
