### ISSUE TITLE
Feature Request: Add version to global `REMARK42` object

### ISSUE THREAD

**Issue by JeppeKlitgaard** [umputun/remark42#1536]
I can't seem to find a way to read the version of REMARK42 used from the front end. Would it be possible to add a version attribute to the global `REMARK42` object? Perhaps there is some other way that I have missed.

**Comment by akellbl4** [comment]
Hey @JeppeKlitgaard,
It's not hard to do, but maybe you have some usecase for it?
If you're just wanna check version installed, you can check headers in network requests to the backend and see current version there.

**Comment by JeppeKlitgaard** [comment]
My use-case was primarily to check what version of `remark42` my site was actually running to verify that the docker image had indeed been updated. I tried poking around a bit and wasn't able to find the version anywhere, but I didn't think to look in the headers. That would be enough for me, though I think having access to it on the frontend directly could make sense. For example, a frontend script might to implement something based on what version of `remark42` is running?

Feel free to close this – the header trick is enough for my current use-case.

Thank you so much!
