### ISSUE TITLE
Height iframe.html

### ISSUE THREAD

**Issue by Ivan-Chupin** [umputun/remark42#1546]
In the latest update of Remark42 version 1.11.1, I see an error displaying comments. The height is calculated incorrectly. This error occurs only if there is a pinned comment.

**New version:**

![cut](https://user-images.githubusercontent.com/83099323/205497328-1a2756b3-71c3-40b3-8302-9f515fe33129.png)

**Old version:**

![no-cut](https://user-images.githubusercontent.com/83099323/205497338-de7e45bb-4d15-4660-962f-75146a52254e.png)

**Comment by akellbl4** [comment]
@Ivan-Chupin could you please check if it fixed in `master`?

**Comment by Ridys** [comment]
Same problem, after installing version 1.11.1 from scratch. 
Built a master ([8d95baa](https://github.com/umputun/remark42/commit/8d95baa70f0a9cc1fa33b855e6f54f405729642c)) with Docker, didn't help.
I avoided this problem by installing version 1.11.0.
![image](https://user-images.githubusercontent.com/17117574/205779504-a9cc0b37-4f24-4cf0-a8a1-e765fec616e8.png)

**Comment by akellbl4** [comment]
@Ridys do you have this problem on https://remark42.com/demo/? if yes, what browser do you use?

**Comment by akellbl4** [comment]
@Ridys I can confirm we are using built system from master, so masted shouldn't have this problem.
Please check if you have correct build.

**Comment by Ivan-Chupin** [comment]
> @Ivan-Chupin could you please check if it fixed in `master`?

I apologize for the long answer. I have no way to compile the master version. Can you provide me with a link to download the master compiled version of remark42.linux-amd64.tar.gz?

**Comment by paskal** [comment]
Here is it: [remark42.linux-amd64.tar.gz](https://github.com/umputun/remark42/files/10202241/remark42.linux-amd64.tar.gz)

**Comment by Ivan-Chupin** [comment]
The master version works great. Thank you.
