### ISSUE TITLE
Incorrect iframe height when `no_footer` enabled

### ISSUE THREAD

**Issue by domw95** [umputun/remark42#1552]
When displaying the embed widget, the bottom of the widget up to the "reply" text on the bottom comment is cut off, I am guessing because the iframe height is too small. Manually setting the iframe height fixes the issue.

Tested on firefox desktop/mobile and chrome desktop.

Tried different versions (docker), and breaking change occurs between v1.11.0 and 1.11.1

![Screenshot from 2022-12-14 02-48-04](https://user-images.githubusercontent.com/63186722/207493594-590a1945-8d38-45bc-bcc6-6cce4239bc52.png)

**Comment by Ivan-Chupin** [comment]
Does version 1.11.2 have the same effect?

**Comment by domw95** [comment]
Yes it does, sorry I didn't make that clear

**Comment by akellbl4** [comment]
@domw95 could you please provide a link to a page with this problem?

**Comment by domw95** [comment]
Example with just the comments on the page here [https://test.domwil.co.uk/comments.html](https://test.domwil.co.uk/comments.html), server set to v1.11.2

**Comment by akellbl4** [comment]
@domw95 thanks, it helped. I figured out the problem, we didn't account for `no_footer` option. I'm gonna work on a fix.

**Comment by domw95** [comment]
I don't think that is the issue, it also occurs when no_footer is set to false

**Comment by akellbl4** [comment]
@domw95 here is example on your instance with footer https://remark.domwil.co.uk/web/

**Comment by paskal** [comment]
Fixed with #1569, will be released shortly as a bugfix version (`v1.11.3`).
