### ISSUE TITLE
Still can not auth becouse of SameSite

### ISSUE THREAD

**Issue by vadamk** [umputun/remark42#1580]
Still can not auth with SameSite=None
I've setted up `AUTH_SAME_SITE=none`, but it still doesn't work for me

If SameSite=None is set, **the cookie "Secure" attribute must also be set** (or the cookie will be blocked).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#none

**Comment by paskal** [comment]
Resolving in favour of #784. Answer from there:

> Secure would be set if your Remark42URL starts with `https://`. Please verify if it works for you when you change the URL to start with `https://`, and please feel free to update the documentation in place you would expect to see that information.
