### ISSUE TITLE
th language not working

### ISSUE THREAD

**Issue by Nabioka** [umputun/remark42#1605]
![image](https://user-images.githubusercontent.com/118914715/223076204-febad9b5-f577-44c5-b302-3d4d08eb4657.png)
i saw on supported locales it's have thai language but it's not working. and i looking around and i found "frontend/apps/remark42/app/utils/loadLocale.ts" didn't have locale th. maybe that's the problem

**Comment by paskal** [comment]
After the merge of #1608, the `master` version of the Remark42 Docker image would work without any changes from your side.
