### ISSUE TITLE
Long one-line `code` block causes content to be hidden

### ISSUE THREAD

**Issue by cowsay1** [umputun/remark42#1629]
reproduce in https://remark42.com/demo/
![image](https://user-images.githubusercontent.com/60675651/234499881-5e76b841-6d1c-4b0c-8a32-2c1adf8d4dc9.png)

I think it can be fixed with css white-space:pre-line or pre-wrap, not sure what is better:

![image](https://user-images.githubusercontent.com/60675651/234500353-282dd034-9ad8-4176-9578-d89a4d44587b.png)

**Comment by paskal** [comment]
I've checked, and it's indeed a problem: that test results in a long line of text which is not visible and not scrollable.
@Jaskon @goooseman, maybe one of you can tackle this one?
