### ISSUE TITLE
Sort By section doesn't switch to Dark theme

### ISSUE THREAD

**Issue by RajuKottedi** [umputun/remark42#1662]
The sort-by section doesn't change to a Dark theme. Please find the screen image.

![image](https://github.com/umputun/remark42/assets/22296335/eb3d9fc8-80dc-4b26-9ad2-11cda18ae71e)

**Comment by umputun** [comment]
works for me

safari:

![image](https://github.com/umputun/remark42/assets/535880/4f39f704-ee99-463f-a745-df064ee8a694)

chrome:

![image](https://github.com/umputun/remark42/assets/535880/48998c64-7778-4559-8049-41f3cb90a28f)

**Comment by paskal** [comment]
It's tied to the system theme, I believe: in @umputun case, it will stay dark after switching to the light theme and even refreshing the page. At least on mac it works like that for me.

**Comment by umputun** [comment]
> It's tied to the system theme, I believe: in @umputun case, it will stay dark after switching to the light theme and even refreshing the page. At least on mac it works like that for me.

yep, confirmed

**Comment by RajuKottedi** [comment]
Could you please look into it?

**Comment by akellbl4** [comment]
@RajuKottedi hey, thanks for reporting the issue. This problem can be resolved by doing this https://github.com/umputun/remark42/issues/1430. I close this one, so you can track linked issue.

**Comment by OnkelTem** [comment]
While we're waiting for a big solution, is there a workaround?

![image](https://github.com/umputun/remark42/assets/114060/117924c0-da29-4dea-8a50-275b8630d94c)
