### ISSUE TITLE
Double-quote characters in comments show as guillemets in output

### ISSUE THREAD

**Issue by davmac314** [umputun/remark42#1666]
When double-quote characters are entered in a comment "like this", they appear in the output as guillemets  «like this».

This is presumably intended, but it is not appropriate for some languages, and doesn't seem to be configurable.

**Comment by paskal** [comment]
We use [blackfriday](https://github.com/russross/blackfriday) `SmartypantsAngledQuotes` [option](https://github.com/umputun/remark42/blob/c9b6f9272f5de893cdec49acdb04ffc9d610dc64/backend/app/store/formatter.go#L128-L130) is responsible for it.

With this option `"quoted" text` translates to `«quoted» text` (current behaviour), without it to `“quoted” text`. Would be the second option be more appropriate? I think I can add it to the frontend so it would be possible to change it per-site based on your preferences and site language.

**Comment by davmac314** [comment]
> Would be the second option be more appropriate?

Yes, thanks!

**Comment by paskal** [comment]
For reference, I found [that](https://op.europa.eu/en/web/eu-vocabularies/formex/physical-specifications/character-encoding/use-of-quotation-marks-in-the-different-languages) European documentation which states that in most listed European Union official languages `„...“` is the correct form, and it's not available in the parser we use at all. I'll think about how to implement this change and how to do it without complicating the code a bit later. It's a very minor piece of functionality, and it feels weird to include it into the backend, maybe we should add replacement rules to the frontend so that all variants would be supported.

**Comment by davmac314** [comment]
It would probably be best to just leave quotes alone, in my opinion. I.e. people can type whatever sort of quotes they like, and how they enter it is how it should be displayed.

**Comment by paskal** [comment]
I've addressed this in #1700. Please verify if that would work for you.

**Comment by davmac314** [comment]
Looks like it should - I'll try to test on the weekend. Thanks!

**Comment by davmac314** [comment]
I'm afraid it doesn't seem to work. I have built your branch and am running with `--disable-fancy-html-formatting`:

```
root@bmdragon:~# ps -Af|grep remark42
remark42 2218378 2218377  0 06:27 pts/1    00:00:00 -bash
remark42 2218749       1  0 06:52 ?        00:00:00 /bin/sh /home/remark42/run-remark.sh
remark42 2218750 2218749  0 06:52 ?        00:00:01 ./remark42.linux-amd64 server --url=https://davmac.org/remark42/ --secret=XXXXXXXX --site=davmac.org --address=127.0.0.1 --port=8001 --smtp.host=localhost --smtp.port=25 --auth.github.cid=XXXXXXXXXXXXX --auth.github.csec=XXXXXXXXXXXXXX --auth.email.enable --auth.email.from=remark42@davmac.org --auth.anon --notify.admins=email --admin.shared.id=XXXXXXXXXXX --admin.shared.email=davmac@davmac.org --disable-fancy-html-formatting
```

But when I make a  comment with "quotes" it still comes out as guillemets. See this page: https://davmac.org/blog/escape-from-system-d-vi.html

Am I doing something wrong?

**Comment by paskal** [comment]
You did everything right, I missed passing the parameter I created in three places. Now it should work as expected, please take a look once more.

**Comment by davmac314** [comment]
Working! Thanks again.
