### ISSUE TITLE
Missing binary version for v1.12.1

### ISSUE THREAD

**Issue by damienalexandre** [umputun/remark42#1684]
While Docker images are built properly (https://github.com/umputun/remark42/pkgs/container/remark42/120570470?tag=v1.12.1), the release binary is missing in https://github.com/umputun/remark42/releases/tag/v1.12.1 :grimacing: 

The documentation links to https://github.com/umputun/remark42/releases and ask "download archive for the stable release".

Thanks :pray:

**Comment by umputun** [comment]
fixed

**Comment by damienalexandre** [comment]
Awesome, thanks a lot!
