### ISSUE TITLE
Commento import results in incorrect URL locator

### ISSUE THREAD

**Issue by RealOrangeOne** [umputun/remark42#1697]
When importing from Commento, the import [uses](https://github.com/umputun/remark42/blob/master/backend/app/migrator/commento.go#L116) just the "Path" as the URL locator, rather than the full domain. This results in comments which can't be found.

Instead, a combination of `Domain` and `Path` should be used, as this seems to be how commento [stores things in the DB](https://gitlab.com/commento/commento/-/blob/master/api/comment_list.go?ref_type=heads#L27-L28) anyway.

See #1696 for an example export to reproduce.

**Comment by paskal** [comment]
Exception from the example JSON you provided:

```json
    {
      "commentHex": "e7a2ef4b4aa1414a7ee65a989889aaecd9d5e7e3bca598ea7a967b4dbcaa8e11",
      "domain": "example.com",
      "url": "https://example.com/example",
      "commenterHex": "018407e4b12b35f43b1d804d82607b341bef80c4325dd047d93f2cbb439cff85",
      "markdown": "",
      "html": "",
      "parentHex": "root",
      "score": 0,
      "state": "approved",
      "creationDate": "2022-10-25T07:25:46.807555Z",
      "direction": 0,
      "deleted": false
    }
```
Should it read `"url": "/example",` instead? Could you please verify?

**Comment by RealOrangeOne** [comment]
@paskal ah, woops, that was a file I'd previously updated to correct. Yes, the `url` is just the path in the raw export:

![image](https://github.com/umputun/remark42/assets/6527489/f0cde855-83dd-470b-9f6a-ed1ea93939fd)
