### ISSUE TITLE
The "Delete" button remains visible in the UI even after the editing period has expired.

### ISSUE THREAD

**Issue by yakimka** [umputun/remark42#1737]
Steps to reproduce:

1. Write a comment in remark42.
2. Wait until the editing time is over.
3. Click the "Delete" button.
4. Nothing happens (as a user, I'm confused because there are no pop-ups or error messages).

Expected result:

- The "Delete" button should not be visible in the UI after the editing period has expired.
- OR perhaps the editing period applies only to editing, and message deletion is always available.
- OR if deletion is not allowed and the button is available in UI, the user should be informed through a pop-up warning.

<img width="809" alt="зображення" src="https://github.com/umputun/remark42/assets/28621349/41ef7ecd-c32a-42d7-886c-097ede90a56e">

**Comment by paskal** [comment]
@akellbl4, the problem was introduced in the 58b0841360c742647243346c5faa183908e082ed. I found this out using `git bisect`.

**Comment by paskal** [comment]
> The "Delete" button should not be visible in the UI after the editing period has expired.

That option is the right one and was in place before the commit where it was broken. It will be fixed in the next release shortly.
