### ISSUE TITLE
Login with auth0?

### ISSUE THREAD

**Issue by woeterman94** [umputun/remark42#1746]
Would it be possible to support logging in with Auth0? (SSO) ?

**Comment by paskal** [comment]
Closing in favour of #1543, please see discussion there.

**Comment by woeterman94** [comment]
You closed this one as completed but I see that it isn't currently supported?

**Comment by paskal** [comment]
#1543 is not closed but is an active discussion of how it's achievable: someone has to add its support into https://github.com/go-pkgz/auth and no one done it yet. Please vote up the original post in that discussion.

Auth0 is a commercial product and I will unlikely pick that task up unless someone would convince me that it would make sense for ordinary users. The biggest selling point for Remark42 is SSO support which make sense only for businesses, and if someone needs it I presume they should be okay with paying their own developer for implementing Auth0 support in Remark42 to cover their need.

If I would run Remark42 as a service to sell someone, it would be a different talk as it would be a selling point for me to support it.
