### ISSUE TITLE
Sign in with Apple breaks

### ISSUE THREAD

**Issue by tomy0000000** [umputun/remark42#1789]
After configuring all the required variables, Sign in with Apple still fails. The behavior is identical to the demo site, so I suspect this is not because of misconfiguration.

```log
remark42  | 2024/06/25 00:44:58.852 [ERROR] prepare login url for [apple] provider failed
remark42  | 2024/06/25 00:44:58.852 [INFO]  prepare login url for [apple] provider failed - response_mode must be form_post if scope is not empty - 500 - ***.***.***.*** - /auth/apple/login?from=https://***.***.***/web/iframe.html?selfClose&site=blog [caused by auth/provider/apple.go:282 provider.(*AppleHandler).LoginHandler]
remark42  | 2024/06/25 00:44:58.852 [INFO]  GET - /auth/apple/login?from=https://***.***.***/web/iframe.html?selfClose&site=blog - ***.***.*** - 9865eb6e1655 - 500 (58) - 206.795µs
remark42  | 2024/06/25 00:44:58.852 [ERROR] prepare login url for [apple] provider failed
```

After some tracing, I noticed this line, which was added recently: 

https://github.com/umputun/remark42/blob/c04705947a2a611aef51df82fb20d4cbc6fcefb5/backend/app/cmd/server.go#L911

It used to be `form_post` but somehow got changed to `query` without any document or commit message.

**Comment by paskal** [comment]
Does removing it fix the situation? I have no active Apple subscription to check it.

**Comment by tomy0000000** [comment]
See #1806
