### ISSUE TITLE
Encounter proplem in logging out

### ISSUE THREAD

**Issue by here-tunan** [umputun/remark42#1812]
Hi, when I tried to log out, I encountered a problem. Could you help me to solve it?
![image](https://github.com/user-attachments/assets/e6d4bef1-d740-4418-a2ee-37f9ceda1f47)
Even though the HTTP request was fine, the control showed an error and I couldn't log out.
![image](https://github.com/user-attachments/assets/b8f68849-5deb-4610-8722-a90872f2699b)

This is my front-end code below:
[github-link](https://github.com/here-tunan/tunan-blog/blob/main/ui/app/blog/%5Bslug%5D/comment.tsx)

I'm using the latest version of remark42.

You can go to https://remark42.tunan.fun/web/ to reproduce this issue.

**Comment by paskal** [comment]
I can reproduce at https://demo.remark42.com/web/, so master is affected. I'll find out where it was introduced and fix it.

**Comment by paskal** [comment]
I found that the problem commit is a9b439602b094a694c30d4de47056f3fa2ed9734 using `git bisect`.

**Comment by here-tunan** [comment]
Thanks for your help and all of your work! You are the goat! I appreciate it!
