### ISSUE TITLE
FreeBSD asset

### ISSUE THREAD

**Issue by AmritasyaPutra** [umputun/remark42#1818]
I noticed that until recently all release had 9 assets that included Linux and FreeBSD binary but they are not there in the most recent 1.13.1 release.

**Comment by paskal** [comment]
@umputun I guess you need to do the push manually:
1.13.0
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/3710d786-1a28-4477-9a4e-70a7b4e7f0e0">
vs 1.13.1
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/ea419dde-d690-40c9-84e5-082e39e65aca">

**Comment by paskal** [comment]
It's fixed in [v1.14.0](https://github.com/umputun/remark42/releases/tag/v1.14.0), resolving.
