### ISSUE TITLE
"no auth providers defined" when discord is clearly defined

### ISSUE THREAD

**Issue by chilledtonic** [umputun/remark42#1880]
I have Discord defined as outlined in the docs in my docker-compose file:
```
      - AUTH_DISCORD_CID=1xxxxxxx
      - AUTH_DISCORD_CSEC=Fs-xxxxxxx
```

In spite of this, Discord doesn't appear as an option for user login, saying:

```
2024/12/29 19:15:46.542 [WARN]  {cmd/server.go:1025 cmd.(*ServerCommand).addAuthProviders} no auth providers defined

2024/12/29 19:15:57.738 [DEBUG] {middleware/auth.go:75 middleware.(*Authenticator).Auth.(*Authenticator).auth.func1} auth failed, can't get token: token cookie was not presented: http: named cookie not present
```

What am I missing? Let me know any more information I can provide. Thanks.

**Comment by umputun** [comment]
what version do you run? discord support is a relatively new feature, added in the latest 1.14.

**Comment by chilledtonic** [comment]
I was running `latest`, but to check for certain I just pinned my container to `umputun/remark42:v1.14.0`

I haven't managed to test every provider, but Github is working normally.

**Comment by chilledtonic** [comment]
One more update: as a test, I switched to `master`, which does work normally. So at least we have a window to figure out where the issue lies. Even with the logs as debug, I don't get much information...

**Comment by chilledtonic** [comment]
![Screenshot 2024-12-29 at 18-52-30 Authorization Remark42](https://github.com/user-attachments/assets/30b040b4-e93f-4124-86e9-1e1e2161c1df)

Presumably documentation should be updated to note this?

**Comment by umputun** [comment]
Yeah, the docs are too optimistic in this case. Eventually, we will release the next version. 

@paskal - what do we do in such cases with the docs? Is there any standard way to indicate "master only for now"?

**Comment by amosjyng** [comment]
I ran into this as well. Any ideas on when the next release will happen? :)

**Comment by paskal** [comment]
There is no "master only" documentation, we're not supposed to have such a long release cycle:) Let me do some backend changes shortly, and we'll release the new version. Apologies for taking that much time for getting back on this one.
