### ISSUE TITLE
Looks like link to comment's anchor doesn't work

### ISSUE THREAD

**Issue by shalugin** [umputun/remark42#19]
Добавил комментарий на странице https://remark42.com/demo/

Щёлкаю на ссылку (где дата и время) - 
https://remark42.com/demo/#remark42__comment-6138aa59-eef7-4630-82f8-5d501bbf1d7b

В FF 60 комментарий не подсвечивается, и страница не скролится к якорю.

**Comment by igoradamenko** [comment]
I think it's because of slow loading of images and other assets, which affects a height of a page, and it makes jumping incorrect.

I will try to fix it.

**Comment by igoradamenko** [comment]
Fixed.

**Comment by L11R** [comment]
@igoradamenko @umputun It's seems like I see regression.

In my case it just scrolls to the comment's block, not to the exact comment:
https://krasovs.ky/2021/04/26/checkpoint-snx-adventure.html#remark42__comment-f7b0b2bf-b246-4d87-acb5-67a6fc095db3

**Comment by umputun** [comment]
ping @akellbl4

**Comment by akellbl4** [comment]
They work but badly. We already have a task for the problem #575
