### ISSUE TITLE
Message length restriction

### ISSUE THREAD

**Issue by Labutin** [umputun/remark42#212]
I tried to write a long message. The interface shows that I can type 10 more symbols.
<img width="787" alt="message" src="https://user-images.githubusercontent.com/6604871/47477314-812ec080-d7d9-11e8-9676-04177e8742c5.png">
But I can't continue my message.

**Comment by Labutin** [comment]
I have tried radio-t right now. Issue still presents.

**Comment by umputun** [comment]
I have found an old one, probably about the same issue https://github.com/umputun/remark/issues/3#issuecomment-392270278

**Comment by Labutin** [comment]
You are right. In Chrome all works fine. Problem in Safari :(
Didn't check Firefox.

**Comment by Reeywhaar** [comment]
Duplicate of https://github.com/umputun/remark/issues/3
