### ISSUE TITLE
Document integration procedure for popular blogging systems

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#27]
Probably this can be done in the wiki. I think we should provide simple instructions on how to embed it into Hugo, Ghost, and other popular blogging engines.

**Comment by Menelion** [comment]
Am I right that it always be self-hosted, i.e., no public server like disqus.com, for example? I'm asking because I have a Wordpress plugin in mind :).

**Comment by umputun** [comment]
@Menelion I have plans for hosted version someday, but no ETA

**Comment by umputun** [comment]
@paskal - with our new documentation site those manuals may have a good place to live.

**Comment by paskal** [comment]
I'll do step-by-step documentation for a platform or two and will move [existing wiki documents ](https://github.com/umputun/remark42/wiki) to the new documentation.

**Comment by paskal** [comment]
Here is [step-by-step documentation for installing Remark42 when you don't have a server](https://terrty.net/2022/self-hosted-comments-remark42/). What is left is moving over the wiki documents.

**Comment by paskal** [comment]
Wiki documents are already available on https://remark42.com/docs/getting-started/installation/, resolving.
