### ISSUE TITLE
Allow LaTeX style formulae

### ISSUE THREAD

**Issue by Shchvova** [umputun/remark42#31]
Some markdown editors provide ability to embed math formulae. For example, here is screengrab of [StackEdit.io](https://stackedit.io/app#) ![](https://i.imgur.com/at8W7U3.png)

This can be of limited use in resources like Github since this is coding oriented resource, but comment engine is general purpose tool and may be used by someone who is interested in math.

Some links:
* https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference
* https://khan.github.io/KaTeX/

This may be an optional feature

**Comment by umputun** [comment]
I don't think we will add such exotic MD extension into the core but with recently added `orig` filed it should be possible to implement it on the client side as a custom UI

**Comment by Shchvova** [comment]
I will investigate how (if) current front-end implementation can be adjusted to make such customizations possible, without rebuilding whole thing.

**Comment by paskal** [comment]
I am strongly against implementing this feature for the reasons I've described in #478. As far as I see, Remark author is not very enthusiastic about adding such functionality as well and year-and-a-half investigation of issue author yielded no results.

For these reasons, I believe we could safely close this issue.
