### ISSUE TITLE
Add github style syntax highlighting.

### ISSUE THREAD

**Issue by Shchvova** [umputun/remark42#32]
For examle:

    ```java
    class Borsch {
      private static function borshch() {
        return new Borshch();
      }
    }
    ```
In github results in:

```java
class Borsch {
  private static function borshch() {
    return new Borshch();
  }
}
```

But in remark it just renders
```
class Borsch {
  private static function borshch() {
    return new Borshch();
  }
}
```

**Comment by umputun** [comment]
yeah, we know and even tried to address. The problem is this - the regular md library we use seems to set ids only for colors but doesn't provide styles. External rendering engine I have tried brings way too many dependencies and conflicted with sanitizer.

**Comment by Shchvova** [comment]
I tried to implement my change but [found out](https://github.com/umputun/remark/blob/5f6134b39094f586e5635e45f4f3dd61427a57fe/app/rest/api/rest.go#L160) that original markdown is not stored at all, and storage just contains rendered html. 

I'm not sure how editing supposed to work with such model either... Do you get to edit html after you entered markdown? If it has colors would it be HTML with all the styles and stuff. Anyway. My suggestion wouldn't work with current model, and I don't know if changing model breaks something.

**Comment by umputun** [comment]
> original markdown is not stored at all

Why is it a problem for syntax highlighting? Maybe you tried to colorize it on the client side?

> I'm not sure how editing supposed to work with such model either...

Good point, me neither. Most likely this will require storing md as well.

**Comment by Shchvova** [comment]
Yes, my whole comment was about post processing MD on client side with JS. This will allow to use custom post-processing. Basic MD rendering is done how it is now. When comments is loaded client can extend with callback and re-render the comment.
Example would be mathjax/katex. Like include math formulas. This is not needed for casual comments, but some sites may want to allot to use math notations in comments. Another - plug in advanced code highlighting.
Suggestion: everything works as it is now: except add `orig`(`md`) field to Comment. It can be used either in "Edit" functionality or in andvaced re-rendering on client side if required. Re-rendering this way can be made user customization, not even requiring to edit anything in Remark. All can be done with parent HTML/CSS/JS.

**Comment by umputun** [comment]
@Shchvova see https://github.com/umputun/remark/issues/13 trying to decide which way to go

**Comment by umputun** [comment]
@Reeywhaar - I have checked the current state of fenced code blocks and on my side, it seems to render it correctly

<img width="734" alt="cyqox_20190701_141213 ximmm" src="https://user-images.githubusercontent.com/535880/60460862-8070e880-9c0a-11e9-8d11-18b212aed8b3.png">

However, I don't do any colorization and probably your side is the right place to make it happen. This way it will be theme-friendy for example. I guess this shouldn't be some tricky code, hopefully, you have a bunch of libraries to deal with this.

**Comment by Reeywhaar** [comment]
Yep, should be not that hard.

**Comment by paskal** [comment]
Remark backend injects code as a class for `code` tag, [example](https://remark42.com/demo/#remark42__comment-62ebfa37-1b8a-47fb-8b82-613162d6be44) for java:

```
<code class="language-java">...</code>
```
As formatting is done on the frontend side, I believe something could be done there to add colors to the code sections.

@Mavrin @Reeywhaar @akellbl4 would you be so kind as to check if that's possible and how hard would it be to implement it?

**Comment by akellbl4** [comment]
Okay, if we do it on frontend we will need to use some lib. For example https://bundlephobia.com/result?p=prismjs@1.19.0
This lib small and should be fast. But I think I need to check how fast it is.

**Comment by akellbl4** [comment]
I made a small research and realize that using JS library will make our bundle really heavy.
Because we need not just lib but an extension for each language what we need to highlight, also it will take time to parse code in runtime every time when a browser renders comment with code.

I found how it solved in Hugo https://gohugo.io/content-management/syntax-highlighting/
It parsed at a server and works like here in github comments.

@umputun @paskal what do you think about this solution?

**Comment by umputun** [comment]
I have done a quick test integrating bfchroma on the `code-colors` branch.  It produced colorized code, like this:

<img width="526" alt="q4rhz-202002-05151239-5iq2i" src="https://user-images.githubusercontent.com/535880/73884200-f6859f80-482a-11ea-9f83-ce032de89623.png">

```
<pre style="color:#f8f8f2;background-color:#272822">
<span style="color:#66d9ef">func</span> 
<span style="color:#a6e22e">main</span>(<span style="color:#a6e22e">aa</span> 
<span style="color:#66d9ef">string</span>) 
<span style="color:#66d9ef">int</span> {<span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>}
</pre>
```
I have not checked how this render affects anything else. Also, we have to make sure it can support external css and not injecting colors directly

@paskal - if you want to deal with this your are very welcome

**Comment by umputun** [comment]
I have tried `WithClasses()` and it produced the expected output:

```
<pre class="chroma">
<span class="kd">func</span> <span class="nf">main</span><span class="p">(</span>
<span class="nx">aa</span> <span class="kt">string</span><span class="p">)</span> 
<span class="kt">int</span> <span class="p">{</span><span class="k">return</span>
<span class="mi">0</span><span class="p">}</span>
</pre>
```

Probably we can get ready to use css from github.com/Depado/bfchroma or github.com/alecthomas/chroma/formatters/html. One of them should have them in already.

**Comment by akellbl4** [comment]
I think this feature should be disabled by default (because the feature it will download CSS file for code highlight) and we should load CSS only when the feature is enabled.

**Comment by umputun** [comment]
From UX point of view, I don't really see a reason to make this optional. The CSS extra is not that big I think, and it will be cached anyway.
