### ISSUE TITLE
Flapping backend tests on GitHub Actions

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#380]
I think that multiple tests might be flapping, examples:

| Test name | Failure date |
| --------- | ------------ |
| ~[Test_Main](https://github.com/umputun/remark/blob/cb60261124a7648fe2ae735e78833ff0dff54d4c/backend/app/main_test.go#L21)~ | [Oct 18](https://github.com/umputun/remark/commit/cb60261124a7648fe2ae735e78833ff0dff54d4c/checks?check_suite_id=271350649#step:5:210) |
| ~[Test_Main](https://github.com/umputun/remark/blob/f859239bdf9ac8d72b6a6bb2368764e720c822d8/backend/app/main_test.go#L21)~ | [Oct 29](https://github.com/umputun/remark/commit/f859239bdf9ac8d72b6a6bb2368764e720c822d8/checks?check_suite_id=285601644#step:5:214) |
| ~[Test_Main](https://github.com/umputun/remark/blob/c273828647e32aea21622eb0c4b7be02c3d6de19/backend/app/main_test.go#L21)~ | [Oct 31](https://github.com/umputun/remark/commit/c273828647e32aea21622eb0c4b7be02c3d6de19/checks?check_suite_id=290398749#step:5:214) |
| ~[Test_Main](https://github.com/umputun/remark/blob/c273828647e32aea21622eb0c4b7be02c3d6de19/backend/app/main_test.go#L21)~ | [Dec 30](https://github.com/paskal/remark/runs/367524352#step:5:41) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/c92dd6b7f447253245ee76a2fb625145eb534f3c/backend/app/store/image/fs_store_test.go#L245)~ | [Jul 29](https://travis-ci.org/umputun/remark/builds/564850006#L567) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/b2403a240e10185cbd91fcbb88bc6e9878ec3bd3/backend/app/store/image/fs_store_test.go#L245)~ | [Sep 15](https://travis-ci.org/umputun/remark/builds/585229004#L1459) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/b2665d21d6c88f048c80d3cc5939f9dc21cde2cd/backend/app/store/image/fs_store_test.go#L245)~ | [Oct 21](https://github.com/umputun/remark/commit/b2665d21d6c88f048c80d3cc5939f9dc21cde2cd/checks?check_suite_id=273970581#step:5:200) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/eb67ba85d1b4e196117ec6c5d3ab264a63dcd7e8/backend/app/store/image/fs_store_test.go#L245)~ | [Oct 27](https://github.com/umputun/remark/commit/eb67ba85d1b4e196117ec6c5d3ab264a63dcd7e8/checks?check_suite_id=283441884#step:5:199) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/7fd28978993bbc469323beec02a8c8fa5e0aba9d/backend/app/store/image/fs_store_test.go#L245)~ | [Nov 9](https://github.com/umputun/remark/commit/7fd28978993bbc469323beec02a8c8fa5e0aba9d/checks?check_suite_id=302916224#step:5:26) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/13486f014e710d61dea61b728ae77f17ba74bd2a/backend/app/store/image/fs_store_test.go#L245)~ | [Dec 13](https://github.com/umputun/remark/commit/13486f014e710d61dea61b728ae77f17ba74bd2a/checks?check_suite_id=356628113#step:5:28) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/a0ef7b104f7c64cafe3380bca0f8cb314f0aea43/backend/app/store/image/fs_store_test.go#L245)~ | [Dec 14](https://github.com/umputun/remark/commit/a0ef7b104f7c64cafe3380bca0f8cb314f0aea43/checks?check_suite_id=358424353#step:5:28) |
| ~[TestFsStore_Cleanup](https://github.com/umputun/remark/blob/9df2b2a9ed58c793e5463b927117ba1286b104d5/backend/app/store/image/fs_store_test.go#L245)~ | [Dec 27](https://github.com/paskal/remark/commit/9df2b2a9ed58c793e5463b927117ba1286b104d5/checks?check_suite_id=375489896#step:5:28) |
| ~[TestMigrator_Export](https://github.com/umputun/remark/blob/0a28fe1e29cc30340117f727fe95ba804ae3ab91/backend/app/rest/api/migrator_test.go#L197)~ | [Sep 20](https://travis-ci.org/umputun/remark/builds/587625018#L418) |
| ~[TestMigrator_Export](https://github.com/umputun/remark/blob/1ecfe7c6c6ab8eb389e2241bc5f497aeb729cd85/backend/app/rest/api/migrator_test.go#L193)~ | [Oct 18](https://travis-ci.org/umputun/remark/builds/599433224#L418) |
| ~[TestMigrator_Export](https://github.com/umputun/remark/blob/7bc2c55b31e719d8ca4c6ec36808a415b5e99130/backend/app/rest/api/migrator_test.go#L197)~ | [Oct 17](https://travis-ci.org/umputun/remark/builds/599337691#L419) |
| ~[TestMigrator_Export](https://github.com/umputun/remark/blob/81290dfa6ae80ed99a3df28a9ebb63d233d1f08c/backend/app/rest/api/migrator_test.go#L197)~ | [Oct 17](https://travis-ci.org/umputun/remark/builds/599346398#L419) |
| ~[TestMigrator_Export](https://github.com/umputun/remark/blob/eccc90596c53cc0da95af5ffb47c17a8d7d2cb55/backend/app/rest/api/migrator_test.go#L197)~ | [Nov 5](https://github.com/paskal/remark/commit/b9c861ea02923e95fb0c90a9b0d152c83ffe5106/checks?check_suite_id=297406017#step:5:133) |
| ~[TestMigrator_Export](https://github.com/umputun/remark/blob/eccc90596c53cc0da95af5ffb47c17a8d7d2cb55/backend/app/rest/api/migrator_test.go#L197)~ | [Nov 22](https://github.com/umputun/remark/commit/eccc90596c53cc0da95af5ffb47c17a8d7d2cb55/checks?check_suite_id=323674315#step:5:141) |
| [TestMigrator_ImportDouble](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L130) | [July 10](https://travis-ci.org/umputun/remark/builds/556690984#L663) |
| [TestMigrator_ImportDouble](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L130) | [July 22](https://travis-ci.org/umputun/remark/builds/562291597#L664) |
| [TestMigrator_ImportDouble](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L130) | [July 23](https://travis-ci.org/umputun/remark/builds/562279327#L665) |
| [TestMigrator_ImportDouble](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L130) | [July 23](https://travis-ci.org/umputun/remark/builds/562342470#L664) |
| [TestMigrator_ImportDouble](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L130) | [June 29](https://travis-ci.org/umputun/remark/builds/552216861#L663) |
| [TestMigrator_ImportDouble](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L130) | [Oct 14](https://github.com/umputun/remark/commit/ec3ef88ca5d16ab763092728f4cddbcb84c5d59f/checks?check_suite_id=264534333#step:5:326) |
| [TestMigrator_Remap](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L259) | [Oct 13](https://github.com/umputun/remark/commit/c9de09ffdd36e1994ec4a67335adfcead6a3b17b/checks?check_suite_id=263112307#step:5:309) |
| [TestMigrator_Remap](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L259) | [Oct 18](https://travis-ci.org/umputun/remark/builds/599433224#L455) |
| [TestMigrator_Remap](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L259) | [Dec 3](https://github.com/paskal/remark/commit/8132d5b8ab3f7d6fd77f3203b36d914d5845bd7a/checks?check_suite_id=338985979) |
| [TestMigrator_Remap](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L259) | [Dec 9](https://github.com/paskal/remark/commit/30c42ce36b1a06073f970b16d08be65fd3542f12/checks?check_suite_id=349750915#step:5:149) |
| [TestMigrator_Remap](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L259) | [Dec 27](https://github.com/paskal/remark/commit/d9510f9de2bb8dd07a3facdec130baf11ba0c62a/checks?check_suite_id=375477763#step:5:152) |
| ~[TestMigrator_ImportWaitExpired](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L163)~ | [July 22](https://travis-ci.org/umputun/remark/builds/562291597#L677) |
| ~[TestMigrator_ImportWaitExpired](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L163)~ | [July 23](https://travis-ci.org/umputun/remark/builds/562279327#L678) |
| ~[TestMigrator_ImportWaitExpired](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L163)~ | [July 23](https://travis-ci.org/umputun/remark/builds/562342470#L677) |
| ~[TestMigrator_ImportWaitExpired](https://github.com/umputun/remark/blob/4dc123dbe84f4f248864bcdbbd6cc2b3a4dafe11/backend/app/rest/api/migrator_test.go#L163)~ | [Oct 20](https://travis-ci.org/umputun/remark/builds/600211261#L417) |
| ~[TestRest_RunStaticSSLMode](https://github.com/umputun/remark/blob/51c64f00e56ca97d8641d0202f9336bc393e5ac8/backend/app/rest/api/rest_test.go#L102)~ | [Oct 19](https://github.com/umputun/remark/runs/266854607#step:5:523) |
| ~[TestRest_RunStaticSSLMode](https://github.com/umputun/remark/blob/4576c4cdd1c29d153bff2cf7391ce427c8b3e7ed/backend/app/rest/api/rest_test.go#L102)~ | [Dec 11](https://github.com/umputun/remark/commit/4576c4cdd1c29d153bff2cf7391ce427c8b3e7ed/checks?check_suite_id=352755386#step:5:390) |
| ~[TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/cfdcc4fffda53f0b50e6e636e70ce1fdd00f7c63/backend/app/rest/api/rest_public_test.go#L630)~ | [Oct 19](https://github.com/umputun/remark/commit/cfdcc4fffda53f0b50e6e636e70ce1fdd00f7c63/checks?check_suite_id=272475230#step:5:482) |
| ~[TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/1cbedb85b06b86c09f36d0b3625a210f6d54569c/backend/app/rest/api/rest_public_test.go#L630)~ | [Oct 19](https://github.com/umputun/remark/runs/266884368#step:5:482) |
| ~[TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/57ce795eb6d121f03abf6bf2c4e1388d1cfd6806/backend/app/rest/api/rest_public_test.go#L630)~ | [Oct 20](https://github.com/umputun/remark/commit/57ce795eb6d121f03abf6bf2c4e1388d1cfd6806/checks?check_suite_id=272667667#step:5:481) |
| ~[TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/92696669315e30e82d114bc79ad1be338e77e2d1/backend/app/rest/api/rest_public_test.go#L630)~ | [Nov 6](https://github.com/umputun/remark/commit/92696669315e30e82d114bc79ad1be338e77e2d1/checks?check_suite_id=299057132#step:5:301) |
| ~[TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/424d520e63868d77292c1363fcb03ed9ed5aca67/backend/app/rest/api/rest_public_test.go#L630)~ | [Dec 14](https://github.com/umputun/remark/commit/424d520e63868d77292c1363fcb03ed9ed5aca67/checks?check_suite_id=358716587#step:5:343) |
| ~[TestRest_InfoStreamSince](https://github.com/umputun/remark/blob/7bab10ab5741e6dc905a977ee3f18024a99d3327/backend/app/rest/api/rest_public_test.go#L672)~ | [Dec 12](https://github.com/paskal/remark/commit/6c0631d9b03e00c213bb6ccd3e00ac4845d4d25c/checks?check_suite_id=356066894#step:5:438) |
| ~[TestRest_CreateWithPictures](https://github.com/umputun/remark/blob/f8eb34633083b8d493506fe685eac4f81bd81a2d/backend/app/rest/api/rest_private_test.go#L884)~ | [Dec 11](https://github.com/paskal/remark/commit/965d86bb416350fb32ec0c30fbaef885859c600b/checks?check_suite_id=352796079) |
| ~[TestRest_CreateWithPictures](https://github.com/umputun/remark/blob/f8eb34633083b8d493506fe685eac4f81bd81a2d/backend/app/rest/api/rest_private_test.go#L884)~ | [Dec 14](https://github.com/umputun/remark/commit/f8eb34633083b8d493506fe685eac4f81bd81a2d/checks?check_suite_id=358424744#step:5:240) |
| ~[TestServerApp](https://github.com/umputun/remark/blob/cdc1ae1e85d6efe5f0bbf341df71a77bfe09cd2e/backend/app/cmd/server_test.go#L25)~ | [Oct 14](https://github.com/umputun/remark/commit/8315299676961cf00de10d45923d5e318d12e484/checks?check_suite_id=264658757#step:5:244) |
| ~[TestServerApp](https://github.com/umputun/remark/blob/cdc1ae1e85d6efe5f0bbf341df71a77bfe09cd2e/backend/app/cmd/server_test.go#L25)~ | [Oct 16](https://github.com/umputun/remark/commit/3e4f9d6f02a6c8b204354f781c8b7d2c1a7d3941/checks?check_suite_id=266861491#step:5:244) |
| ~[TestServerApp](https://github.com/umputun/remark/blob/ee63763120b5daf05e52402d720ceeb808c5fee7/backend/app/cmd/server_test.go#L25)~ | [Dec 29](https://github.com/umputun/remark/runs/367129051#step:5:75) |
| ~[TestServerApp_AnonMode](https://github.com/umputun/remark/blob/7bab10ab5741e6dc905a977ee3f18024a99d3327/backend/app/cmd/server_test.go#L90)~ | [Dec 11](https://github.com/paskal/remark/commit/36629cc57fb3a80a55de29e3a059d0ad6d8939af/checks?check_suite_id=354021014) |
| ~[TestService_UserReplies](https://github.com/umputun/remark/blob/1cbedb85b06b86c09f36d0b3625a210f6d54569c/backend/app/store/service/service_test.go#L801)~ | [Oct 19](https://github.com/paskal/remark/runs/266854560#step:5:218) |
| ~[TestMemData_FlagListBlocked](https://github.com/umputun/remark/blob/5192a3c50a32b2f68d26f59780c046171efa4d71/backend/_example/memory_store/accessor/data_test.go#L523)~ | [Nov 17](https://github.com/umputun/remark/commit/5192a3c50a32b2f68d26f59780c046171efa4d71/checks?check_suite_id=314926262#step:5:104) |
| ~[TestBolt_FlagListBlocked](https://github.com/umputun/remark/blob/57ce795eb6d121f03abf6bf2c4e1388d1cfd6806/backend/app/store/engine/bolt_test.go#L577)~ | [Oct 20](https://github.com/umputun/remark/commit/57ce795eb6d121f03abf6bf2c4e1388d1cfd6806/checks?check_suite_id=272667667#step:5:580) |
| ~[TestRPC_admEnabledHndl](https://github.com/umputun/remark/blob/aafe760bafb89ed4e939ecbb091d2c71ae000b6a/backend/_example/memory_store/server/rpc_test.go#L350)~ | [Nov 22](https://github.com/umputun/remark/commit/aafe760bafb89ed4e939ecbb091d2c71ae000b6a/checks?check_suite_id=323640436#step:5:117) |
| ~[TestRPC_admEventHndl](https://github.com/umputun/remark/blob/bc1893883b6880655bae8572e753884104ebebc6/backend/_example/memory_store/server/rpc_test.go#L364)~ | [Dec 8](https://github.com/umputun/remark/commit/bc1893883b6880655bae8572e753884104ebebc6/checks?check_suite_id=348041164#step:5:118) |
| ~[TestRPC_deleteHndl](https://github.com/umputun/remark/blob/f830a8a473ecc2e2141f996a36ab6cba3bbe9999/backend/_example/memory_store/server/rpc_test.go#L279)~ | [Dec 29](https://github.com/umputun/remark/runs/367104452#step:5:112)
| ~[TestRPC_listFlagsHndl](https://github.com/umputun/remark/blob/ee63763120b5daf05e52402d720ceeb808c5fee7/backend/_example/memory_store/server/rpc_test.go#L192)~ | [Dec 29](https://github.com/paskal/remark/runs/367129050#step:5:110) |
| ~[TestRPC_closeHndl](https://github.com/umputun/remark/blob/b82be0cc2dfa4cc74995cad8df43c3c6bf7f497c/backend/_example/memory_store/server/rpc_test.go#L303)~ | [Dec 30](https://github.com/paskal/remark/runs/367256059#step:5:113)|

From what I see it seems like these fails are unrelated to code changes.

**Comment by paskal** [comment]
Updated the ticket with new observations.

**Comment by paskal** [comment]
Updated with new observations, stats so far:
```
   8 TestFsStore_Cleanup
   6 TestMigrator_ImportDouble
   5 TestRest_InfoStreamCancel
   5 TestMigrator_Export
   4 TestMigrator_ImportWaitExpired
   3 Test_Main
   2 TestServerApp
   2 TestRest_RunStaticSSLMode
   2 TestMigrator_Remap
   1 TestService_UserReplies
   1 TestRest_CreateWithPictures
```
I'll try to fix at least worst offenders.

**Comment by paskal** [comment]
I haven't fixed everything, but I improved the tests code reliability a little and I hope next time we'll see a false positive, it would be easier to investigate. Resolving this issue.

**Comment by paskal** [comment]
Below are problems that are actual and for sure not fixed at the time of writing. Seems to be reproducible only in GitHub Actions, working theory is that the reason for it is having single virtual CPU and thus goroutines which are executed in very strange sequential order instead of being run in parallel.


| Test name | False positive failure date |
| --------- | ------------ |
| TestServerAuthHooks | [Dec 30](https://github.com/umputun/remark/commit/4adf6c6fe10303855fa4ebeddc64e8b5811f9fe7/checks?check_suite_id=379105105#step:5:253) |
| TestRest_LastCommentsStreamSince | [Dec 30](https://github.com/umputun/remark/commit/43ee0f54f33e93d68dc8448bc643325e9d06ad56/checks?check_suite_id=378980594#step:5:380) |
| TestRest_LastCommentsStreamSince | [Dec 30](https://github.com/umputun/remark/commit/20f667bd1dc2ee45dc8b2a2549f79248f1e3a165/checks?check_suite_id=378979905#step:5:380) |
| TestRest_LastCommentsStreamSince | [Jan 2](https://github.com/paskal/remark/runs/371446576#step:5:380) |
| TestMigrator_ImportDouble | [Dec 31](https://github.com/umputun/remark/commit/ad16ed9cc772deda2ad79ef27e6cd2a1b901edc8/checks?check_suite_id=379525539#step:5:128) |
| TestMigrator_Remap | [Jan 2](https://github.com/umputun/remark/commit/ff83b446b8c94cc5e4d2b0cdd8f2841aa29baca6/checks?check_suite_id=381509766#step:5:149) |
| TestMigrator_Remap | [Jan 3](https://github.com/umputun/remark/commit/a3f4fdd841d0b53e3f8713c7a5888b13fabb024d/checks?check_suite_id=382984276#step:5:149) |

**Comment by umputun** [comment]
I think we can close this one. Tests seem to be stable now

**Comment by paskal** [comment]
Unfortunately, as you can see from the dates in the last table, we still have false positives.

Before my changes, there were "real" false positives and now we see only ones caused by GitHub limited parallelization: I believe our tests fail (almost) every time when they hit some particular kind of limited conditions on GitHub instance. If we don't want to invest time into tilting at windmills of GitHub, feel free to close this one. It's interesting to investigate that but I didn't figured out how to fix it so far.

**Comment by paskal** [comment]
Streams which is a large contributor to the false positives might be dropped in #826.

**Comment by paskal** [comment]
Resolving this one as we haven't seen these problems recently as frequent as in the past. There are still few false positives but they are rare.

**Comment by paskal** [comment]
[assert.Eventually](https://pkg.go.dev/github.com/stretchr/testify/assert#Eventually) will save us, #1122 is an example of its use.
