### ISSUE TITLE
Extend image proxy to keep local copy of pictures

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#399]
Currently, we have an optional proxy to prevent http/https mixed content. However, often, users post images hosted on some external place and, sometimes, those pictures stored temporarily. To avoid missing pictures, we can extend image proxy functionality or even bridge it to the local image store.

_This is going to be optional mode, off by default._

**Comment by smaant** [comment]
Added PR https://github.com/umputun/remark/pull/447

**Comment by paskal** [comment]
`IMAGE_PROXY_CACHE_EXTERNAL` is the parameter responsible for that, resolving this issue.
