### ISSUE TITLE
Hotkeys work in EN layout only

### ISSUE THREAD

**Issue by mykola-petiukh** [umputun/remark42#404]
Repro: switch keyboard to other language than English and press Ctrl+B.

[Demo](https://youtu.be/zr7ZJ1YwxPc) on Youtube (clickable): 
[![](http://img.youtube.com/vi/zr7ZJ1YwxPc/0.jpg)](http://www.youtube.com/watch?v=zr7ZJ1YwxPc "")

**Comment by Reeywhaar** [comment]
We have hotkeys? :D

What system/browser? It seems to work on osx/firefox.

**Comment by umputun** [comment]
yeah, I was shocked too :) Had to watch a video to figure out what hotkeys we have

**Comment by Reeywhaar** [comment]
You can check out title on hover of each button, or just plain code :-) https://github.com/umputun/remark/blob/f0750c24335742da2b04cee6e38bbb67f972c44b/frontend/app/components/input/markdown-toolbar.tsx#L29-L37

**Comment by NikolayPetyukh** [comment]
> What system/browser?

Vivaldi 2.6.1566.49 (Stable channel) (64-bit)
Windows 10 OS Version 1903 (Build 18362.267)

Github have the same issue.

**Comment by umputun** [comment]
works for me on safari and chrome (both on macos).

**Comment by Reeywhaar** [comment]
It also works for me on osx/Vivaldi 2.6.1566.49 (Stable channel) (64-bit)

So, I guess it's either Vivaldi or @github/markdown-toolbar-element

Code related to this here https://github.com/github/markdown-toolbar-element/blob/dd0ffba8d9ad9d64471d3be41b3b7e1b77aa3545/index.js#L228-L236

![Screenshot 2019-08-04 at 16 52 12](https://user-images.githubusercontent.com/884649/62424565-f7514380-b6d8-11e9-9c79-fc94e4f5fc9f.png)

Package adds `hotkey` attribute to element and then searches for it on keydown. And it seems there is mismatch between `hotkey` attr and `event.key`. 

@NikolayPetyukh if you have skill, can you please check, what `hotkey` attribute if you click select `inspect element` on any of the toolbar button? And then, is `event.key` of `keydown` event property is different on EN and RU layouts? https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by Andrew-Shtein** [comment]
Chrome 76 on Windows 10. I confirm that the hotkeys only work on EN.

![Screenshot_2](https://user-images.githubusercontent.com/12440746/62982550-d1ae0200-be6f-11e9-8311-38f87d0f4659.png)

![Screenshot_6](https://user-images.githubusercontent.com/12440746/62982919-fe164e00-be70-11e9-8ae5-44a37d90ef3e.png)

![Screenshot_5](https://user-images.githubusercontent.com/12440746/62982927-040c2f00-be71-11e9-8ab1-2e76abb9c45d.png)

**Comment by Reeywhaar** [comment]
As I expected on Windows `key` is different and it appears to be more close to [spec](https://www.w3.org/TR/uievents-key/#key-attr-values). It's a markdown-toolbar-element issue. Made an issue there https://github.com/github/markdown-toolbar-element/issues/15

**Comment by paskal** [comment]
Reply from linked issue:
> @ muan not bug.
> That's not issue. It's expected, if you wanna create multilanguage support just add another hotkey data to div, for example:
> 
> ```js
> [hotkey${currentKeyboardLang}="${event.key}"]
> ```

**Comment by paskal** [comment]
We should not fix it on our side if the library doesn't support it: we then open a can of worms by trying to support the undocumented hotkey feature for dozens of languages we have. The only solution I think is appropriate is switching to another library which will do that.

Closing this as "won't fix", feel free to comment on the issue if your opinion differs from mine.
