### ISSUE TITLE
unescape step missing for the user name

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#415]
This is an example:

<img width="759" alt="8l221-201908-17133235-gp03k" src="https://user-images.githubusercontent.com/535880/63215953-8015a980-c0f3-11e9-9554-ab76b255c8d6.png">

Note: in the info wideget is seems to be handled correctly 
<img width="480" alt="k8mh0-201908-17133330-pgcnn" src="https://user-images.githubusercontent.com/535880/63215962-9facd200-c0f3-11e9-9d8b-de7ac5368ea5.png">

**Comment by umputun** [comment]
the same issue in the last comments widget
<img width="290" alt="ics6n-201908-17134719-75ljf" src="https://user-images.githubusercontent.com/535880/63216090-991f5a00-c0f5-11e9-95b2-8560ea145611.png">

**Comment by Reeywhaar** [comment]
What kind of escaping backend does? Don't we do double work here? Why api can't return unescaped username (as well as id)? React does the job of preventing xss.

**Comment by umputun** [comment]
the backend does sanitize with `template.HTMLEscapeString(c.User.Name`). The goal was to prevent html tags and potential js code to be returned and rendered by UI.

**Comment by Reeywhaar** [comment]
I'm trying to find common ground on what should I unescape and what not. I made username `<b>bold</b>` with dev provider. And getting his info failing as remark cannot find user with id `<b>bold</b>`. I think it expects escaped id in `http://127.0.0.1:9000/api/v1/comments?user=...` which kinda odd.

**Comment by Reeywhaar** [comment]
React does job of sanitizing incoming html by itself. There is no need to escape username and id. Though comment sanitizing still necessary.

**Comment by umputun** [comment]
the same thing what user's widget unescape? I think it is limited to &, ", ' and things like this

**Comment by umputun** [comment]
> React does job of sanitizing incoming html by itself

This makes me nervous as I don't trust frontends to do backend's job ;) Maybe react is a good one and does everything correctly but someday someone, somewhere will use it wrong or will make a different frontend with a less-clever framework.

**Comment by Reeywhaar** [comment]
User's widget name is unescaped by "lucky" accident as it gets passed with via url param and something occurs while these steps. I think it's more of a bug rather then proper work.

**Comment by umputun** [comment]
I see. However you do perform some of un-escaping on the comment itself, right? Maybe the same function can do its things here?

**Comment by Reeywhaar** [comment]
> This makes me nervous as I don't trust frontends to do backend's job ;) 

Well, look, how it goes with react, I can do this:
```js
const xss = "<script>pwned</script>";
const element = <span>{xss}</span> // this is JSX syntax. Everything gets properly escaped

// in plain dom equivalent will be
const el = document.createElement("span")
el.innerText = xss

// to actually make xss work I need to make like this
const element = <span dangerouslySetInnerHTML={{ __html: xss }}></span> 

// ...again, equivalent
const el = document.createElement("span")
el.innerHTML = xss 
```

...the same thing (`dangerouslySetInnerHTML`) I have to do with your escaped name, which is I don't like either as I think html sanitation can't be done only with string escaping. There is whole set of apis in the DOM to set content properly and safe. Also I don't like this from perspective that this all will be runtime manipuations. I'm talking not only of username. What is harder is to handle id properly as we constantly pass it concatenated in url. And I have to first unescape it from html entities and then reescape it as url params.

**Comment by umputun** [comment]
> What is harder is to handle id properly as we constantly pass it concatenated in url.

Technically is is correct, User.ID wrapped HTMLEscapeString. However, this step is really over-paranoid on my side as ids generated by backend and I don't see how we can get anything escaped in. I didn't know the frontend even does all of this unescape/reescape for ids and don't think it is necessary unless I'm missing something.

**Comment by umputun** [comment]
fyi: this is the list of things we may want to unescape here (took it from go's HTMLEscape code):

```
	htmlQuot = []byte("&#34;") // shorter than "&quot;"
	htmlApos = []byte("&#39;") // shorter than "&apos;" and apos was not in HTML until HTML5
	htmlAmp  = []byte("&amp;")
```

**Comment by Reeywhaar** [comment]
So, right now I see two ways:
* Disable escaping of username and id on the server
* Unescaping response right after api call, which will be equivalent to server unescape, but will be executed after every call in runtime, which I don't like.

**Comment by umputun** [comment]
There is the third way, something in between - to do the partial unescape for quotes, apostrophes and `&` on the server-side. This is a trivial change on my side and it should resolve the immediate problem.

**Comment by Reeywhaar** [comment]
There is some inconsistency in calls.
Lets take user `<b>bold</b>`.
His id would be `&lt;b&gt;bold&lt;/b&gt;`

Trying to fetch user comments fails if we don't urlescape his id ()
```
http://127.0.0.1:9000/api/v1/comments?user=&lt;b&gt;bold&lt;/b&gt;&limit=10&site=remark

{"code":1,"details":"can't get comment by user id","error":"invalid count request {Locator:{SiteID:remark URL:} UserID: Sort: Since:0001-01-01 00:00:00 +0000 UTC Limit:0 Skip:0}"}
```
it also fails if we htmlunescape it and urlescape it (not found)
```
http://127.0.0.1:9000/api/v1/comments?user=%3Cb%3Ebold%3C%2Fb%3E&limit=10&site=remark

{"code":1,"details":"can't get comment by user id","error":"no comments for user \u003cb\u003ebold\u003c/b\u003e in store"}

```
but just urlescaped htmlunescaped  goes fine:
```
`http://127.0.0.1:9000/api/v1/comments?user=%26lt%3Bb%26gt%3Bbold%26lt%3B%2Fb%26gt%3B&limit=10&site=remark`
```

... But, trying to block with same escaping fails, but fails in interesting way. Server says that user was blocked:
```
http://127.0.0.1:9000/api/v1/admin/user/%26lt%3Bb%26gt%3Bbold%26lt%3B%2Fb%26gt%3B?block=1&ttl=10080m&site=remark

{"block":true,"site_id":"remark","user_id":"%26lt%3Bb%26gt%3Bbold%26lt%3B%2Fb%26gt%3B"}
```
... but on `get /blocked` user appears with empty name
```
http://127.0.0.1:9000/api/v1/admin/blocked?site=remark

[{"id":"%26lt%3Bb%26gt%3Bbold%26lt%3B%2Fb%26gt%3B","name":"","time":"2019-08-27T17:06:12.95497335-05:00"},...]
```
... original user we tried to block remains unblocked (nice hack for trolls, though only works with  dev provider)

Same thing goes with verifying user.

**Comment by Reeywhaar** [comment]
So, my question is, should I first htmlunescape and then urlescape id in url, or just urlescape sanitized id?

**Comment by umputun** [comment]
> Lets take user <b>bold</b>.

How do you even get such user id? The only way I can think about is via the anonymous provider. Is this the one you meant? If so, this is the issue with go-pkgz/auth library and I need to clean user names as user performs such authentication.

**Comment by Reeywhaar** [comment]
It was made with dev, not sure if it will pass with anonymous as such username blocked on ui level

**Comment by umputun** [comment]
>  should I first htmlunescape and then urlescape id in url, or just urlescape sanitized id?

I don't think you should do anything. With #415 it should be handled on the server-side as it does partial unescape. For dev provider - I wouldn't worry much as this one is not for real anyway. But I'll check anonymous and email provider and will make sure user_id doesn't include anything escapable.

**Comment by Reeywhaar** [comment]
oh, ok, good.

**Comment by umputun** [comment]
hmm, now confused for real. I don't get how you can even get such user id (except from the dev provider), as they all formed like <provider_name>_sha_of_something, i.e. `anonymous_aff008275dd1f4966ff111ba2ad910b13e2224fa`

**Comment by Reeywhaar** [comment]
Why confused? Yes, it was dev provider, only it generates such ids.

**Comment by umputun** [comment]
Maybe I misread your update? I've parsed it as you were able to simulate/reproduce the mismatch due to escaped symbols **with anonymous**

> not sure if it will pass with anonymous as such username blocked on ui level
> edit. No, it will not pass server.

**Comment by Reeywhaar** [comment]
No, I weren't, both ui and server reject such username

**Comment by umputun** [comment]
ok, i think we all good

**Comment by Reeywhaar** [comment]
I am confused why do you close this ticket as problem still stands and username is still escaped. I see you've added commit that escapes only partail of html entities but how it solves the issue?

**Comment by umputun** [comment]
this is my logic:

- if someone uses a name with html tags in, this someone is asking for the problem and we better handle such names as invalid and rejected on auth level, i.e. as a part of auth library and, in addition on UI level (i think you do it already).
- the particular case we had and the only one we have every run into was about `&#39;`
- if someone has quotes/apostrophes in his name we allow it and it will be passed unescaped back to ui

Am I missing something?

**Comment by umputun** [comment]
I'm trying to understand your confusion. I think by " how it solves the issue?" you actually meant existing comments? The change I've added was about future comments, not the existing one.

**Comment by Reeywhaar** [comment]
Hmm, I would like to agree, but I think it's a bit technological point of view. Imagine `<<<<youtube influencer>>>>` username. Perfectly valid but will be escaped.

**Comment by umputun** [comment]
> Perfectly valid 

Is it? Does google even allow such names? Anyway, my understanding is your PR got it covered, right?

_just checked github, and it doesn't like such names_
<img width="503" alt="duhau_20190820_180327 v9bht" src="https://user-images.githubusercontent.com/535880/63390489-f07f2d80-c374-11e9-87be-31a0666b0450.png">

**Comment by Reeywhaar** [comment]
I think that if you add custom oauth provider later then ploblem will appear again. I don't know what valid names on google, facebook, github, yandex.

Yeah, my PR unescapes usernames. Don't know how to make you sure that there will be no xss (I am myself not sure 100%, and if there will it would be preact bug). I can only advise you to check yourself and try to break it.

**Comment by umputun** [comment]
can you limit unescape to the same 3 suckers we do on the server-side? This way we can be 100% sure and we keep it internally consistent, i.e. both sides perform the same partial/minimal unescaping for names.

If we run into ticky names with custom providers will handle it in some way or another, but for now, this is a very theoretical problem we don't see/have yet.

**Comment by umputun** [comment]
ok, maybe a better idea? I can get rid of name unescape all together and replace it by the same `bluemonday.Sanitize` we do for the comment itself. In this case `name <b/>` will be passed as is, but crap like this `blah <a href="javascript:alert('XSS1')" onmouseover="alert('XSS2')">XSS</a>` will become `<a href="http://blah.com">username</a>`

What do you think? To me it sounds as win-win - UI gets everyhting unsescaped but potentially bad things stripped by server side anyway. The only problem with this - UI should be avare about possible "formatting attack", i.e. if someone somehow push <h1>name</h1> in

**Comment by Reeywhaar** [comment]
Hm, and then `<h1>name</h1>` will be passed unescaped in api? If so it will be great. I then remove unescaping on ui.

**Comment by umputun** [comment]
and you ok with suppressing styles here, right? We don't want name to be renederd as bold or header ;)

**Comment by Reeywhaar** [comment]
Yep, react already handles this, as I said earlier.

One thing is my concern is that search by username will work correctly (i.e sanitized name is the one that will be stored in db), but I think you understand what you're doing :-)

**Comment by umputun** [comment]
We don't have any searches by user name I'm aware of. The only API storage provides uses user_id

**Comment by umputun** [comment]
unfortunately sanitize is trying to be smart and probably doing the right thing here, but you won't like it:

1. `name <b/>` -> `name <b/>`
2. `<h1>name</h1>` -> `<h1>name</h1>`
3. but `<name 123> 'blah'"` -> ` &#39;blah&#39;`

**Comment by Reeywhaar** [comment]
Yeah, it seems it unpredictably smart. I'm going to sleep a bit. Let's think tomorrow.

**Comment by timurxyz** [comment]
"if someone uses a name with html tags in, this someone is asking for the problem" -- well if you made ' and " an exception from this assumption then nice (my case is done, and those weren't html syntax anyway), also I saw legit names with *-s and so on. I know you aren't a liberal Umputun, but you know well that names are to be respected. Just my 5 kopeks, I may have missed something. PS: We're living in 2020, and even emoticons become first class citizens in ids.

**Comment by umputun** [comment]
> I saw legit names with *-s and so on

this is fine. dash isn't (and wasn't) affected by html escaping.

>  know you aren't a liberal Umputun, but you know well that names are to be respected

wat? It has nothing to do with respect to the names or my political views. The discussion we are having here is around technical limitations and protection against possible security flaws. 

@Reeywhaar - I guess we are going to the orginal plan? I.e. `&#34;`, `&#39;` and `&amp;` unescape on both sides, unless you have some beter ideas not involving complete lack of name escaping on the backend.

**Comment by Reeywhaar** [comment]
Yep, nothing better comes to mind.

By the way, do backend sanitizer strips control characters? This concerns me more than visible symbols. Just as we going full paranoid :-)

**Comment by umputun** [comment]
sanitizer, the one used for the comment text, allows some, i.e. `\n` and `\t` intentionally.

For user name it just a direct html escaping not the full sanitizer and it doesn't handle control characters either. Maybe it should, I can strip them all with some nice regex ;)
