### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#422]
The provided README is fine and has enough info allowing to setup and configure remark42. However, it looks scary for a non-technical person. It shows endless parameter, has a lot of technical details, and feels like a heavy read.

Could be nice to make real documentation in some form. With easier step-by-step instructions, without exposing all details at the same time. There are many examples of how people do it for other OSS projects, for instance, https://gohugo.io/documentation/, https://docs.drone.io, https://docs.traefik.io, and many more.

**Comment by joseph-vidal-rosset** [comment]
Yes, you are right. Even for someone who is not a real "newbie" in installing free softwares, it seems at the first reading the documentation not very easy to succeed in installing remark42. I have understood that the best way is the docker install, but I was not really aware of docker installs. With taking care to write a correct docker-compose.yml , I hope to get a clean install today. If I am successful, I will publish a simple description of the process on my blog, and I will give you the link to this page. 
By the way, I have a last hesitation about these lines in docker-compose.yml that I just added: 
- NOTIFY_TYPE=telegram
- NOTIFY_QUEUE=100
- NOTIFY_TELEGRAM_TIMEOUT=5s

What about NOTIFY_TELEGRAM_TOKEN and NOTIFY_TELEGRAM_CHAN ? My number phone for telegram or the number that telegram sent to me for my account? Telegram except, I feel ready now to load the docker installation.

**Comment by joseph-vidal-rosset** [comment]
https://www.vidal-rosset.net/Installing_Comment_Engine_Remark42.html
As I promised. 
Of course, corrections are very welcome. If it is helpful, even just a little bit, I will not have wasted my day.

**Comment by paskal** [comment]
[The new link](https://www.vidal-rosset.net/installing_comment_engine_remark42.html) to @joseph-vidal-rosset article. Thanks for creating it Joseph, I think it will be useful for me when I'll be working on splitting Readme.

I have a plan of trying generating pages from docs subdirectory and when the result will satisfy us, we'll be able to split Readme into different smaller documents and post all of them this new way. I'll take this issue if nobody minds.

**Comment by joseph-vidal-rosset** [comment]
Thanks for this word Dmitry, but I want to be sure of having understood. Is your post only a thanks or do you except something else from me to help with this article? I am not an expert  and  Umputun helped me very kindly and I remain very thankful to him.

**Comment by paskal** [comment]
@joseph-vidal-rosset, I think I will borrow something from your article when I'll be reworking the documentation for remark. If you don't mind, of course.

I could propose you rework this article into the documentation page and put it into [docs folder](https://github.com/umputun/remark42/tree/master/docs), but I thought it would be too much to ask and I'll better spend time on doing it myself. However, if you are willing to do so yourself, I'll be more than happy to review and merge it.

The general idea as I wrote above is to split Readme to multiple documents and provide a separate subdomain with well-organized documentation rather than a current bunch of markdown documents in the repo. Having complete installation instructions like yours is a must-have for a documentation portal I have in mind.

**Comment by joseph-vidal-rosset** [comment]
Dear Dmitry, you can of course use this article as you want. If you think that it is useful, I am already rewarded. 
Best wishes.

**Comment by akellbl4** [comment]
@paskal I started working on UI for the documentation. It will get MD files from this repository and then generate the site with documentation.
I think we should structure our documentation connected with it.
If you want to know more details feel free to ask.

**Comment by paskal** [comment]
As per #709, it would make a lot of sense to add gifs to server and frontend configuration options to show administrators what to expect when they are turned on.

**Comment by paskal** [comment]
For whoever would want to pick it up: the idea here is to split [Readme.md](/umputun/remark42/blob/master/README.md) into multiple files in [docs directory](/umputun/remark42/tree/master/docs/latest) (and figuring out the proper structure for it in the process), then people who are more experienced with the system would be able to rearrange it and update particular docs more easily than the single giant Readme file.

I assume it doesn't require any technical skills aside from knowing how to work with git and markdown, and I'll be extremely grateful for whoever will be able to help with it. Feel free to poke me if there will be any questions.

**Comment by paskal** [comment]
Per talk with @akellbl4, now waiting for him to resolve #1013 and maybe simplify the generation pipeline + likely move it to this repo from a separate one, then we'll be able to proceed with splitting documentation.

**Comment by paskal** [comment]
Now the new site [is published](https://remark42.com/docs/getting-started/installation/), we are ready to start cutting stuff away from Readme so that the site with proper navigation would be the source of truth.

**Comment by paskal** [comment]
The current state of things: all documentation moved to a separate site, what is missing is a step-by-step installation guide for some popular platform like Hugo.

**Comment by paskal** [comment]
I'll do step-by-step documentation in https://github.com/umputun/remark42/issues/27, and will move [existing wiki documents ](https://github.com/umputun/remark42/wiki) to the new documentation. Existing published documentation satisfies my standards and I wrote missing pieces including the developer documentation I planned.
