### ISSUE TITLE
A few frontend improvement ideas

### ISSUE THREAD

**Issue by leem32** [umputun/remark42#426]
I know there's no ETA for any frontend refactoring, but just wanted to add a few ideas for what in my opinion would improve remark42.

Show the comments box even if a user is not logged in.
Or at least add an option for this in the config parameters.
I believe this would greatly increase the chances of a user posting a comment.
The user could type their comment and when they click the submit button a popup would appear saying "Please login to comment".

Reduce the length of the sign in to comment line.
This line of text is too long IMO and looks messy for smaller viewports and if you need to place your comments in a narrow container.
Instead of: "Sign in to comment using Google, Yandex, Facebook or email" you could just have "Login: " followed by the social login/email icons similar to the way Disqus does.

Also the dropdown boxes for email login and username break outside the container at certain viewports or in narrow containers which also looks messy and obviously unreadable.

Those are the 3 things I would most like to see added/fixed in remark42.

Thanks :)

**Comment by akellbl4** [comment]
> Show the comments box even if a user is not logged in.
I think it is not small feature. I will think about it later.

> Reduce the length of the sign in to comment line.
@umputun can I change "Sign in to comment using ..." to "Login via ..."?

> Also the dropdown boxes for email login and username break outside the container at certain viewports or in narrow containers which also looks messy and obviously unreadable.

@leem32 can you provide some screenshots or viewport sizes?

**Comment by umputun** [comment]
> can I change "Sign in to comment using ..." to "Login: ..." or "Login via ..."?

sure, good idea

**Comment by leem32** [comment]
Oddly I can't seem to reproduce the issue I was having with the username dropdown box.
I do notice, when I log into comments the sort by options box escapes its container which can cause the right side of the sort by options box to be cut off for narrow mobile viewports in a 1 column layout with no gutter.

(Screenshots using Chrome Dev tools mobile view.)
These screenshots show when a user is logged in the sort-by options box expands further to the right than when a user is not logged in. 

User not logged in: (this is fine)
![remark42 not logged in](https://i.ibb.co/N63wdWk/remark42-not-loggedin.png)

User logged in.
![remark42 logged in](https://i.ibb.co/rvr8wJN/remark42-loggedin.png)

**Comment by akellbl4** [comment]
@leem32 it's not a problem :) This is the default browser select (not HTML markup). It can render differently in different browsers. On a mobile device, it looks completely different. 

<details>
<summary>For example on iOS</summary>

![IMG_29170CCAF844-1](https://user-images.githubusercontent.com/2330682/71787822-363f4880-302d-11ea-97d3-5ccc4b01a3a1.jpeg)
</detals>

**Comment by leem32** [comment]
Good point, prob not an issue then. I'll let you know if I come across the username dropdown box issue I mentioned in the op :)

**Comment by akellbl4** [comment]
@leem32 thanks ;)

**Comment by paskal** [comment]
I see that the issues mentioned here are fixed, resolving this issue. Feel free to comment if I'm wrong.
