### ISSUE TITLE
Rename GitHub repo to umputun/remark42

### ISSUE THREAD

**Issue by bessarabov** [umputun/remark42#436]
The site is https://remark42.com
Docker image is `umputun/remark42`

But the repo is `umputun/remark`

What do you thing about renaming GitHub repo to `umputun/remark42` to make things consistent?

GitHub allow this change and there will be auto redirects  — https://help.github.com/en/articles/renaming-a-repository

**Comment by umputun** [comment]
Sounds a little dangerous to me.  According to the linked article, this supposed to be a safe operation, but I'm not sure how this may affect existing PRs. If anyone with the actual experience renaming repository can share the info and confirm -  we can do it. My primary concern is the unexpected side effects.

**Comment by umputun** [comment]
I did the same thing for my other repo and it worked fine, surprisingly uneventful.

Renamed this one as well

**Comment by bessarabov** [comment]
Great! Thank you!
