### ISSUE TITLE
"exec format error" when compiling on Raspberry Pi 4

### ISSUE THREAD

**Issue by quantonganh** [umputun/remark42#444]
`armv7l` is 32-bit, so I tried to compile from source by running:

```
make OS=linux ARCH=arm32
```

and got the below error:

```
Step 28/34 : RUN     export WEB_ROOT=/go/src/github.com/umputun/remark/backend/web &&     sed -i "s|https://demo.remark42.com|http://127.0.0.1:8080|g" ${WEB_ROOT}/*.js &&     sed -i "/REMOVE-START/,/REMOVE-END/d" ${WEB_ROOT}/iframe.html &&     go get -v github.com/rakyll/statik &&     statik --src=${WEB_ROOT} --dest=/go/src/github.com/umputun/remark/backend/app/rest -p api -f &&     ls -la /go/src/github.com/umputun/remark/backend/app/rest/api/statik.go &&     ls -la /go/src/github.com/umputun/remark/backend/web/
 ---> Running in ac3923f42342
standard_init_linux.go:211: exec user process caused "exec format error"
```

The reason is at the step 20:

```
Step 20/34 : FROM umputun/baseimage:buildgo-latest as build-backend
 ---> cc19be47a26c
```

This image is not compiled for arm.

**Comment by umputun** [comment]
A little bit confused - the title says "compiling on Raspberry Pi 4", but the make file you mentioned intended to help with cross-compile, i.e. compile binary for different platforms on something more ... traditional.

All binaries in remark42 releases were made with `make deploy`, so it can compile for different architectures just fine and it doesn't require differnet base images. However `ARCH=arm32` is not the architecture supported by go compiler. I think you want `arm` architecture (see https://golang.org/doc/install/source#environment). 

Pls note - Docker.artifact didn't make binary for `arm` and I just added it. With this change you should be able to run `make bin ARCH=arm` and it will build the binary you are looking for.

**Comment by quantonganh** [comment]
> A little bit confused - the title says "compiling on Raspberry Pi 4", but the make file you mentioned intended to help with cross-compile, i.e. compile binary for different platforms on something more ... traditional.

No, I'm on RP4 and just follow your [README.md](https://github.com/umputun/remark#without-docker):

> alternatively compile from the sources - make OS=[linux|darwin|windows] ARCH=[amd64,386,arm64,arm32]

> All binaries in remark42 releases were made with `make deploy`, so it can compile for different architectures just fine and it doesn't require differnet base images.

How an image (`umputun/baseimage:buildgo-latest`) is built on `amd64` can be run on `arm`?

```
root@raspberrypi:~/go/src/github.com/umputun/remark# docker run -it umputun/baseimage:buildgo-latest
standard_init_linux.go:211: exec user process caused "exec format error"
```

> However `ARCH=arm32` is not the architecture supported by go compiler. I think you want `arm` architecture (see https://golang.org/doc/install/source#environment).

I thought it's `ARCH` env which will be passed to the Dockerfile/Makefile, not `GOARCH`.

> Docker.artifact didn't make binary for `arm` and I just added it. With this change you should be able to run `make bin ARCH=arm` and it will build the binary you are looking for.

Same error as I said above:

```
Step 28/34 : RUN     export WEB_ROOT=/go/src/github.com/umputun/remark/backend/web &&     sed -i "s|https://demo.remark42.com|http://127.0.0.1:8080|g" ${WEB_ROOT}/*.js &&     sed -i "/REMOVE-START/,/REMOVE-END/d" ${WEB_ROOT}/iframe.html &&     go get -v github.com/rakyll/statik &&     statik --src=${WEB_ROOT} --dest=/go/src/github.com/umputun/remark/backend/app/rest -p api -f &&     ls -la /go/src/github.com/umputun/remark/backend/app/rest/api/statik.go &&     ls -la /go/src/github.com/umputun/remark/backend/web/
 ---> Running in 25f784104727
standard_init_linux.go:211: exec user process caused "exec format error"
```

I'm pretty sure you have to change the [base image](https://github.com/umputun/baseimage/blob/master/build.go/Dockerfile#L1) to something like this:

```
FROM golang:1.13-alpine@sha256:44d0ff3793c07d45af452a5f225af0e8d3dded923096e06e686fbd6f64f0f05a
```

and remove this: https://github.com/umputun/baseimage/blob/master/build.go/Dockerfile#L7

**Comment by umputun** [comment]
> How an image (umputun/baseimage:buildgo-latest) is built on amd64 can be run on arm?

It can't. But it can produce arm binary.

I have not tried to compile it on Pi and never tested or intended to do so. The make does it inside a container and this container is **not supposed to run on arm/arm64**. But the compiled binaries are. It means -  you need non-arm computer to compile it with provided make and dockerfile. This way you can build for the arm architecture the same way as for all other architectures been built for releases.

In case if you really need to compile on pi you need to do the same steps Dockerfile describes directly on your pi (with all tools installed) or make an alternative Dockerfile. I don't have plans to support an alternative build system to make it runnable on Raspberry Pi. To me, this is a really exotic and unusual idea to use such a tiny thing to build relatively heavy software.

**Comment by paskal** [comment]
Hi @quantonganh, have you figured out a way to compile a binary for Raspberry Pi?

**Comment by quantonganh** [comment]
@paskal Yes, as @umputun said:

> you need non-arm computer to compile it with provided make and dockerfile. This way you can build for the arm architecture the same way as for all other architectures been built for releases.

I tried running `make OS=linux ARCH=arm32` again on Mac OS X:

```
Step 35/36 : RUN ls -la /artifacts/*
 ---> Running in c7a57dfcf59e
-rwxr-xr-x    1 root     root      24964640 Apr 12 02:01 /artifacts/remark42.darwin-amd64
-rw-r--r--    1 root     root       8359163 Apr 12 02:03 /artifacts/remark42.darwin-amd64.tar.gz
-rwxr-xr-x    1 root     root      22468000 Apr 12 02:03 /artifacts/remark42.freebsd-amd64
-rw-r--r--    1 root     root       7950860 Apr 12 02:04 /artifacts/remark42.freebsd-amd64.tar.gz
-rwxr-xr-x    1 root     root      19370144 Apr 12 01:53 /artifacts/remark42.linux-386
-rw-r--r--    1 root     root       7452306 Apr 12 02:03 /artifacts/remark42.linux-386.tar.gz
-rwxr-xr-x    1 root     root      22440864 Apr 12 01:51 /artifacts/remark42.linux-amd64
-rw-r--r--    1 root     root       7938678 Apr 12 02:03 /artifacts/remark42.linux-amd64.tar.gz
-rwxr-xr-x    1 root     root      19474864 Apr 12 01:55 /artifacts/remark42.linux-arm
-rw-r--r--    1 root     root       7448330 Apr 12 02:03 /artifacts/remark42.linux-arm.tar.gz
-rwxr-xr-x    1 root     root      21498848 Apr 12 01:57 /artifacts/remark42.linux-arm64
-rw-r--r--    1 root     root       7268120 Apr 12 02:03 /artifacts/remark42.linux-arm64.tar.gz
-rwxr-xr-x    1 root     root      22416384 Apr 12 01:59 /artifacts/remark42.windows-amd64.exe
-rw-r--r--    1 root     root       7926898 Apr 12 02:04 /artifacts/remark42.windows-amd64.zip
Removing intermediate container c7a57dfcf59e
 ---> c951037cb282
Step 36/36 : CMD ["sleep", "100"]
 ---> Running in 7c1dcc8d697f
Removing intermediate container 7c1dcc8d697f
 ---> f331e669bc2f
Successfully built f331e669bc2f
Successfully tagged remark42.bin:latest
docker run -d --name=remark42.bin remark42.bin
411be5d9a6652a5999f927766d7a5f328129c3578c6cd955301445cdf820b308
docker cp remark42.bin:/artifacts/remark42.linux-arm32 remark42
Error: No such container:path: remark42.bin:/artifacts/remark42.linux-arm32
make: *** [bin] Error 1
```

Created: https://github.com/umputun/remark42/pull/664

**Comment by P4tzr1ot** [comment]
so if i understand correctly I have to build it with windows docker desktop then push it to my own dockerhub repo and then pull it from there onto my rpi4 it should works ?

**Comment by paskal** [comment]
That is correct.
