### ISSUE TITLE
Add providers logo

### ISSUE THREAD

**Issue by VovaStelmashchuk** [umputun/remark42#451]
Add providers logo url to request `https://remark42.radio-t.com/api/v1/config?site=<site-id>`.
The request return only providers names. Please add the url to provider logo to the response. 

FE load logo by providers name at the moment, it is not correct behavior.

**Comment by umputun** [comment]
Not sure I understand. What logo, and what the purpose of the request? What is "FE load logo by providers name at the moment, it is not correct behavior." ?

**Comment by jordan1997** [comment]
I want to add the logo of provider to my remark FE client.

**Comment by umputun** [comment]
remark's backend has no clue about the provider logo. Generally speaking, a logo is UI concern and if you want to show it - just add it on UI side. I don't see how maintaining the logo (link? png? icon?) is any concern of the backend and neither go-pkgz/auth providing all auth support.

**Comment by umputun** [comment]
out of curiosity - any reason for making a custom front end? Maybe just join upstream and PR your changes if they useful/helpful for others?

**Comment by jordan1997** [comment]
> out of curiosity - any reason for making a custom front end? Maybe just join upstream and PR your changes if they useful/helpful for others?

I don't write a web interface. I write a sdk for mobile.

**Comment by jordan1997** [comment]
> remark's backend has no clue about the provider logo. Generally speaking, a logo is UI concern and if you want to show it - just add it on UI side. I don't see how maintaining the logo (link? png? icon?) is any concern of the backend and neither go-pkgz/auth providing all auth support.

I don't want add auth provider logo on FE side, because it is not flexible. In case when backend adding new provider, FE must automatically add new provider to UI (without any update)

**Comment by umputun** [comment]
> I don't want add auth provider logo on FE side, because it is not flexible.

I get it, but making REST backend to serve some of UI assets is not the right thing to do either. And this is not the only place UI has to deal with its own translations/mapping. For example, translating error codes (or backend error messages) to human-friendly done on UI level as well, and will need to be adjusted if backend adds new errors. 

The bottom line - it should be done on UI side and UI may need adjustments if the backend changed. I don't think adding a new provider should be a breaking change for UI. The current version of web frontend maintains the list of auth providers and will ignore new providers until adjusted properly, see [this one](https://github.com/umputun/remark/pull/442) as an example.
