### ISSUE TITLE
GitHub Actions double build on PR into fork

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#576]
## Expected behavior

PR into fork runs all triggered GitHub Actions jobs once.

## Current behavior

PR into fork runs everything twice, triggered both for `push` and `pull_request`. An example: akellbl4/remark/pull/2

<img width="742" alt="image" src="https://user-images.githubusercontent.com/712534/72764195-53584780-3be7-11ea-895e-3b666e117b15.png">

Source of the problem is some misconfiguration in there:

https://github.com/umputun/remark/blob/b2176a175d4412f17d9af3b6b7c6addb99f8e86f/.github/workflows/ci-test-backend.yml#L3-L17

**Comment by Smolevich** [comment]
It's not bug because PR created from branch in fork repo to master branch and both events are triggered. As solving you can add branches only master

**Comment by umputun** [comment]
> can add branches only master

Not a good idea as it will prevent all direct branches from being processed

@paskal - why we even care? I mean this "dbl-build" is an understandable artifact of github's event nature. I think I've seen in some other place someone complained about the same thing and the conclusion was - "it is fine and expected".

Unless github actions are smart enough to figure potential doubles I'm not sure what can be done on our side.

**Comment by paskal** [comment]
I didn't know it is a known problem. If they don't care about deduplication themselves, we should not as well. Resolving.
