### ISSUE TITLE
Lack of proper image types

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#598]
Part of #447 lost image types and replaced `image/gif`, `image/png` and so on with the generic `image/*` type.

This is the quote:

> in order to guaranty that image ID doesn't change (which happened in case of resizing and FS image store) I removed storing images extensions for FS store at all. content-type for cached images is image/* which seems to be accepted by browsers without any problems.

The problem with `image/*` is not how we show it on the page (this works just fine), but how to do "Open Image in new tab/window". Both Chrome and Safari refuse to open the image and treated it as a downloadable file which is very unexpected behavior.

@smaant - I think we should restore image type somehow. Maybe we could exclude extension from image ID to prevent the confusion after resizing, not sure. Let me know what you think

**Comment by umputun** [comment]
ping, just in case you missed

**Comment by paskal** [comment]
Ping @smaant: in case you won't pick it up I'll take if you don't mind it as it seems rather important.
