### ISSUE TITLE
Reject admin names for anonymous and (maybe) email auth

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#605]
With those auth methods, bad guys can try to impersonate and pick one of admin's names. This is visible but may confuse users.

We should reject such names at least on the backend side for anonymous. Regarding email auth - unclear, because this could be a valid way for real admin to login

**Comment by Mavrin** [comment]
Maybe we can add some badge for real admin. Your idea will not work for non-english users.

**Comment by umputun** [comment]
>  Your idea will not work for non-english users.

What do you mean?

**Comment by Mavrin** [comment]
Sorry, I didn`t understand the problem correctly. But another case, how it should work for github https://github.com/Mavrin?

**Comment by umputun** [comment]
The goal is to restrict free-form user names, i.e. anonymous and maybe email. Possible collisions via social logins is another issue, outside of the scope of this ticket.

>  can add some badge for real admin

not a bad idea indeed. Currently, admins highlighted with a different color, but this is not very obvious.

**Comment by alexeyten** [comment]
umputun
umрutun
umpиtuп

**Comment by akellbl4** [comment]
First of all admin users are verified users and I think that badge togerther with different color of username are good enough for marking admins.
I think any name filled by user must be rejected if it is the same as any existed username.

**Comment by umputun** [comment]
> I think any name filled by user must be rejected if it is the same as any existed username.

There are two problems with this suggestion:

1. Generally, we don't know "any existed username"
2. For common names, this could be way too restrictive
