### ISSUE TITLE
Two .golangci.yml files

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#615]
As per [this discussion in PR](https://github.com/umputun/remark42/pull/447/files#r368281531), now we have two `.golangci.yml` files: in root and backend directories. We might want to figure out which location is preferred and move all settings to a single file.

I don't know how the root file is used, working theory is that it's the one used by GolangCI.

**Comment by umputun** [comment]
We can safely remove the one for GolangCI as tat service will be closed in just a couple of weeks
