### ISSUE TITLE
Site-wide email notifications for site owner

### ISSUE THREAD

**Issue by Infinoid** [umputun/remark42#633]
I see a scope selection dropdown for RSS, but not for email.  So it seems we'd need to subscribe separately for each page we create.

Is it possible to get an email notification for comments posted to all pages on our site, or set up a user as subscribed to everything automatically?

**Comment by paskal** [comment]
At this moment, subscribing to email notifications subscribes you to all replies to your messages on the site.
remark42 can't subscribe users to notifications automatically itself, but you can build your own flow on top of its API if you want to do so I presume. [Here](https://github.com/umputun/remark42#email-subscription) is the readme section about notifications API.

**Comment by Infinoid** [comment]
Oh, ok.  I somehow thought that it would only subscribe to comments on that particular page.  If it's site-wide, than that's perfect for what I need.

Thanks!

**Comment by Infinoid** [comment]
Hmm, one more question.  Does it subscribe to all comments?  Or only comments which reply to my comments?

**Comment by umputun** [comment]
only comments which reply to your comments

**Comment by umputun** [comment]
if you describe the use case it will be easier to understand what exactly you trying to achieve. I don't see why a regular user will want all comments sent to his email, but for admins, such functionality makes some sense.

**Comment by paskal** [comment]
Other clarification: first-level, direct replies. @Infinoid if you know a place you were looking for this information but didn't found it, please let me know and I'll add it to documentation.

Also, we have an issue about adding more infromation about it to the interface, feel free to add your thoughts to it: #564.

**Comment by Infinoid** [comment]
As the admin of a blog, I think that most comments will be responding directly to my blog post, or asking a question.  I'd like to be notified about those so I can be sure to read and respond to them.

**Comment by umputun** [comment]
yeah, it makes sense for admins, agree. Personally, I just have telegram channel with all comments as admin, but adding such functionality for emails is not a bad idea. @paskal - what do you think?

**Comment by Infinoid** [comment]
Yeah, that sounds good, except that we don't use telegram.

**Comment by umputun** [comment]
@paskal - sounds like this should be almost trivial thing to do. We already have an admin email and we don't need any confirmation. All we want is a new parameter turning it on and, probably a template to send the message.

**Comment by Infinoid** [comment]
It works!  Thanks a lot, guys.
