### ISSUE TITLE
Linters broke as we switched to 1.14

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#641]
see  #637

All actions build produces errors, like [this](https://github.com/umputun/remark42/runs/562894170?check_suite_focus=true#step:7:1).

@paskal can you pls take a look

**Comment by umputun** [comment]
tried to update linter's version to the latest. backend linter seems to work but example/memory
_store failed

**Comment by umputun** [comment]
Actually the failed one is your branch. I guess you just need to rebase it with the current master

**Comment by paskal** [comment]
I can't reproduce these errors locally no matter how many times I try.
I saw [an error](https://github.com/umputun/remark42/runs/563442016#step:8:6 ) on the first restart of a master last commit CI, but [it's gone](https://github.com/umputun/remark42/runs/563720419#step:8:1) after second restart.
Errors it reported made no sense. I would observe it but it's not 100% broken for sure. Maybe another strangeness of CI environment, maybe something else.

**Comment by umputun** [comment]
the working theory - this is due to go1.14 autodetect for vendor directory goes up and detect unexpected one from the backend. I'm not sure how sometimes it worked and sometimes not, but I think enforcing -mod=mod is the right thing to do

**Comment by paskal** [comment]
As discussed offline, might be related to https://github.com/golangci/golangci-lint/issues/995 and https://github.com/golangci/golangci-lint/issues/1011.

**Comment by paskal** [comment]
From what I see locally, Go 1.14.2 and golangci-lint 1.23.8 don't have these problems so I think it's safe to update Go in CI pipeline and stick to 1.23.8 until the problems will be sorted out.
