### ISSUE TITLE
BE and FE builds are stuck on step 29 

### ISSUE THREAD

**Issue by lon4ik4ik** [umputun/remark42#652]
Hi All,

from some reason, I can not proceed with the BE and FE builds, always stuck on step 29/45:

![image](https://user-images.githubusercontent.com/5412350/78870536-925ba380-7a46-11ea-95ae-de4623c33c1a.png)

I also see the missing Python error in the container but it was building the code flawlessly before just FYI:

 ```
node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.14.171-136.231.amzn2.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/frontend/node_modules/fsevents
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

Any suggestions how to pass it? I cleaned all and cloned the project again and also cleaned all the docker images and containers.

**Comment by umputun** [comment]
Is BE means backend? If so, I don't see from your log how it stuck, backend build finishes prior to frontend steps.

You have not provided the command you used to build id, so I'll guess you used `docker-compose.yml`. Either way, I can't reproduce the issue.

Note: you can disable tests by setting `SKIP_BACKEND_TEST=true` and `SKIP_FRONTEND_TEST=true`, like this:

```yml
    remark42:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - SKIP_BACKEND_TEST=true
                - SKIP_FRONTEND_TEST=true
```

**Comment by lon4ik4ik** [comment]
Yes, for FE I used:
docker-compose -f compose-dev-frontend.yml build
docker-compose -f compose-dev-frontend.yml up
for BE:
docker-compose -f compose-dev-backend.yml build
docker-compose -f compose-dev-backend.yml up

The problem happens during some of the node remark-ui parts with /srv/frontend.
The tests were fine till now, I would disable them now and retest.
Thanks

**Comment by lon4ik4ik** [comment]
Here is the screenshot regarding the python error which is not critical I think but still:
1.I have cloned the git project
2.added the skip true for the tests on both .yml's
3.invoked this command: docker-compose -f compose-dev-backend.yml build && docker-compose -f compose-dev-backend.yml up 
![image](https://user-images.githubusercontent.com/5412350/78881729-7f9d9a80-7a57-11ea-83ee-dfda277695d6.png)

And again stuck on step 29:
![image](https://user-images.githubusercontent.com/5412350/78881914-ba073780-7a57-11ea-85ff-be9abd91aa9d.png)

The problem is that its timeouts my SSH connnection and I do not see the final error.

**Comment by lon4ik4ik** [comment]
Ok I caught the error finally:
![image](https://user-images.githubusercontent.com/5412350/78885260-92669e00-7a5c-11ea-9d74-91ac181da56d.png)

**Comment by lon4ik4ik** [comment]
I have executed "npm update" in the ./frontend folder and the npm install and then npm run build and got the same issue as from the docker-compose step 29/45.
I see the new commit from Pavel Mineev which updated some of the node deps. But seems not to work for me.

**Comment by akellbl4** [comment]
@lon4ik4ik you got npm error 137. It means you don't have enough memory to build.

**Comment by lon4ik4ik** [comment]
tnx @akellbl4 I suspected that too, but checked the Amazon console for the Server CPU and RAM was less then 20%... but will check this more into detail

**Comment by akellbl4** [comment]
I have the same error on DO instance with 1GB of RAM.

**Comment by lon4ik4ik** [comment]
@akellbl4 are you running your Dev Env. on Linux/Mac based machine?
When I am trying to build it on my local Windows based machine from the ./frontend folder with your latest changes from the master I am getting the following:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle remark-ui@0.1.0~prebuild: remark-ui@0.1.0
6 info lifecycle remark-ui@0.1.0~build: remark-ui@0.1.0
7 verbose lifecycle remark-ui@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle remark-ui@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\lon4i\Documents\remark42\frontend\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\apache-maven-3.6.0\bin;;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Go\bin;C:\Users\lon4i\AppData\Local\Microsoft\WindowsApps;;C:\Users\lon4i\AppData\Local\Programs\Fiddler;C:\Users\lon4i\AppData\Local\Microsoft\WindowsApps;C:\Users\lon4i\AppData\Roaming\npm;C:\Users\lon4i\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\lon4i\go\bin
9 verbose lifecycle remark-ui@0.1.0~build: CWD: C:\Users\lon4i\Documents\remark42\frontend
10 silly lifecycle remark-ui@0.1.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   "webpack --mode production && es-check es5 './public/*.js'"
10 silly lifecycle ]
11 silly lifecycle remark-ui@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle remark-ui@0.1.0~build: Failed to exec build script
13 verbose stack Error: remark-ui@0.1.0 build: `webpack --mode production && es-check es5 './public/*.js'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid remark-ui@0.1.0
15 verbose cwd C:\Users\lon4i\Documents\remark42\frontend
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error remark-ui@0.1.0 build: `webpack --mode production && es-check es5 './public/*.js'`
22 error Exit status 1
23 error Failed at the remark-ui@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by akellbl4** [comment]
@lon4ik4ik yep. I develop on mac.
It seems like `es-check es5 './public/*.js'` doesn't work on windows.
Could you please run just `webpack --mode production`  or remove `es-check es5 './public/*.js'` in package.json form `build` script and run it without es-check.

**Comment by lon4ik4ik** [comment]
Tnx @akellbl4 this worked.
I tried in parallel to run the dev builds for which the FE part was ok but the BE part ended with this error:
![image](https://user-images.githubusercontent.com/5412350/78900334-fdbd6980-7a76-11ea-9069-424086017369.png)
Any ideas?

**Comment by akellbl4** [comment]
@lon4ik4ik build on cloud server works for me with 2GB of RAM.

Last error really strange. But you need only one docker instant for developing BE or FE. These compose files really similar the only difference is settings and vars about tests. Also, both of them use the same Dockerfile for a build.

**Comment by lon4ik4ik** [comment]
@akellbl4 cool, I will have to extend my EC2 to 2GB's but in the meanwhile trying on my local machine:
1.its running with npm directly on port :9000 which has no BE.
2.When building it with the docker builds so FE is ok now, but BE fails with this strange /init.sh part which I am trying to figure our what is wrong there.
Any alternative to run the BE directly without docker?

**Comment by akellbl4** [comment]
As frontend developer I prefer to run backend with docker compose and run frontend with proxy to backend.
If you want to run production instance you can use `docker-compose.yml`

I can suggest to try to rebuild BE container without cache.

**Comment by umputun** [comment]
@akellbl4 I think we should add a note to the frontend dev document saying "you need at least 2g RAM, or swap enabled"

**Comment by akellbl4** [comment]
@lon4ik4ik did you solve all problems? Do you have other questions or problems with building image? Or this issue could be closed?

**Comment by akellbl4** [comment]
Information about RAM requirements was added in #656
