### ISSUE TITLE
Wrong order of replies 

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#66]
If multiple replies added the order gets inverted. Page refresh (i.e. server's tree rendering) fixes it.

**Comment by igoradamenko** [comment]
It's fine. Otherwise we would have to add user's reply to the end of current thread. But it's not good for UX. Just imagine, you add reply to a comment and it shows after all other replies. In this case we at least need to scroll view to the new comment. I'm not sure that it's a good idea.
