### ISSUE TITLE
Lack of message in case of image upload try by anonymous user

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#661]
Hello there!

If I drag-and-drop image onto the comment box as logged in user, it gets uploaded.

In case I do it as an anonymous user, nothing happens. I think this is wrong and we should show an error message instead, like "Please log in not as anonymous user to be able to attach images".

**Comment by dellink** [comment]
Hi, I can't reproduce this issue
<img width="682" alt="Screen Shot 2020-04-18 at 15 38 46" src="https://user-images.githubusercontent.com/4217598/79637780-bb88dc00-818a-11ea-9500-eb4a14253dd3.png">

**Comment by paskal** [comment]
@dellink  You are not logged in and I'm logged in as anonymous user. Can you please try with anonim auth?

**Comment by dellink** [comment]
Yes. My mistake, sorry. I got string with path
<img width="685" alt="Screen Shot 2020-04-18 at 16 35 46" src="https://user-images.githubusercontent.com/4217598/79639174-ad3ebe00-8192-11ea-958a-8f08d88f7410.png">
