### ISSUE TITLE
Prepare 1.6 release

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#673]
We are getting close to the next release. I'll need to mark all relevant tickets and PRs with 1.6 milestone. Also, we need a short description of "what's new/changed" for release notes. @paskal - if you want to provide the list feel free to add to this ticket comments.

**Comment by paskal** [comment]
I used the search term [is:pr merged:>=2020-01-21](https://github.com/umputun/remark42/pulls?page=1&q=is%3Apr+merged%3A%3E%3D2020-01-21) to find all PRs which are merged since the last release.

```
## User-facing changes
- #590 #592 #596 code colors support
- #602 translations support added, English and Russian languages
- #606 German translation is added
- #619 Finnish translation is added
- #645 Spanish tranlation is added
- #654 Simplified Chinese translation is added
- #612 anonymous can't take name of the site admin anymore
- #616 authentification is now present where you write your comment, not only on top of the page
- #640 added email notifications on new comments for site administrator
- #648 fix special charaters like `+` in notifications email address
- #660 comment is highlighted when you open it by the direct link
- #662 uploaded images have proper type like `image/png` and will be displayed and not downloaded in browser if opened directly
- #583 autosubmit email auth/notification verification token on paste
- #579 blockquotes styles improved
- #578 #597 #608 improve mobile frontend presence
- #658 #675 remark42 shutdown procedures made more reliable
- #613 added documentation on deployment with Caddy
- #622 AWS SES email service usage documentation
- #638 documentation on how to add new translation added
- #656 RAM requirements for frontend build are documented
- #657 added documentation for SendGrid and Mailgun email services usage

## Backend changes
- #580 #623 #628 image service rehaul
- #625 image RPC added
- #582 switch image interpolation alghorytm from BiLinear to CatmullRom
- #637 #672 #683 go 1.14 support
- #659 improved error message on docker run without `/srv/var` attached
- #681 #682 `notify.Email` bugfixes
- #684 fix documentation for arm builds

## Frontend changes
- #599 started work on giving users ability to customize remark42 css
- #600 introduce stylelint
- #618 #639 #650 #653 #667 #670  js dependencies updated
- #679 scripts and docs updated
```

**Comment by umputun** [comment]
@paskal @akellbl4 @Mavrin - do you have anything in work for this release, or we good to go and make it official today?

**Comment by paskal** [comment]
All things I wanted to work on are bugfixes for obscure situations which we figured out ourselves and not received bugreports about. I would say new release is good to go.

**Comment by akellbl4** [comment]
@umputun I want to solve at least #564 #563 #560. These all tasks about subscription by email and I think they all should be together.
I need to see #560, #564 is a pretty small task, #563 shouldn't be hard to solve. But first of all, I want to finish my PR with HTML templates. I've worked today on it and I need a bit more time because golang isn't my main programming language.

**Comment by paskal** [comment]
If we still have time, I'll give #584 a try.

**Comment by paskal** [comment]
Bumped with newest PRs at that moment.

**Comment by umputun** [comment]
released
