### ISSUE TITLE
New look for auth form

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#677]
I made simple sketches (I am not a designer and I did it just on iPad with Adobe Comp), It shows the way to combine all auth providers in a compact and convenient form.
For social auth providers may use logos.

![telegram-cloud-photo-size-4-5996946266153660949-y](https://user-images.githubusercontent.com/2330682/79113980-c3134400-7d8a-11ea-881f-2ca657ca0d6f.jpg)

**Comment by umputun** [comment]
looks good. And logos for social auth should make it even better
