### ISSUE TITLE
multisites usage FE issue

### ISSUE THREAD

**Issue by lon4ik4ik** [umputun/remark42#695]
Hi All,

I have configured the following in the docker file:

 - SITE=test1,test2,test3

The after adding this widget into three different websites adding comments and rendering them seems to work fine:

https://smalltalksserverpoc.kom-design.de/api/v1/last/50?site=test1
https://smalltalksserverpoc.kom-design.de/api/v1/last/50?site=test2
https://smalltalksserverpoc.kom-design.de/api/v1/last/50?site=test3

But when loading the Remark42 website console directly:

I see this request retrieving http 401:

https://smalltalksserverpoc.kom-design.de/api/v1/user?site=site1

see following screenshot:

![image](https://user-images.githubusercontent.com/5412350/79755470-79da6b80-8319-11ea-8d0c-77e846cfbe89.png)

Any special settings to be set on the FE part? I tried to adjust /frontend/index.ejs a bit:
by setting the URL exactly to my host address but this seems not to help much.

Anything I am missing here about the usage or a setup of more than one site?

Thanks in advance,
Eli

**Comment by umputun** [comment]
https://github.com/umputun/remark42/issues/328
