### ISSUE TITLE
multisite /web console view

### ISSUE THREAD

**Issue by lon4ik4ik** [umputun/remark42#696]
Hi All,

I have configured the following in the docker file:

SITE=test1,test2,test3

The after adding this widget into three different websites adding comments and rendering them seems to work fine:

https://smalltalksserverpoc.kom-design.de/api/v1/last/50?site=test1
https://smalltalksserverpoc.kom-design.de/api/v1/last/50?site=test2
https://smalltalksserverpoc.kom-design.de/api/v1/last/50?site=test3

My question is how come on the server console: https://smalltalksserverpoc.kom-design.de/web/

I can not see any of the test1,2,3 comments, is it by design like that?

Thanks in advance,
Eli

**Comment by umputun** [comment]
they on different urls, not sure how you expect them to match. 

Your comment on site1 clearly indicates `"url":"https://kom-author.biogen-support.com/content/sandbox-ous/audimedes-hl-demo/eu/home/mainmenu5/RecipeArticlePage3.html"` but your demo page is different url

**Comment by lon4ik4ik** [comment]
So it means that it matches the URL value for the site and not the Site param? sonce the widget added on those pages includes the correct smalltalkpoc... url?

**Comment by umputun** [comment]
comments are per page, not per site. Last comments widget matches per site, the regular comment box by site+url

**Comment by umputun** [comment]
also pls note: you called /web/ "the server console". This is not a console, but a demo page, just like any other page (post) on your side. Comments for pageA (postA) are not supposed to appear for postB

**Comment by lon4ik4ik** [comment]
Tnx @umputun for refining my understanding about the console.
I just wanted to give the Moderators a way to administrate the comments with the extra admin options on the hosted server and on the other pages only enable the standard comment features for a regular commentator.

**Comment by umputun** [comment]
Not sure I get it - admins have all admin options on all pages to the site they allowed to admin. The moment admin logged in he will see those extra options. Technically speaking, remark42 doesn't have moderators. All hierarchy we have in place (at least for now) is Admin -> Regular User -> Anon User -> Read-only user

**Comment by lon4ik4ik** [comment]
Let me try to explain what I at least wanted to achieve:
Different websites will have Article pages.
Each article page will have the the widget arbitrary configured with:

```
var remark_config = {
--
  | site_id: 'test2',
  | host: 'https://smalltalksserverpoc.kom-design.de',
```
On each Article page comments would be allowed for Anon Users/ Regular Users/ Read-only Users (btw. what do you consider as Regular user? any logged in user against an auth provider?)

But my original idea was that the "Admin" which could be defined as many "Admins" would be using the /web "Console" on the Remark42 hosted solution and would have some kind of a dropdown option that I would add which will filter through the different Keys(Article-Site relation).

Probably its not as you designed the solution, but maybe you could suggest some better ideas here as you did before.

Thanks in advance,
Eli

**Comment by umputun** [comment]
in order to achieve this, you need an actual console with the support of multiple sites. Nothing stops you from implementing it, remark42 API exposes enough calls to achieve this goal.

**Comment by lon4ik4ik** [comment]
Will try to do that, but still on the current running page on my /web console, I have the following config set:

```
var remark_config = {
--
  | site_id: 'site1',
  | host: window.location.origin,
  | url: 'https://smalltalkspocserver.kom-design.de/',
```
I can not see any comments from url: ttps://kom-author.biogen-support.com/content/sandbox-ous/audimedes-hl-demo/eu/home/mainmenu5/RecipeArticlePage3.html

Because of the URL+SITE combination matching, is that correct?

**Comment by umputun** [comment]
remark42 by design intended to show comment per post/article. `/web` and `/content/sandbox-ous/audimedes-hl-demo/eu/home/mainmenu5/RecipeArticlePage3.html` **are two different posts**, so it is fully expected not to see comments for one post within another post. The matching unit, in this case, is [Locator](https://github.com/umputun/remark42/blob/master/backend/app/store/comment.go#L33)

**Comment by akellbl4** [comment]
@lon4ik4ik if you want to see comments from the page and the site you need to configure `remark_config` exactly as it is configurated at that page.

For example:
```js
var remark_config = {
  ...
  site_id: 'site1',
  url: https://kom-author.biogen-support.com/content/sandbox-ous/audimedes-hl-demo/eu/home/mainmenu5/RecipeArticlePage3.html/',
  ...
}
```

This config should show you comments from this page if your comments were on this page posted with correct `url` in config.
P.S. `host` param should refer to your remark comments server.
