### ISSUE TITLE
Rename project (because numbers in name)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [umputun/remark42#698]
I believe that you will close this issue, but anyway I want to say that I think that numbers in software name is a bad idea:

iTerm 2 version 3.
Plan 9 version 8
Remark42 version 43

Also maybe other users will vote on this issue.

**Comment by umputun** [comment]
> I believe that you will close this issue

yep

we will not rename the project. Having remark42 version 43 is not possible because we use semantic versioning. Theoretically, in 500 years we may reach `remark42 v43.0.0` but I wouldn't worry about it too much
