### ISSUE TITLE
[Feature Request] Telegram Login

### ISSUE THREAD

**Issue by MasterGroosha** [umputun/remark42#707]
It would be nice to have "Login via Telegram" support:
https://core.telegram.org/widgets/login

**Comment by umputun** [comment]
I have checked if this login can be implemented as a part of our [auth library](https://github.com/go-pkgz/auth) and the way telegram does it seems very odd and problematic. From what I can see their script renders "Log in with Telegram" button inside the iframe with another extra script that loads some Telegram entities to work with.

I think, this API  is not something useful to open authorization windows and do redirects to specified url, as any sane oauth provider does.

However, if anyone can figure a way to integrate this flow, pls provide PR to https://github.com/go-pkgz/auth

**Comment by umputun** [comment]
TG login is a part of go-pkgz/auth now (see above), so the only thing left is the UI part and a couple of params on the backend side.

**Comment by uPagge** [comment]
@paskal I understand correctly that there is no way to implement telegram-based authorization yet. I just sort of did everything according to the documentation, but the telegram button did not appear
