### ISSUE TITLE
EMOJI are not visible in UI toolbar

### ISSUE THREAD

**Issue by lon4ik4ik** [umputun/remark42#709]
I have enabled the EMOJI=true option in the docker .yml but I still do not see the emoji icon option in the toolbar and when entering an emoji raw text in the editor like :bowtie: its being rendered as is and not recognized.

What might be missing with my configuration?

**Comment by umputun** [comment]
Not sure what "emoji icon option in the toolbar" you mean. Pls take a look at [demo](https://remark42.com/demo/) and try to type `:`. It will give you the list for autocompletion and will render the emoji just fine. i.e. if you enter `:dog:` it will render a dog emoji, pretty much the same as GitHub does.

<img width="662" alt="tredb2z95l-20200512-025746" src="https://user-images.githubusercontent.com/535880/81656149-6728f300-93fc-11ea-8d09-1fa5a97b6fd9.png">


I also not sure what you meant by "entering an emoji raw text". If this is about Unicode - it works, you can enter any Unicode emoji directly

**Comment by lon4ik4ik** [comment]
Yes, I see the autocomplete option but in the listed comments widgets I see them not rendered as emojis:
![image](https://user-images.githubusercontent.com/5412350/81657632-5007f680-9438-11ea-9c43-d43048007478.png)

**Comment by umputun** [comment]
your `:dog` here has no `:` suffix. The second one is not even in the list of our emojis 

As you see the list of emojis and continue to type till you found the emoji, just hit Enter and it will put it in with both prefix and suffix

<img width="273" alt="aplsdc9i60-20200512-031149" src="https://user-images.githubusercontent.com/535880/81658419-5da08a80-93fe-11ea-9b55-a4bddcc39e01.png">

**Comment by lon4ik4ik** [comment]
Thanks looks like the Enter hit was missing, this was not trivial!
