### ISSUE TITLE
[Discussion]: I want to dig deeper in the code

### ISSUE THREAD

**Issue by mohammedi-haroune** [umputun/remark42#710]
Hello there,
I didn't find any other place to post that, redirect me if there are more suitable channels, I was interested in remark42 several months ago and I'm planning to build something on top of it, I have to be able to understand the code (both front and back ends) because I'll sure adapt some behaviors and add some features, Is there any guide on how to contribute, an explanation of the modules/components .... that could help me ?

**Comment by paskal** [comment]
Hi @mohammedi-haroune, I don't think we have anything other than Readme file in the root of the repo and Readme in frontend folder.

[Development](https://github.com/umputun/remark42#development) section of the main Readme file is a good start, as well as looking at GitHub Actions pipelines run after commits in your repo: we have pretty decent code coverage with linters and tests which will prevent you from shifting too far away from remark42 code standards.

**Comment by umputun** [comment]
> explanation of the modules/components .... 

The code is well-documented, pls take a look

**Comment by mohammedi-haroune** [comment]
> we have pretty decent code coverage

Unit tests are a good place to start since it cover a decent amount of the source code, thanks for the tip.

> The code is well-documented, pls take a look

Great to know, I'll do that and I'll get back to you when struggling
