### ISSUE TITLE
Non-latin anonymous names not allowed

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#715]
I think this is the frontend issue as server-side seems to allow it

![xumf6-202005-21124649-8ka3w](https://user-images.githubusercontent.com/535880/82588997-24d08600-9b61-11ea-85a7-00e7f0fc5857.png)

@akellbl4 @Mavrin – any idea why we limit it to latin only?

**Comment by Mavrin** [comment]
Because we have next validation regexp https://github.com/umputun/remark42/blob/master/frontend/app/components/auth/__anonymous-login-form/auth__anonymous-login-form.tsx#L38
I think we  should can skip this validation on client side and show validation error from server.

**Comment by umputun** [comment]
in fact, the backend had the same regex. I have changed it to `^[\p{L}\d_ ]+$`. Probably, we can update regex on ui side as well.

**Comment by Mavrin** [comment]
Look like you forgot it is JavaScript 😄. Property escapes `\p{…}` doesn't have good browsers support. I can try apply https://babeljs.io/docs/en/next/babel-plugin-proposal-unicode-property-regex.html, but it need to check. Also I have question. Does your regexp include Unicode? JavaScript has special flag for Unicode `/u`

**Comment by umputun** [comment]
> Does your regexp include Unicode?

https://github.com/umputun/remark42/blob/master/backend/app/cmd/server_test.go#L137

If this is a big deal on the js side we can delegate the check to backend exclusively. The nice thing with the current js check is immediate response as user types, even before hitting the login button.

**Comment by Mavrin** [comment]
Got it. I try to make it on client side.

**Comment by umputun** [comment]
fixed #716
