### ISSUE TITLE
Testing translation question

### ISSUE THREAD

**Issue by foxbg** [umputun/remark42#718]
Following the instructions I've edited index.ejs and build front end.
When I visit /web I see English instead of translated language.

What I'm missing?

**Comment by akellbl4** [comment]
@foxbg could you please provide the list of steps that you did? I've tried to change lang in `index.ejs` and it works for me.

**Comment by foxbg** [comment]
I re-executed all steps and it is working.
It looks that since I started from scratch I had to recompile again to get it to work as expected.
Thanks.
