### ISSUE TITLE
Unable to edit comments in 300 seconds (5 minutes)

### ISSUE THREAD

**Issue by patarapolw** [umputun/remark42#725]
Is this intended or can be opt out?

**Comment by umputun** [comment]
it is intended and configurable.  

<img width="1124" alt="ob5z1-202006-05110137-s6rp1" src="https://user-images.githubusercontent.com/535880/83898002-eb307b00-a71b-11ea-9b6f-931d8fd3d104.png">

**Comment by patarapolw** [comment]
Can it also be Infinity or High number? Or is it advisable?

**Comment by umputun** [comment]
it can be anything you like, i.e. 5s, 24h or 10000h. If you want to completely disable the limitation you can set it to 0.

The reason why this functionality in place is to limit the ability to alter comments after some people read it and responded. Pls note: it has two separate checks - one (configurable) is edit window and you may alter or disable it as described above. The second - if a comment has any replies it can't be edited. This part is not configurable.

**Comment by patarapolw** [comment]
So, you dislike this, then -- [How to see deleted comments in reddit threads](https://www.reddit.com/r/howto/comments/5en53l/how_to_see_deleted_comments_in_reddit_threads/)

**Comment by umputun** [comment]
I'm not sure how deleted comments related to this issue.

**Comment by patarapolw** [comment]
> The second - if a comment has any replies it can't be edited. This part is not configurable.

Not only that I cannot edit, I cannot delete.

**Comment by umputun** [comment]
I consider deleting to be part of edit functionality. Maybe an unlimited ability to delete is something useful. If you need such functionality pls make a ticket (PR welcome as well) describing your use case and proposed change.
