### ISSUE TITLE
SMTP implementation has some issues

### ISSUE THREAD

**Issue by davxiao** [umputun/remark42#730]
When the SMTP port is set to 587, emails were not delivered. 

I have attached 2 screenshots from tcpdump, both were talking to [Mailgun](mailgun.com) SMTP.

The first one was captured on Postfix relaying an outgoing email to Mailgun. Email was successfully delivered. 

From tcpdump, I observed that when the SMTP server responds `250 STARTTLS`, postfix proceeded with responding "STARTTLS" prior to disconnecting and reconnecting with TLS handshake.

<img width="1321" alt="postfix" src="https://user-images.githubusercontent.com/3964699/84094759-87cc7480-a9cb-11ea-9d0a-814ae01bfe50.png">

The second one was captured on remark42 container delivering an outgoing email through Mailgun. Email was not delivered. 

From tcpdump, I observed that when remark42 smtp client actually disconnected the TCP session immediately after receiving   `250 STARTTLS`. On the container log, the following error message was noted:

`2020/06/08 17:11:58.886 [WARN]  {notify/notify.go:122 notify.(*Service).do.func1} failed to send to email: from "remark42@davidxiao.me" with username 'postmaster@mg.davidxiao.me' at server smtp.mailgun.org:587, failed to make smtp Create: failed to auth to smtp smtp.mailgun.org:587: unencrypted connection`

<img width="1358" alt="mailgun" src="https://user-images.githubusercontent.com/3964699/84095165-95362e80-a9cc-11ea-9a04-a32e10289f05.png">

On remark42 settings, I've tried various possible values on the env`SMTP_TLS`: unset, "true" and "false"

When it's set as "false" or unset, the error message is the same as above.

When it's set as "true", the error message is 

`"2020/06/08 17:21:21.670 [WARN]  {notify/notify.go:122 notify.(*Service).do.func1} failed to send to email: from "remark42@davidxiao.me" with username 'postmaster@mg.davidxiao.me' at server smtp.mailgun.org:587, failed to make smtp Create: failed to dial smtp tls to smtp.mailgun.org:587: tls: first record does not look like a TLS handshake"`

**Comment by davxiao** [comment]
For now, my workaround is setting up a Postfix relay server on the local network listening to port 25 and having remark42 using the relay server as its SMTP server.

**Comment by umputun** [comment]
pls see [documenation](https://github.com/umputun/remark42/blob/master/docs/email.md#mailgun), it has exact snippet for Mailgun.

The short version – 587 port is STARTTLS, the one you need is TLS/SSL, i.e. **465**

See also other tickets with similar questions, like [this one](https://github.com/umputun/remark42/issues/432#issuecomment-530454973)

hope it helps.

**Comment by umputun** [comment]
I'll close this one as to me it looks like misconfiguration. Feel free to reopen if disagree
