### ISSUE TITLE
Is it possible to enabled admin notifications (about new comments), but without email subscriptions for other users?

### ISSUE THREAD

**Issue by ajgon** [umputun/remark42#731]
Hey!

So I have a problem, like described in the question.

I'm hosting my own email server, and I don't want it to send emails to (or from) anybody but me. 

After quick looking to the code, I noticed that enabling `NOTIFY_TYPE` will enable both admin and registered user notifications. Is it possible to keep only the former?

**Comment by patarapolw** [comment]
I currently cannot let user subscribe for some reasons, and my settings are

```yaml
      - AUTH_EMAIL_FROM=polv@polv.cc
      - AUTH_EMAIL_ENABLE=true
      - NOTIFY_EMAIL_FROM=polv@polv.cc
      - NOTIFY_EMAIL_ADMIN=true
      - ADMIN_SHARED_EMAIL=polv@polv.cc
      - NOTIFY_TYPE=email
```

I still receive my needed emails as an admin, though.

**Comment by paskal** [comment]
@patarapolw if admin notifications work, then following would work:

1. Subscribe as user A, leave a comment
2. Log in as user B, leave a reply to comment from user A

Then you'll receive a notification about new reply to your comment as user A. Replying to your own comment won't produce notification. Please let me know if that doesn't work as I described.

**Comment by paskal** [comment]
@ajgon my apologies for the delay with the answer. Currently, email notifications enable site email subscription as well but I do see value in adding a separate option for that.

I'll add an option like "disable email notifications for users" which would disable the frontend part of the subscription. Disabling API might be harder but I'll try to do it as well to have a proper solution.

**Comment by paskal** [comment]
@ajgon we decided to move this configuration option to frontend configuration which makes more sense and also gives the ability to customize this behavior per-site in a multi-site setup. Passing to @akellbl4 for implementation.
