### ISSUE TITLE
Opt-in functionality to check if such a comment alreday was made

### ISSUE THREAD

**Issue by sleshJdev** [umputun/remark42#740]
Not sure if this functionality should be build-in into the comment engine because it's about radiot site and the process of collecting the new topics for the next podcast release. The use case is the following, I noticed not once that ppl add the same topic multiple times because it's quite hard to identify if such a topic was already suggested especially when there are a lot of comments and replies. 

How do you feel about functionality to check whether such a topic(links, subject, etc) was already posted earlier or not and if it was, then notify ppl about it and give him decide if it's really want to post it again?

Potentially it could somehow be addressed with the help of the #734

**Comment by umputun** [comment]
see https://github.com/umputun/remark42/issues/566
