### ISSUE TITLE
Get current user through API fails preflight (cross-origin)

### ISSUE THREAD

**Issue by rnmp** [umputun/remark42#749]
Hey all,

I’m building a custom frontend for the comments on my blog and I realized there’s no way to access a current user by ways of a GET request to `/api/v1/user?site=site-id`, I fail preflight because CORS seem to be hardcoded since https://github.com/umputun/remark42/pull/183 and I cannot customize the allowed origins:

```
Access to fetch at 'https://[redacted]/api/v1/user?site=[redacted]' from origin 'http://localhost:3000' has been blocked by
CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the
request's credentials mode is 'include'.
```

I’m making a `fetch` request with basic `{ credentials: 'include' }`.

Is there any workarounds or planned work towards addressing this?

**Comment by umputun** [comment]
As far as I understand the hardcoded CORS doesn't prevent you from altering it on the proxy level. Smth like this (nginx):

```
add_header Access-Control-Allow-Origin DENY;
add_header Access-Control-Allow-Origin whatever-you-need;
```

**Comment by rnmp** [comment]
I tried to alter it as well, but it doesn’t replace the hardcoded CORS, it adds to it:

```
Access to fetch [...] The 'Access-Control-Allow-Origin' header contains multiple values
'*, DENY, http://localhost:3000', but only one is allowed. Have the server send the header 
with a valid value, or, if an opaque response serves your needs, set the request's mode 
to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by umputun** [comment]
`MANUAL_CORS`  (maybe better to name it `PROXY_CORS`?) is a reasonable option

**Comment by umputun** [comment]
The master version has poxy-cors option disabling internal CORS middleware. Give it a try

**Comment by rnmp** [comment]
@umputun Thanks so much for looking into this! I’m having trouble building `umputun/remark42:master` from DockerHub, says `ERROR: Cannot locate specified Dockerfile: Dockerfile`. This is not the case when I run `latest` instead.

**Comment by umputun** [comment]
I'm not sure what you meant by "building umputun/remark42:master from DockerHub". You don't need to build it, just pull from docker hub, i.e. `docker pull umputun/remark42:master` as image already built.

**Comment by rnmp** [comment]
Ok thanks. I managed to run the app and confirm that the request headers are proxied correctly!
