### ISSUE TITLE
Multiple admin emails

### ISSUE THREAD

**Issue by dkornilove** [umputun/remark42#756]
Hello! I have a couple of managers that should be notified about all the new comments via email. But as I see I can set only one admin email at the ADMIN_SHARED_EMAIL variable. Is there any way to configure multiple admin emails? Thanks

**Comment by umputun** [comment]
Currently, there is no way to define multiple admin emails. This is something I'd like to add, but for now you have two workarounds:

- Create a "group email" if your email service support it (google's gsuite can do it) 
- Use telegram notifications as it pushes updates to groups

**Comment by umputun** [comment]
@paskal let me know if you want to deal with this one. It seems to be a trivial change:

1. Change AdminGroup.Email (both shared and RPC) to the slice / repeated
1. Change rest.AdminEmail to slice
1. Change notify.Request to support slice of emails  or send one-by-one from `createCommentCtrl`

**Comment by paskal** [comment]
ETA ~1 week.

**Comment by paskal** [comment]
@dkornilove my apologies, it took longer than I anticipated. After linked MR will be merged you'll have ability to set up multiple emails for notifications.

**Comment by dkornilove** [comment]
@paskal , @umputun 
Thanks for the attention! But sadly I am not able to get it work with this env variable defined:
`- ADMIN_SHARED_EMAIL=exam.ple@mail1.com,example2@mail2.ru`
Emails are not sent. Only this working for me
`- ADMIN_SHARED_EMAIL=example@mail.com`
Im using last master version

**Comment by paskal** [comment]
@dkornilove, the first variant should work. Would you be so kind as to post docker-compose log around the time the message supposed to be sent to these emails? There should be something from notification part of the program at least trying to send them.
