### ISSUE TITLE
Create recursive email notifications to parent comment about all children

### ISSUE THREAD

**Issue by paskal** [umputun/remark42#758]
A follow-up for #745 involved parties agreed upon, we want to implement email notifications to be sent not only about direct replies to the user's comment but about any replies to them as well as deep as it goes.

- 1
  - 2
    - 3
      - 4

In the scenario above, user 1 would receive notification for comment 2 (but should 2-4), user 2 would receive notification for comment 3 (should be 3-4), user 3 would receive notification for comment 4 (will not be changed).

**Comment by paskal** [comment]
Working on it, found a lot of complications in implementation progress. Trying to figure them out at the moment.

**Comment by paskal** [comment]
I finally figured out proper tests for the case (in the branch [paskal/recursive_email_notifications](https://github.com/umputun/remark42/tree/paskal/recursive_email_notifications)), what is left is the easy part of actually writing the code to satisfy them.

**Comment by paskal** [comment]
@axllent @kostimoshenko what do you think we should do with recursive email notifications, make them an option which can be turned on and off, or change the default behavior?

From a technical perspective, it's easier to do it without a flag: less code to maintain, fewer settings for users to think about.
It was implemented that way and not recursively because when I was writing it I had enough trouble with figuring out other things, not because I thought that notification to the single parent is better than notifications to all parents recursively. In my opinion, recursive notifications are more natural than the old behavior.

**Comment by axllent** [comment]
@paskal Of course this is just my personal opinion, however I cannot think of any scenario where one would ever just expect notifications for direct replies. I thnk this new notification system (recursively) should definitely be the default/standard.

**Comment by paskal** [comment]
Per talk with @umputun, recursive notifications to any comment under your comment will be the new default.

**Comment by kostimoshenko** [comment]
Hey @paskal, I can see that my input is no longer required, but I felt it was right to reply anyway. I concur with you all, in my opinion recursive notifications need to be the new default behavior.
