### ISSUE TITLE
Alternate cookie name for XSRF-TOKEN

### ISSUE THREAD

**Issue by avt00** [umputun/remark42#769]
remark's XSRF-TOKEN are conflicting with a Laravel application that is hosted on the same domain name. Is there any way to rename remark's cookie to something like XSRF-TOKEN_remark42?

**Comment by umputun** [comment]
Currently, there is no support for such customization in remark42 configuration but [auth library](https://github.com/go-pkgz/auth) supports it.

`auth.Opts`(passed [here](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L906)) allows custom names for cookies and headers:

```
	// optional (custom) names for cookies and headers
	JWTCookieName  string // default "JWT"
	JWTHeaderKey   string // default "X-JWT"
	XSRFCookieName string // default "XSRF-TOKEN"
	XSRFHeaderKey  string // default "X-XSRF-TOKEN"
	JWTQuery       string // default "token"
```

You can add new `Auth` [param(s](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L80)) to change the default

**Comment by avt00** [comment]
Thank you. It would be cool if you could add this configuration option in the future releases.
