### ISSUE TITLE
Without Preact 

### ISSUE THREAD

**Issue by Textras** [umputun/remark42#777]
Is anyone using this without Preact?

**Comment by umputun** [comment]
not sure what you meant. API can be used with or without preact, even without js. If you mean alternative implementation with a different framework - we don't have it and not planning to do it.

**Comment by Textras** [comment]
Sorry, the latter. Got it, thank you.

**Comment by Mavrin** [comment]
Hi, @Textras! You can use remark42 with any js framework. Remark42 js client is standalone and don't need any external dependencies. Preact is used underhood, but it can be replaced by another library, it  doesn't matter. For example, it can be integrated with vue https://github.com/umputun/remark42/blob/master/docs/spa.md
