### ISSUE TITLE
Disable comment deletion and/or show deleted comments

### ISSUE THREAD

**Issue by George3d6** [umputun/remark42#778]
Hello,

Recently I've had remark42 email me about several comments, but upon searching them I couldn't find them. 

I'm unsure if this is due to a bug in my setup or the comments being deleted by the users.

Is there any way to disable comment deletion and/or to preserve an admin log of sorts where I can see all comments? (even ones that were deleted and/or edited)

**Comment by umputun** [comment]
> Is there any way to disable comment deletion

Kind of. You can set `EDIT_TIME` to some tiny value (but not 0), for example, 1ms. This effectively disables edit/delete functionality. 

> preserve an admin log of sorts where I can see all comments

it produces a log with a lot of details. You may even turn on debug logging to get even more details. The log sent to stdout and the user can forward/save it. This is not exactly the log you meant, but this is the closest thing.

**Comment by George3d6** [comment]
Yeap, I think that should suffice, thanks :)
