### ISSUE TITLE
docker-compose error "npm WARN tarball tarball data seems to be corrupted. Trying one more time."

### ISSUE THREAD

**Issue by CodeWithOz** [umputun/remark42#780]
I get errors like this one when I run `docker-compose up -d` to start up the backend:
> npm WARN tarball tarball data for eslint-config-prettier@6.10.1 (sha512-svTy6zh1ecQojvpbJSgH3aei/Rt7C6i090l5f2WQ4aB05lYHeZIR1qL4wZyyILTbtmnbHP
5Yn8MrsOJMGa8RkQ==) seems to be corrupted. Trying one more time.

It happens for different packages that are being installed, but the effect is the same: that docker step effectively stalls and the process doesn't continue. This has been happening at this step:
> Step 22/45 : RUN cd /srv/frontend && CI=true npm ci --loglevel warn

I've seen different reports online about the cause of this error, and they seem unrelated. So is this something you have seen with this project before? And if so how can it be fixed? Thanks!

**Comment by umputun** [comment]
To me, it looks like a warning, not an error and as I build it - I don't see this warning. Maybe some proxy on your side messing with your network? Anyway, the build passes just fine on my workstation as well as in Github Actions and on drone CI.

Pls note: this npm step may take time, as a few minutes. Maybe you don't give it a chance to finish?

**Comment by CodeWithOz** [comment]
Hmm I actually left it to run for more than an hour on 3 different occasions. After the first error showed, it would eventually show another one (for another package), then another one... and usually it would get stuck on the third package.

**Comment by CodeWithOz** [comment]
Looks like it was a problem with my internet connection.
