### ISSUE TITLE
Documentation on spam detection/protection features

### ISSUE THREAD

**Issue by CodeWithOz** [umputun/remark42#783]
Can you please provide a quick rundown/brief explanation of the spam protection features on the backend? I see [this thread](https://github.com/umputun/remark42/issues/754) and [this one](https://github.com/umputun/remark42/issues/754) and some code in [`/backend/app/cmd/cleanup.go`](https://github.com/umputun/remark42/blob/master/backend/app/cmd/cleanup.go) that relates to spam, but I'm not certain what exactly is implemented and how it should be used.

Thanks!

**Comment by paskal** [comment]
[Here](https://github.com/umputun/remark42/blob/master/backend/app/cmd/cleanup.go#L268-L291) is the current spam detection, there is nothing aside what's written in this check currently.

**Comment by paskal** [comment]
The documentation is published [here](https://remark42.com/docs/manuals/spam/).
