### ISSUE TITLE
Requirements for implementing alternate db store

### ISSUE THREAD

**Issue by CodeWithOz** [umputun/remark42#786]
Hi, what would be required for implementing an alternate db store? It looks like the necessary functionality is listed in [`/backend/app/store/engine/engine.go`](https://github.com/umputun/remark42/blob/master/backend/app/store/engine/engine.go) along with the default bolt implementation. Is there anywhere else that I'd have to update or make changes to? Thanks.

**Comment by umputun** [comment]
Technically speaking - yes, all you need to do is provide your implementation of `store.Interface`. Bolt's implementation can be used as a reference. 

However, it means - you on your own with the fork you make and will need to maintain it. A much better way would be to implement `remote` store you can run without modifying the core code. There is an example of such implementation, see [example/memory_store ](https://github.com/umputun/remark42/tree/master/backend/_example/memory_store)
