### ISSUE TITLE
fcgi server

### ISSUE THREAD

**Issue by vendelin8** [umputun/remark42#801]
This project looks a really cool extension for hugo. I have only one problem: the hosting that I use doesn't run http servers like this. There's possibility to run fcgi (https://golang.org/pkg/net/http/fcgi/) server though. How could I use Remark this way?

**Comment by umputun** [comment]
nop, this won't work. You have to run it as a normal binary/server/container. It doesn't have to run on the same hosting limiting you, but can run on any VPS hosting and serving comments to your remote hugo site
