### ISSUE TITLE
Backups not working (self-signed certificate)

### ISSUE THREAD

**Issue by leem32** [umputun/remark42#804]
On my local server when I try to make a manual backup with:  `sudo docker exec -it c256ebb5 backup -s di-dev --admin-passwd *****`

I get an SSL error.

```bash
remark42 master-5039e8d-20200222-13:04:57
2020/10/25 10:06:36.545 [INFO]  {cmd/backup.go:28 cmd.(*BackupCommand).Execute} export to /srv/var/backup, site di-dev
2020/10/25 10:06:36.545 [DEBUG] {cmd/backup.go:37 cmd.(*BackupCommand).Execute} export file /srv/var/backup/userbackup-di-dev-20201025T100636.gz
2020/10/25 10:06:37.050 [ERROR] {app/main.go:54 main.main.func1} failed with Get https://dev.mywebsite.com/comments/api/v1/admin/export?mode=file&site=di-dev: x509: certificate is valid for comments.mywebsite.com, mywebsite.com, www.mywebsite.com, not dev.mywebsite.com
request failed for https://dev.mywebsite.com/comments/api/v1/admin/export?mode=file&site=di-dev
github.com/umputun/remark/backend/app/cmd.(*BackupCommand).Execute
        /build/backend/app/cmd/backup.go:53
main.main.func1
        /build/backend/app/main.go:52
github.com/jessevdk/go-flags.(*Parser).ParseArgs
        /build/backend/vendor/github.com/jessevdk/go-flags/parser.go:318
github.com/jessevdk/go-flags.(*Parser).Parse
        /build/backend/vendor/github.com/jessevdk/go-flags/parser.go:190
main.main
        /build/backend/app/main.go:59
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
...
```

I have a self signed certificate on local server with the alternate names.
```
[alt_names]
DNS.1 = dev.mywebsite.com
DNS.2 = www.dev.mywebsite.com
DNS.3 = comments.dev.mywebsite.com
```

But the certs for this are located in `/etc/nginx/ssl/` .

So, remark42 is not looking here for the certs.

Where does remark42 look for the SSL certs?

Also my `./var/backup` dir inside the docker container is empty so auto backups are not working either.

**Comment by umputun** [comment]
this has nothing to do with remark42. Your site (nginx) doesn't have a cert for dev.mywebsite.com. Just try to hit your home page with https://dev.mywebsite.com and you will see the same error.
<img width="956" alt="gpgs2-202010-25123314-f2e77" src="https://user-images.githubusercontent.com/535880/97114400-4c062300-16be-11eb-9872-f8f4f2840dca.png">

**Comment by umputun** [comment]
regarding your second part, i.e. "./var/backup dir inside the docker container is empty so auto backups are not working either" - need more details (logs). Check the messages after `[DEBUG] exporting`, it may give a clue what's going on

**Comment by leem32** [comment]
No, I do have a certificate. The website https://dev.mywebsite.com is not a real domain name it's just how I have it set up in my HOST file to point to a private IP address.

If I go to https://dev.mywebsite.com  in my browser my local dev site loads and has a shield to show the site is secure.

It's only a self-signed cert though but that's all I need for local dev (offline).

My Nginx certs are in 

```
ls -la /etc/nginx/ssl/
total 36
drwxr-xr-x. 2 root root    61 Apr 21  2020 .
drwxr-xr-x. 4 root root 12288 Jul  8 12:46 ..
-rw-r--r--. 1 root root  1472 Aug 12 14:59 di-dev.crt
-rw-r--r--. 1 root root  1704 Aug 12 14:59 di-dev.key
-rw-r--r--. 1 root root 11122 Aug 12 14:59 openssl.cnf
```

And in my nginx conf I point to those files.

```nginx
ssl_certificate /etc/nginx/ssl/di-dev.crt;
ssl_certificate_key /etc/nginx/ssl/di-dev.key;
```

I'm guessing I have an old SSL cert somewhere which Remark42 has found on my local dev server.

That's why I wanted to know where remark would look for the cert?

**Comment by umputun** [comment]
if you use default SSL mode in remark42 (`none`) (param `ssl.mode` or env SSL_MODE) remark42 doesn't do anything with SSL and has no clue about SSL as it expects your proxy to deal with this. If you set it to `static` you also provided `ssl.cert` path. If you set it to `auto` it will try to obtain LE cert

**Comment by leem32** [comment]
I haven't set anything for SSL in the config

**Comment by umputun** [comment]
well, in this case, see my first response - this is not remark42, but your nginx in front of remark42 handling SSL termination

**Comment by umputun** [comment]
another thing I'd suggest you check - have you added your self signed cert to remark42 container? As you do the backup it makes https call from the container. As far as I recall alpine appending all certs from /usr/local/share/ca-certificates to /etc/ssl/certs/ca-certificates.crt as you run `update-ca-certificates`

**Comment by leem32** [comment]
No I haven't added my seld signed certificate to the remark42 container.
As I mentioned they point to Nginx like below.
```
ssl_certificate /etc/nginx/ssl/di-dev.crt;
ssl_certificate_key /etc/nginx/ssl/di-dev.key;

```

How would I add them to the container? Would I just drop them in manually into a specific directory or would I need to do this in Remark42 config?

**Comment by umputun** [comment]
Let me repeat - this is not SSL to remark42 issue, but rather an attempt to reach  https://dev.mywebsite.com/ from the container. Nothing in remark42 config involved in this process and it won't work for any other, non-proxied URL as well.

The configuration you made with self-signed certs is not something we officially support or recommend. I guess you can try mount certs directory to your container and change `docker-init.sh` to copy them to  /usr/local/share/ca-certificates and invoke update-ca-certificate if you are willing to support such a custom build.

As long as the basic `curl https://dev.mywebsite.com` or `curl https://dev.mywebsite.com/comments/ping` works from your container, the backup request should be working as well.

**Comment by leem32** [comment]
The thing is the error message doesn't make sense.
```
[ERROR] {app/main.go:54 main.main.func1} failed with Get https://dev.mywebsite.com/comments/api/v1/admin/export?mode=file&site=di-dev: x509: certificate is valid for comments.mywebsite.com, mywebsite.com, www.mywebsite.com, no t dev.mywebsite.com
```
My local dev cert uses dev. for all domains. In Chrome browser on local domain dev.mywebsite.com if I click the shield icon and Certificate -> details -> alt names I get:
```
DNS Name=dev.mywebsite.com
DNS Name=www.dev.mywebsite.com
DNS Name=comments.dev.mywebsite.com
```

So I don't understand why the error message says "certificate is valid for comments.mywebsite.com, mywebsite.com, www.mywebsite.com,"

I can't see where it's getting these domains from. 

Forget it anyway. I give up. 

Thanks

**Comment by umputun** [comment]
what I've tried to say - the message `certificate is valid for comments.mywebsite.com, mywebsite.com, www.mywebsite.com, not to dev.mywebsite.com` is your hit to nginx, not remark42. remark42 just a client in this case. By running `curl` within the container you will see the same error, and your request never reached the remar42 server

**Comment by leem32** [comment]
I understand that yes. 
As you say if I run curl from inside remark container it returns the same error:

```
sudo docker exec -it c256eb295 /bin/sh
/srv # curl https://dev.mywebsite.com
curl: (60) SSL: no alternative certificate subject name matches target host name 'dev.mywebsite.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
I just can't work out where it's found those alternate names from.
It works in production anyway and auto-updates work too it also works in a staging environment so it must be a problem with the self-signed cert.

Thanks for your help and patience :)

**Comment by umputun** [comment]
np. I also puzzled where those alternate names from. The actual (failed) call is from stdlib's http client and the actual error is from https://golang.org/src/crypto/x509/verify.go (line 147).

_If you figure what's going on pls update the ticket, can be useful for others_
