### ISSUE TITLE
How to enable notifications

### ISSUE THREAD

**Issue by mind-overflow** [umputun/remark42#814]
Hi! I'm trying to enable email and telegram notifications for new comments but I really don't understand how.
I've set up all the email parameters (smtp server, password, address, etc.) and yet emails are not arriving.
I have also created a Telegram bot and added its secret key to the compose file, however, I don't know what am I supposed to enter as the "NOTIFY_TELEGRAM_CHAN".
Any idea on how to enable both?

Also, can you clarify what does the "NOTIFY_QUEUE" size do?
Thanks!

**Comment by paskal** [comment]
Re email + telegram: you should set `NOTIFY_TYPE=telegram,email` to make it work.

Re telegram channel: please see [this repo](https://github.com/GabrielRF/telegram-id). I think we should include a link to it into the documentation as well if it would help you.

**Comment by mind-overflow** [comment]
Thank you! I was finally able to get Telegram notifications by using my id obtained by talking to the `@userinfobot` bot.
Email notifications are still not working, but this must be related to something wrong in my configuration.
Thanks again!

**Comment by paskal** [comment]
Just in case it's not solved, you should see a notification being sent in the docker-compose logs, as well as error if it happened.

**Comment by paskal** [comment]
Resolving, if you don't mind. Feel free to reopen \ create a new one.

**Comment by mind-overflow** [comment]
Hey! Sorry for the terribly late response. A lot of stuff has been happening recently.
Anyway, I haven't been able to make emails work yet. I am running a postfix + dovecot server, and in the postfix logs (/var/log/maillog), whenever I add a new comment, this happens:
```
Jan 25 20:59:35 mindoverflow postfix/submission/smtpd[3087880]: connect from unknown[172.30.0.2]
Jan 25 20:59:35 mindoverflow postfix/submission/smtpd[3087880]: lost connection after CONNECT from unknown[172.30.0.2]
Jan 25 20:59:35 mindoverflow postfix/submission/smtpd[3087880]: disconnect from unknown[172.30.0.2] commands=0/0
```

Coming from the docker container Remark42 is running in. The mail server is working perfectly fine with many other services (Nextcloud, Gitea, etc...) which I configured in the exactly same way:

```
            - NOTIFY_TYPE=email,telegram
            - ADMIN_SHARED_EMAIL=my@email.com
            - NOTIFY_EMAIL_ADMIN=true
            - SMTP_HOST=mail.myserver.com
            - SMTP_PORT=587
            - SMTP_USERNAME=mail@myserver.com
            - SMTP_PASSWORD=MyPassword
            - SMTP_TLS=true
```


SMTP server is running on port 587 via STARTTLS. Email and Password are correct.

**Comment by umputun** [comment]
@mind-overflow we support SMTP_TLS, not STARTTLS. I would guess you should change the port to 465 and it will fix your issue. 

See also https://github.com/umputun/remark42/issues/730#issuecomment-640973341

**Comment by mind-overflow** [comment]
Thanks! This was indeed what I needed to do. That's unfortunate however, as I had SSL disabled in favor of STARTTLS as it's better in terms of security, and now I only have it enabled for remark42. Any plan to introduce support for it?

Also, quick question since I don't want to flood you with new issues - is there any way to send emails to normal users too, when you reply to their comment?
Thanks again!

**Comment by umputun** [comment]
>  had SSL disabled in favor of STARTTLS as it's better in terms of security

My view is the opposite. From what I understand STARTTLS is a riskier protocol and there is a chance to send the plain password over an unencrypted channel if STARTTLS foe whatever reason failed upgrading it to a secure connection.

This is the reason why we decided to stick to the standard TLS.  Pls note - as far as I know, this is not a question of taste/opinions, but rather the official recommendation from the RFC - https://tools.ietf.org/html/rfc8314#section-3. I also recall the implicit TLS is the recommended way to send an email with gmail, however they support both ways.

**Comment by umputun** [comment]
and to the second question - yes, we support email notification to the normal users as well
