### ISSUE TITLE
/web does not respect remark_config.host

### ISSUE THREAD

**Issue by paul-nameless** [umputun/remark42#818]
I followed steps on [this doc](https://github.com/umputun/remark42/blob/bcc2fc7a9e56c6de88b9270a109ac9fce64aff1f/docs/1.6/subdomain.md) and faced a problem that I can't open /web page.

**What expected:**
1. When I navigate to https://example.com/remark42/web web page of the remark42 will be opened.
2. `Disable third-party cookies blocking to login or open comments in new page` the `new page` 
should open web page as well

**Reality:**
1. I am redirected to /web (https://example.com/web)
2. This page should be opened https://example.com/remark42/web/comments.html?...

Is it supposed to work like this or should js respect the remark_config.host?
Are you interested to support remark42 without a subdomain?

**Comment by umputun** [comment]
> Are you interested to support remark42 without a subdomain?

it is already supported, see https://remark42.com/docs/1.6/subdomain/

**Comment by paul-nameless** [comment]
Sorry for misunderstanding, I meant if you are interested to continue to support remark42 without a subdomain.
I understood from your reply that you do, thanks.
