### ISSUE TITLE
Loading the same comments thread on multiple pages

### ISSUE THREAD

**Issue by leem32** [umputun/remark42#820]
It would be great if you could load the same comments thread on multiple pages.
Disqus has this feature by using a page identifier, which is just a URL.

https://help.disqus.com/en/articles/1717158-how-do-i-load-the-same-thread-of-comments-on-multiple-pages

**Comment by umputun** [comment]
is it the same as https://github.com/umputun/remark42/issues/812 ?

**Comment by leem32** [comment]
No, say you have a page ( /animals/lion ) with Remark42 comments loaded on.

Then you have another page ( /cats/lion ) and you want to load the same Remark42 comments thread on /cats/lion as /animals/lion because you don't want multiple comments threads on your site about the same topic.

**Comment by umputun** [comment]
ah, I see what you mean, somehow read if from the iPhone and imagined smth else ;)

However, I don't really understand the intended use case. Why someone needs the same/shared comments for different posts/URLs?

**Comment by umputun** [comment]
@Mavrin - in case we decide to support it (I still don't really get why) it should be smth UI side only as the server doesn't really care about the source of location as long as it set by UI. So, theoretically, it should be possible to support overwrite of whatever default is now for location.

**Comment by leem32** [comment]
It can be useful if you have multiple pages across a site that are on the same topic and you don't want a separate thread for each page. 

Here's an example in use:
https://downdetector.co.uk/status/facebook/
https://downdetector.co.uk/status/facebook/news/347950-user-reports-indicate-problems-at-facebook/

**Comment by leem32** [comment]
It would probably only make sense if the comments where synced both ways though e.g /animals/lion -> /cats/lion and /cats/lion -> /animals/lion

**Comment by umputun** [comment]
not sure what you mean. This is not about comments sync but rather pointing multiple different web pages to the same  `locator.url` (see https://github.com/umputun/remark42/blob/master/backend/app/store/comment.go#L36)

**Comment by leem32** [comment]
Yes, you are right the work sync is not right here.

**Comment by leem32** [comment]
Multiple pages across a website sharing the same comments thread. That might have been a better title for this.

**Comment by akellbl4** [comment]
@leem32 I think you could do what you want with current API.
[This is the docs for it](https://github.com/umputun/remark42#comments)
Just pass the same value to `url` param it should help you.

**Comment by leem32** [comment]
@akellbl4, Perfect, I didn't realize the `url` param could be used for this purpose. Thanks.
