### ISSUE TITLE
Broken link in manual

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#821]
There is a link in readmi

If you want to set this up on a Single Page App, see /docs/spa.md.

It is broken.

**Comment by paskal** [comment]
Thanks! Should be https://github.com/umputun/remark42/blob/master/docs/latest/spa.md.

**Comment by uPagge** [comment]
Thank you :)

seems to have found another misprint in the confige. 

Setup on your website -> comments

I don't think it's a comma after 

locale: 'en'
