### ISSUE TITLE
Telegram notify not work

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#822]
I tried to add telegram notifications, and as far as I understand it worked, but they do not work.

![telegram](https://user-images.githubusercontent.com/40397740/100429695-bee03080-30a6-11eb-8a7a-5ee72773471d.png)

![telega2](https://user-images.githubusercontent.com/40397740/100430267-999ff200-30a7-11eb-9e4e-6447112d3ed3.png)

if you follow this link

![изображение](https://user-images.githubusercontent.com/40397740/100429841-fb139100-30a6-11eb-8dc7-6fc58d3ea8bb.png)

but 

![изображение](https://user-images.githubusercontent.com/40397740/100429890-1383ab80-30a7-11eb-9efb-1ae59fd7a2d2.png)

**Comment by umputun** [comment]
it supposed to work. Well, at least it works fine for me on multiple sites.

Have you checked [docs](https://remark42.com/docs/1.6/telegram/)? From your ticket, it is hard to figure what is wrong/missing, need more details about your configuration. But I'd suggest to follow the docs and check if you have the bot registered, `NOTIFY_TELEGRAM_TOKEN` set, `NOTIFY_TYPE` includes `telegram`. And in addition, make sure `NOTIFY_TELEGRAM_CHAN` points to your channel name. This is all you need to make it work.

**Comment by uPagge** [comment]
@umputun I hastened the opening of the issue, made a misprint in the name of the channel, please forgive me.

I wanted to ask you another question, what happens if I change the domain. As far as I understand, the absolute path for links is used by default. Is there any way to easily fix a domain in a database file?

I also see the solution to this problem in the use of relative paths, but then the link to the article does not work in Telegram notification messages, which is sad.

**Comment by umputun** [comment]
>  what happens if I change the domain

Migration already supported, see https://github.com/umputun/remark42/issues/412. Some day we will document this functionality.

**Comment by uPagge** [comment]
@umputun That is, you can not worry and use absolute links?

**Comment by umputun** [comment]
Not sure what you mean and how else it can work, especially if comments served from a different domain. In addition, a single instance of remar42 can provide comments for multiple sites.

**Comment by uPagge** [comment]
@umputun At first, I did not use this parameter in the configuration of `url: 'PAGE_URL'`.

Then, realizing that I could change the domain zone in the future, I thought about the comments and decided to use the parameter `url: 'PAGE_URL'` substituting a relative path there.

If in the future it is possible to change the domain in the comment database without any problems, I will give up this hack.

This is what I mean.

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/100498534-e4873b80-3173-11eb-930e-3a3fb75610b4.png)

it seems to be easy to do, so I'll give up the relative paths
