### ISSUE TITLE
Idea: View counter

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#823]
I would like to suggest the following idea: add to the script a component that will count the number of page views, nothing unusual and complicated, just views.

If a person refreshes a page, it will count for the second view.

This will be useful for sites on Hugo to display in pagination not only the number of comments to the article, but also the number of hits.

I think the idea is clear :)

**Comment by paskal** [comment]
I think it’s not a comment system functionality, and there are already various ways of achieving that. Implementing such a counter is trivial, but I don’t see it as a part of remark42.

**Comment by uPagge** [comment]
I would not say that it is a trivial task, I have not found ready-made solutions. 

I know it doesn't suit the system, but I thought it could be a useful function. well, no :)

**Comment by umputun** [comment]
I don't see how this even related to the system, I.e. remark42. Stats for a static site is a completely different domain and I see no reason to make it a part of the commenting system.
