### ISSUE TITLE
Multi Site Setting docker-compose

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#833]
Hello

I may have a silly problem, but I couldn't figure out how to install remark42 on 2 sites using docker-compose. One site works, the other site says "failed to prepare comment: can't get secret for site documentation: site documentation disabled".

Tried it both ways

- SITE=site1, site2
- SECRET = secret1, secret2

and so on

- SITE=site1
- SITE=site2

I would be glad to help

**Comment by paskal** [comment]
Can you please set `SITE=site1,site2` (with no spaces), `SECRET=secret` (as it's not multi) and let us know the results? If it wouldn't work, please post docker-compose logs for the remark42 container after it started, and you opened the second site which breaks, and I'll look into it.

**Comment by uPagge** [comment]
It worked for me.
