### ISSUE TITLE
Microsoft OAuth (social login) not working

### ISSUE THREAD

**Issue by zakiur** [umputun/remark42#838]
Docker logs does not read "init oauth2 service microsoft" when passing ENV variable 
AUTH_MICROSOFT_CID and AUTH_MICROSOFT_CSEC
Facebook, Google, Github all works when Docker ENV variable is passed
Microsoft does not pop up in the Docker logs.

2021/01/02 02:33:47.385 [INFO]  make avatar store, type=fs,
2021/01/02 02:33:47.385 [INFO]  init oauth2 service google,
2021/01/02 02:33:47.386 [INFO]  init oauth2 service github,
2021/01/02 02:33:47.386 [INFO]  anonymous access enabled,
2021/01/02 02:33:47.386 [INFO]  activate http rest server on port 8080

The website does not say Microsoft Social Login is supported, whereas it is mentioned as being supported in the GitHub readme.
Is it supported? Am I passing the wrong ENV variable, is it spelt differently? The logs should read "init oauth2 service microsoft" even if it is not setup correctly with ClentID and Secret right?

**Comment by umputun** [comment]
MS login supported but not released yet. I.e., if you run `:latest` or `:1.6.0` images, it won't work. However, if you switch to  `:master` - it will

**Comment by zakiur** [comment]
Thank you, yes `:master` does have support for MS login. Much appreciated.
