### ISSUE TITLE
Question: Switch to user account

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#843]
And there is an opportunity to go to the user's account on the social network?

**Comment by umputun** [comment]
I guess you talking about linking user to the social account he logged in? If this is the case - this info already presented in the used id and all we need is a navigation/link. Maybe from the last comments widget, not sure.

@akellbl4 - what do you think? Is it frontend-only thing, i.e. parse id and get the link or should be an API call, like to get the link?

**Comment by uPagge** [comment]
i tried to use google_bla_bla_bla id. To find a user somehow, but it did not give any results.

I would like to be able, at least for moderators, to go to the user's page on the social network

**Comment by umputun** [comment]
The user info you currently have is a name + authprovider_hash. You can go to auth provider (for instance github) and search by name. It may not work that good for other providers, for instance twitter, as you may have multiple twitter users with the same name, but I don't want to keep more details about user for privacy reasons. So, whatever we can get from the current name + user_id - fine with me, but adding the link to the social profile - nop.

**Comment by paskal** [comment]
Agreed, I'm against collecting any new info about the user, even the link to their social network profile.

**Comment by uPagge** [comment]
I understood you, it's a pity
