### ISSUE TITLE
Js error

### ISSUE THREAD

**Issue by yantonov** [umputun/remark42#851]
When you try to open last user comments, you will have:

Uncaught (in promise) ReferenceError: Fragment is not defined
    at E.tl [as constructor] (last-comments-list.tsx:17)
    at E.$ [as render] (preact.module.js:1)

It seems the cause of the problem is missing Fragment import at last-comments-list.tsx

**Comment by umputun** [comment]
@akellbl4 - something related to the recent refactoring?

**Comment by akellbl4** [comment]
Yep, @yantonov thanks for PR
