### ISSUE TITLE
Can i use Email login without verification?

### ISSUE THREAD

**Issue by NghiaMaster** [umputun/remark42#856]
Hello everybody. Im use remark42 on very small blog site, all comment are welcome and I don't want users to take more step to comment and get notification when they receive replied. I try with Anonymous but it cant subscribe via email.
Simply enter your name, email and comment. When they receive a reply they will receive an email notification. same as isso I used before. Thank you and sorry about my english

**Comment by paskal** [comment]
Hi @NghiaMaster, unfortunately, the only way to do what you want is to ask users to log in with email or any other way except anonymous auth.

With anonymous auth, nothing prevents me from logging in with the same name someone else used and changing their subscription settings or adding new messages that they will receive notifications for. We can't allow that even as an option.

**Comment by umputun** [comment]
> Simply enter your name, email and comment.

Unless a user has to confirm the login via email (and this is pretty much what our email auth does) this is not safe. For example, it can be used by bad actors as a way to send spam, just by entering victim's email and subscribing it to all notification.

**Comment by NghiaMaster** [comment]
> For example, it can be used by bad actors as a way to send spam, just by entering victim's email and subscribing it to all notifications

So if I ignore the risks, is there still no other way?

**Comment by umputun** [comment]
There is no way to allow anonymous users to get email notifications.

_P.S. Please note: for questions/discussions it is better to use  [Discussion](https://github.com/umputun/remark42/discussions) and keep issues for bug report and the actual tickets only_
