### ISSUE TITLE
Prepare release v1.7

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#859]
This ticket will be used to coordinate activity related to the new version release. 

/cc @paskal @akellbl4

**Comment by paskal** [comment]
My only concern before the release is that we should split Readme.md into multiple docs and make Readme almost empty. Properly structured doc is a must-have for a project of this complexity.

**Comment by akellbl4** [comment]
@umputun may we close this?

**Comment by umputun** [comment]
sure, closed
