### ISSUE TITLE
Add mocks to frontend

### ISSUE THREAD

**Issue by igoradamenko** [umputun/remark42#86]
When I need to develop something, I run `npm run dev` and use `localhost:8080/dev.html` to test new features. But there are some points that are OK for the only one developer, but they aren't fine for open source project.

This issue is about one of them — mocks.

Right now Remark doesn't have any mocks, and it's sad. You can see that we use some radio-t.com comments for testing UI:

https://github.com/umputun/remark/blob/c32f203f2b28dbca0791991e09b645f19cabfd70/web/dev.ejs#L32-L35

But it's hard to test features with PUT / POST methods because of CORS.

So the goal of the issue is to create mocks for all requests and env for using them. It's actually not so hard, because we use https://github.com/axios/axios for HTTP-requests, so you can start with adding https://github.com/ctimmerm/axios-mock-adapter, which makes creating mocks very handy in this case.

**Comment by jackburg** [comment]
This is good point. It's took me a while to get up and running properly configured dev frontend with the backend. It would be great if we could to develop some frontend features without properly configured backend.

**Comment by Guria** [comment]
Have you seen instructions to bring fully featured backend in a docker?

https://github.com/umputun/remark#testing

It isn't ideal right now, but I have a plans to improve. Though it good enough to start.

**Comment by jackburg** [comment]
Yes, It was my starting point. However some changes in the front-end config files were required for me to get this up and running.

**Comment by akellbl4** [comment]
It is not a big deal to run backend by `docker-compose` now and it works well. I think this PR not actual anymore.
