### ISSUE TITLE
Outdated "import from wordpress" plugin

### ISSUE THREAD

**Issue by rubentorresbonet** [umputun/remark42#871]
The plugin linked in the readme to export wordpress comments in [not accessible anymore](https://wordpress.org/plugins/wp-exporter/#description) due to security concerns, making it impossible to import wordpress comments in remark42.
Is there any alternative that exports them in the xml format remark42 expects?
Thanks

**Comment by umputun** [comment]
I'm not familiar enough with the actual state of wordpress and have no idea what the current way to export. However, if someone can share what kind of export wordpress supports, we could adjust remark42 with whatever needed.

Also, see the original ticket https://github.com/umputun/remark42/issues/156 and feel free to ping the author.

**Comment by enescakir** [comment]
I hit the same issue. Disqus has a plugin for importing comments from Wordpress, and remark42 has working Disqus importer. 
First I migrated my comments to Disqus, then I imported from Disqus to remark42.
`Wordpress -> Disqus -> remark42`

**Comment by likhanov** [comment]
There is no need to use third-party plugin for import comments from Wordpress.
Here is the standard way to export - https://wordpress.com/support/export/
![image](https://user-images.githubusercontent.com/1926497/115190934-6b23c180-a0f1-11eb-80f3-f4280f24b19e.png)

I imported the data with this tool and exported it to a test installation remark42.
Everything looks fine.
![image](https://user-images.githubusercontent.com/1926497/115189660-7d9cfb80-a0ef-11eb-8d4c-1ecd05465876.png)

Maybe just fixing the documentation is enough?
