### ISSUE TITLE
Question: Releases 

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#873]
You commit to master quite actively, but you don't release releases.

Is it worth updating for commits or is it better to wait for releases?

**Comment by umputun** [comment]
see https://github.com/umputun/remark42/issues/859

**Comment by paskal** [comment]
@uPagge we have very long release cycle at the moment, and the previous version was released long ago. I think the safest option is to stay on the master, updating when there are no code changes for a ~week which means that there are no obvious bugs requiring hotfixes discovered after the last set of changes (yet).

Releasing more often would mean that we (developers) will stay on master and mark these "one week in production with no issues" versions for our users ourselves.
