### ISSUE TITLE
I do not see a "send" button on iOS on iPad, Chrome browser, demo page

### ISSUE THREAD

**Issue by tbrowder** [umputun/remark42#875]
**UPDATE**

I just realized I had to login even as anonymous. After aving done that, the send button appeared and my test comment showed as the most recent comment.

**Comment by akellbl4** [comment]
@tbrowder hi!

Yep, now you should authorize and then you will see the button.
Shall I close the issue?

**Comment by akellbl4** [comment]
I think it's should be okay to close the issue. If you have any questions feel free to ask in discussions or reopen this issue.
