### ISSUE TITLE
404 on embed.mjs

### ISSUE THREAD

**Issue by MaxLap** [umputun/remark42#876]
Hello, after a fresh install that I just did, using docker compose. The comments won't load due to getting a 404 on: https://remark42.maxlap.dev/web/embed.mjs

Chrome 84.0.4147.105 on Ubuntu 16.04.

Editing the script to load comments by removing the 'm' seems to solve this issue.

I'm using apache2 as a reverse proxy to do the https. I doubt this would be the cause?

**Comment by akellbl4** [comment]
Hi, it's my fault. I'll change docs, because it was updated to next version and don't work with current version.

Try to use this script when you connect remark in html

```
<script>
  (function(c) {
    for(var i = 0; i < c.length; i++){
      var d = document, s = d.createElement('script');
      s.src = remark_config.host + '/web/' +c[i] +'.js';
      s.defer = true;
      (d.head || d.body).appendChild(s);
    }
  })(remark_config.components || ['embed']);
</script>

```

**Comment by akellbl4** [comment]
@MaxLap I've updated docs.

**Comment by MaxLap** [comment]
This works on my side. Thank you!
