### ISSUE TITLE
One instance for multiple sites?

### ISSUE THREAD

**Issue by mipimipi** [umputun/remark42#880]
Is it possible that I use one instance of remark42 for multiple sites (i.e. a web server is serving multiple sites and I want to use remark42 for all of them)? At least the documentation in the README suggests that (SITE parameter can have multiple values). But I did not find any documentation how to achieve this.
Otherwise, I assume that one must run one container instance per site. Correct?
Thanks, mipi

**Comment by umputun** [comment]
you can pass --site multiple times, i.e. `--site=foo --site=bar` or in env, comma-separated like `--SITE=foo,bar` (compose syntax). A single container with remark42 can handle multiple sites, no need to run one per site.

as you [setup your websites](https://github.com/umputun/remark42#setup-on-your-website) set appropriate `site_id` values, i.e. `foo` or `bar`

**Comment by umputun** [comment]
note: we have [Discussions](https://github.com/umputun/remark42/discussions) enabled and it is a better place to ask questions.

thx

**Comment by mipimipi** [comment]
Will do. Thx.
