### ISSUE TITLE
Image upload is broken

### ISSUE THREAD

**Issue by aprosvetova** [umputun/remark42#885]
I can't upload image anymore.
`/picture` endpoint responds with:
``` json
{
  "code": 2,
  "details": "can't parse multipart form",
  "error": "no multipart boundary param in Content-Type"
}
```

The bug is also live on radio-t, so I don't think it's my fault.

**Comment by akellbl4** [comment]
@aprosvetova thanks for report the problem. I'm going to check and fix it.
