### ISSUE TITLE
Post data via post message without serialization

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#897]
Sending data via post messages [works fine](https://caniuse.com/?search=post%20message) without any processing as a simple data structure.
It's completely unnecessary to stringify and parse JSON.

Now it's making logic more complex and unpredictable.

**Comment by paskal** [comment]
Would you be so kind as to post links to the code you are referring to?

**Comment by akellbl4** [comment]
https://github.com/umputun/remark42/blob/df92500bb41742dffb36f9d06fa26b506c72af1c/frontend/app/utils/postMessage.ts#L20
https://github.com/umputun/remark42/blob/5ec871fd372494318151d02ca45f3d677eabb7bb/frontend/app/embed.ts#L298 and below in this file
https://github.com/umputun/remark42/blob/df92500bb41742dffb36f9d06fa26b506c72af1c/frontend/templates/iframe.ejs#L165

I'm not sure If I found all of the places.

**Comment by Elephmoon** [comment]
Hello. I belive I can help with it.
