### ISSUE TITLE
Replace `parseQuery` with `URL`

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#898]
Remove `parseQuery` from the project and use browser API such as  `URL` or `URLSearchParams`. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)
It is [placed here](https://github.com/umputun/remark42/blob/master/frontend/app/utils/parseQuery.ts). We already started to use it [here](https://github.com/umputun/remark42/blob/c4832ff47a7a7929c30330e7ef0ba6613b1b4014/frontend/app/common/fetcher.ts#L39)

**Comment by Paras0-7** [comment]
Hii @akellbl4  May I  work on it.
