### ISSUE TITLE
Question: Indexing

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#900]
Are comments indexed by search engines? 

It's just rumored that this is a pretty important block on the site.

**Comment by akellbl4** [comment]
If your site is mobile-first only the latest comments will be indexed (number of the last comments determined by `max_shown_comments`). For desktop, all comments will be indexed. Maybe we will change something for full indexation of the comments with any circumstancesю

By the way, a better place for asking questions is [disscussios](https://github.com/umputun/remark42/discussions) ;)

**Comment by uPagge** [comment]
continued in discussion #902
