### ISSUE TITLE
Add Sign in with Apple

### ISSUE THREAD

**Issue by rakleed** [umputun/remark42#906]
Please add sign in with Apple ID. It would be more private compared to Google, Facebook and other social media. But it is more convenient than email, since you don't need to open an email client. Useful link: https://developer.apple.com/sign-in-with-apple/

**Comment by umputun** [comment]
Auth providers implemented as a part of go-pkgz/auth, see https://github.com/go-pkgz/auth/issues/61

**Comment by paskal** [comment]
Apple is already supported in the go-pkgz/auth, I assume what's left is to add backend support for it and then verify that it works in the frontend.

**Comment by paskal** [comment]
Backend part is added, frontend part is left.

**Comment by paskal** [comment]
Done:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/712534/211188475-6f570676-3ae7-434a-8f65-def17b227a9f.png">

<img width="293" alt="image" src="https://user-images.githubusercontent.com/712534/211188465-297dbc07-caf1-4d76-afc0-92c5143bc180.png">

<img width="529" alt="Screenshot 2023-01-04 at 10 37 13" src="https://user-images.githubusercontent.com/712534/210498158-90e59a80-79f4-4e78-826b-b4f987fd009e.png">
