### ISSUE TITLE
sign-in drop-down menu partially hidden

### ISSUE THREAD

**Issue by maxxedev** [umputun/remark42#910]
sign-in drop-down menu is partially hidden, possibly due to z-index issues?

Here is the screenshot:
https://i.imgur.com/kUZZm5h.png

Here is the page source:
https://pastebin.com/raw/YxAVuw5z

**Comment by maxxedev** [comment]
If I apply "z-index: auto" css to "auth-dropdown auth-module__dropdown_xyz" class, it appears correctly.

Or if there is a comment, it appears correctly.

**Comment by akellbl4** [comment]
@maxxedev thank you for testing the last version from the master branch. I'll check it today.
