### ISSUE TITLE
Should simple_view be a client-side setting?

### ISSUE THREAD

**Issue by aprosvetova** [umputun/remark42#916]
I have multiple websites using the same remark42 instance and I've set it to render `SIMPLE_VIEW`, cause I love it.

Today I decided to disable simple view for **one specific website** and realised that it's not only a backend setting, but also a global one!

Would love to see it near `locale` and other site-specific frontend options, cause it doesn't even affect any server-side logic, since remark42 has backend API and frontend separated (yeah I'm aware of [these plans](https://github.com/umputun/remark42/issues/825), but still).

**Comment by umputun** [comment]
this makes sense. @akellbl4 @paskal - what do you think?

**Comment by paskal** [comment]
It does make sense, however, I need to investigate how to do it as it's a backend option at the moment.
I only propose to keep existing settings as-is and add overwrites as a new section, so it won't break the config API.

**Comment by umputun** [comment]
I think we can do non-breaking change here, i.e. keep the backend option as-is and leverage it as a default value for UI. I.e. if no `remark_config.simple_view` defined on UI side it will work as-is.

**Comment by akellbl4** [comment]
I agree with you. It should be easy to do.

**Comment by Yuriy-Karpov** [comment]
PR https://github.com/umputun/remark42/pull/963

**Comment by akellbl4** [comment]
It's done and will available in the next version.
