### ISSUE TITLE
Profile info remains light when using dark theme

### ISSUE THREAD

**Issue by rakleed** [umputun/remark42#920]
## Description of the problem
Profile information and all of its comments remain light when using the dark theme.

## Steps to reproduce the problem:
1. Make sure that the dark theme is selected in the system and browser settings
2. Go to https://remark42.com/demo/
3. Click on any username

## Screenshot
![image](https://user-images.githubusercontent.com/19418601/111680478-52df2f00-8833-11eb-8e0c-00e224af17e9.png)

Related issue: https://github.com/radio-t/radio-t-site/issues/216

**Comment by akellbl4** [comment]
Thank you for the report.
It's not a bug :) the dark theme just wasn't implemented for that part but it should be done someday.
