### ISSUE TITLE
Unknown flag `auth.same-site'

### ISSUE THREAD

**Issue by OStrekalovsky** [umputun/remark42#928]
# Description
I'm trying to run local remark server (remark.local) to add comments for local Hugo site (blog.local). I enabled `auth.anon`  for tests, but in case of login I received warning in Google Chrome Dev Tools that `set-cookie` header was blocked because SameSite is `Lax`  and came from cross site response. So after authorization I don't get Remark Cookie (despite successful anon authorization) for auth and subsequent attempts to post a comment have failed.  So I tried to use `--auth.same-site=none` server run argument to bypass SameSite restriction.

# Env
* Version: remark42 master-71dcb13-20200426T12:41:26
* OS: Windows 10 (x64)

# Expected Behavior
Server should start with run argument `--auth.same-site=none` and set cookie with specified SameSite attribute value.

# Actual Behavior
Trying to run server with run argument  `--auth.same-site=none`  failed with message `Unknown flag 'auth.same-site' `.

In addition, maybe it is an UI issue that Remark widget does not show an error if cookie was not really set.

**Comment by umputun** [comment]
the version you have is too old for this flag. The last part of the version is date-time which is Apr 26, 2020. Support of same-site customization [was added](https://github.com/umputun/remark42/pull/850) on Jan 2021

Pls update your master or pull fresh umputun/remark42.master image
