### ISSUE TITLE
Add tests for frontend

### ISSUE THREAD

**Issue by igoradamenko** [umputun/remark42#93]
After adding mocks in #86 it's important to cover frontend by E2E-tests.

You are welcome to start this journey with a little PR which configures env for testing and adds some examples of them.

**Comment by slawiko** [comment]
@igoradamenko don't forget about https://github.com/umputun/remark/issues/96 . Smaller components easier to test. I propose to first split huge components on atomic parts and then add [testing](http://jestjs.io/docs/en/tutorial-react.html).

**Comment by umputun** [comment]
@Reeywhaar - was it addressed as a part of your massive refactoring? Can you take a look at issues like this one and update? I'm trying to prepare a new release and want to attach the list of tickets we have addressed

**Comment by Reeywhaar** [comment]
This is is indeed stale, it's tricky to write frontend tests properly, and no one bothers, including me. Though there is a lot of issues that were fixed long ago.

**Comment by akellbl4** [comment]
I think this issue not actual for now.
We have env for testing and some test, also we write tests for new features and write test in places what we change.

**Comment by paskal** [comment]
That was added in https://github.com/umputun/remark42/pull/1464.
