### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by ColdHeat** [umputun/remark42#938]
Hi there, do you have a security contact or way to otherwise disclose a potential security vulnerability in remark42?

**Comment by umputun** [comment]
feel free to email me directly, umputun@gmail.com

thx

**Comment by umputun** [comment]
Thx for providing the details. The fix was merged in, see  https://github.com/umputun/remark42/pull/939

No need to backport it to v1.6.1 as it used bluemonday v1.0.2

P.S. I have also added a security policy
