### ISSUE TITLE
Space character in the name when registering anonymously.

### ISSUE THREAD

**Issue by Ivan-Chupin** [umputun/remark42#957]
When registering anonymously, the space character is not allowed in the name. In addition, the error message is partially displayed in Russian.
![1](https://user-images.githubusercontent.com/83099323/116382109-02de8980-a82f-11eb-942a-694a1a0ac844.jpg)

**Comment by akellbl4** [comment]
The error is "Username must contain only letters, numbers, underscores or spaces". Rest of the text is provider by the browser. As I can understand you have Russian localization in your OS or at least in your browser.

**Comment by paskal** [comment]
Aside from localisation, asking user to use spaces and then refusing to allow them is a problem.

**Comment by umputun** [comment]
i see we [don't allow space in suffix and prefix](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L757 ) but it [should be fine](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L754) to have spaces inside the name

@akellbl4 is it UI-side filter rejecting those?

**Comment by akellbl4** [comment]
@umputun looks like that I'm going to check and fix it.

**Comment by umputun** [comment]
maybe you can disable entering prefix/suffix spaces too if not much trouble?

**Comment by akellbl4** [comment]
I can strip spaces on prefix/suffix on hover leave.

**Comment by umputun** [comment]
fine, whatever is easier will do
