### ISSUE TITLE
Imported comments (from disqus) gets a broken Avatar

### ISSUE THREAD

**Issue by damienalexandre** [umputun/remark42#958]
_First time posting here: thanks for this awesome tool!_

Using the Docker image `umputun/remark42:latest` I imported some Disqus comments.

Everything went smootly :+1: and here is a comment object for example:

```json
{
  "comments": [
    {
      "comment": {
        "id": "2258702761",
        "pid": "",
        "text": "<p>Salut,</p><p>Très bonne explication merci.</p>",
        "user": {
          "name": "Redacted",
          "id": "disqus_xxx",
          "picture": "",
          "admin": false
        },
        "locator": {
          "site": "xxx",
          "url": "https:/xxx.com/blog/xxx"
        },
        "score": 0,
        "vote": 0,
        "time": "2015-09-17T15:29:23Z",
        "imported": true,
        "title": "xxx"
      }
    }
  ],
  "info": {
    "url": "xxx",
    "count": 1,
    "first_time": "2015-09-17T15:29:23Z",
    "last_time": "2021-04-28T15:03:58.51542081Z"
  }
}
```

Looks nice to me BUT on the frontend here is the display:

![image](https://user-images.githubusercontent.com/225704/116451217-82368200-a85c-11eb-91d0-7df5f301af42.png)

The generated DOM is:

```html
<img class="avatar-icon avatar-icon_theme_light avatar-icon_default comment__avatar" src="[object Module]" alt="">
```

As you can see"[object Module]" is not a valid avatar url.

I can only suppose there is two issues:

- Disqus importer does not generate avatars for Users;
- the fallback in case there is no picture does not work: https://github.com/umputun/remark42/blob/e7950fcb22cca618f90db0db2218741f3847acab/frontend/app/components/avatar-icon/avatar-icon.tsx#L15

Thanks!

**Comment by umputun** [comment]
import from discuss won't bring avatars, but fail-back supposed to work. @akellbl4 likely one of you recent changes?

**Comment by akellbl4** [comment]
Hm. Last change there 2 years ago.
Maybe it's connected with updates of webpack. I'll check and fix it.

**Comment by Ivan-Chupin** [comment]
Avatars from Disqus can be imported quite easily - https://disqus.com/api/users/avatars/ {username }.jpg
This is documented in the Disqus API - https://disqus.com/api/docs/images/

**Comment by umputun** [comment]
good tip, but I don't think this is as easy as it sounds. Likely massive calls (during the import) may trigger some limiter on the Disqus API side

**Comment by umputun** [comment]
@damienalexandre this got  closed automatically by PR fixing it. Pls take a look and let me know if your issue fixed and imported avatars look better

**Comment by damienalexandre** [comment]
Problem fixed on master!

![image](https://user-images.githubusercontent.com/225704/116517442-438ddf80-a8cf-11eb-99ff-ac8fcfb8efab.png)

Thanks a lot for this really fast correction :muscle: @akellbl4 & @umputun :+1:
