### ISSUE TITLE
Nginx subdirectory set up not taken into account when creating "Sign in with ..." link

### ISSUE THREAD

**Issue by maxmastalerz** [umputun/remark42#961]
If you setup remark42 underneath a subdirectory like /remark42 instead of a subdomain the login with oauth link shows the base url only and does not show /remark42/. Clicking on the login with github link would obviously just 404 you. Using a subdomain works but with a subdirectory it doesn't unless you manually add in a nginx location to forward the oauth link with /remark42 preprended.

I only tried this with the github oauth.

**Comment by umputun** [comment]
pls see the [relevant docs](https://github.com/umputun/remark42/blob/master/docs/latest/nginx-proxy.md)

if you still have an issue pls provide your nginx config and remark42 config

**Comment by umputun** [comment]
because this is not a bug report I'll move it to Discussion
