### ISSUE TITLE
Find returns user while page doesn't have a comment

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#972]
**Steps to reproduce**
1. Leave a comment on a new page without comments
2. Remove the comment
3. Request users that left comments on that page via API: https://remark42.radio-t.com/api/v1/find?url={post_link}&sort=-time&site=radiot&view=user

<details>
<summary>Example</summary>

Page link: https://radio-t.com/p/2021/05/04/prep-753/

API request: https://remark42.radio-t.com/api/v1/find?url=https://radio-t.com/p/2021/05/04/prep-753/&sort=-time&site=radiot&view=user

<img width="495" alt="CleanShot 2021-05-05 at 08 39 17@2x" src="https://user-images.githubusercontent.com/2330682/117100844-7deaf700-ad7d-11eb-813a-86cf33face14.png">
</details>

**Comment by umputun** [comment]
should be fixed

**Comment by akellbl4** [comment]
Looks like fixed
