### ISSUE TITLE
Invalid avatar link when importing from Disqus

### ISSUE THREAD

**Issue by Ivan-Chupin** [umputun/remark42#987]
If Remark42 (version 1.8.1) is configured to work in the server directory, then when importing comments from Disqus, the path to the avatar (domain.com/web/avatar-icon.svg) turns out to be incorrect. It should be domain.com/**remark42**/web/avatar-icon.svg

**Comment by umputun** [comment]
@akellbl4 is it your side or mine? I think it is yours as all import made from disqus is an empty user.picture

**Comment by akellbl4** [comment]
It's should be my side.

**Comment by Ivan-Chupin** [comment]
@akellbl4 Could there be any other avatars when importing from an Disqus XML file? If you mean the normal work of Remark42, then the avatars are displayed normally.

**Comment by akellbl4** [comment]
Yes, I mean any other avatars because this problem isn't connected to importing from Disqus. It is connected to support remark on the same domain.

**Comment by Ivan-Chupin** [comment]
Except for the error when importing from Disqus, everything works fine.

**Comment by akellbl4** [comment]
I'll take a look at the problems related to wrong links while use remark42 on the same domain ;)
